### ISSUE TITLE
1.16: Essentials overwriting /msg command

### ISSUE THREAD

**Issue by socksprox** [kangarko/ChatControl#1008]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true

Hey!
Just disable chatcontrol internal message system and restart the server. It'll fix the issue

**Comment by socksprox** [comment]
Where can i disable this?

**Comment by ElBananaa** [comment]
> Where can i disable this?

In the `settings.yml` file.
```yaml
Private_Messages:
  
  # Should we enable this feature?
  Enabled: true # <---- Set this to false then restart the server
```
