### ISSUE TITLE
1.16.5 Multiple prefixes

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#1029]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

I want to have several prefixes that get activated based on a perm. 

The below extract from ../formats/chat.yml does not work.

```
  prefix:
    Message: '#ffb845✵ '
    Sender_Permission: badge.patreon
  prefix:
    Message: '#ffb845⁎ '
    Sender_Permission: badge.novice
```
    
  This does not work either:
  
```
    prefix:
    Message: '#ffb845✵ '
    Sender_Permission: badge.patreon
    Message: '#ffb845⁎ '
    Sender_Permission: badge.novice
```
