### ISSUE TITLE
1.16.5 chat color for rank

### ISSUE THREAD

**Issue by Rongel92** [kangarko/ChatControl#1090]
Hi, I was wondering if there's a permission or any other way to set it so once people get the first rank the chat color changes from default Minecraft gray color to white color without them putting in command but automatically?

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
> Hi, I was wondering if there's a permission or any other way to set it so once people get the first rank the chat color changes from default Minecraft gray color to white color without them putting in command but automatically?
> 
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false

Hey!
This can be achieved using the format system, here's an example of format based on permissions : 
```yaml
  message-default:
    Message: '&8&l» &7{message}'
    Sender_Permission: group.default
    Hover:
    - '&7Date: &b{timestamp}'

  message-level1:
    Message: '&8&l» &f{message}'
    Sender_Permission: group.level1
    Hover:
    - '&7Date: &b{timestamp}'

  message-level2:
    Message: '&8&l» &e{message}'
    Sender_Permission: group.level2
    Hover:
    - '&7Date: &b{timestamp}'
```
