### ISSUE TITLE
1.16.5: CHC logging passwords, how do I disable this functionality?

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#1103]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Hi there,

I've noticed that chat control also logs login attempts that match a given rule. Is there a way to add an exception so specific commands do not apply to the swear filter?

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false
> 
> Hi there,
> 
> I've noticed that chat control also logs login attempts that match a given rule. Is there a way to add an exception so specific commands do not apply to the swear filter?

Hey,
Yes you can use the `ignore command` operator in your rule to ignore specific commands from the swear filter.
You can find more infos about this identifier on the wiki page : https://github.com/kangarko/ChatControl-Red/wiki/Rules#ignore-command-command

**Comment by BearLeonLight** [comment]
```
Log:
  
  # What player actions should be logged?
  # Options: chat, command, private_message, mail, sign, book, anvil
  Apply_On:
  - 'chat'
  - 'command'
  - 'private_message'
  - 'mail'
  - 'sign'
  - 'book'
  - 'anvil'
  
  # The threshold after which we should clean the logs
  Clean_After: 90 days
  
  # Commands that will be saved along with the chat messages. To log all, set it to ["*"]
  # The Apply_On list must contain "command" for any commands below to be logged.
  Command_List:
  - '/tell'
  - '/w'
  - '/m'
  - '/t'
  - '/pm'
  - '/message'
  - '/msg'
  - '/whisper'
  - '/mail'
  - '/reply'
  - '/r'
  - '/me'
  - '/tag'
  - '/nick'
  ```
