### ISSUE TITLE
1.17: chatcontrol cant hook into the latest placeholderapi but every other plugin can :D

### ISSUE THREAD

**Issue by DoogiePC** [kangarko/ChatControl#1124]
Minecraft Version: 1.17
MySQL: true
BungeeCord: true

![image](https://user-images.githubusercontent.com/29175381/123675839-157b3c00-d83b-11eb-8ce9-a60c110012f9.png)

the formats worked in previous versions, nothing was changed except 1.17 and the new placeholderapi

**Comment by DoogiePC** [comment]
Also can you update chatcontrol-red to work with plotsquared v6, its not loading with v6

**Comment by Sikatsu** [comment]
Yeah, I have the same issue with plotsquared 6.

**Comment by ElBananaa** [comment]
Hey,
Sorry for the delay.
I'm unable to reproduce your issue on my side.
The plugin works flawlessly with placeholderapi as you can see on this screenshot, I was able to display the version, the ping and the coordinates using PAPI placeholders. 
![image](https://user-images.githubusercontent.com/53318613/123831109-43788300-d904-11eb-8b9b-7b394b5dc679.png)

This is on a completely fresh install with `ChatControl-Red-10.4.9, LuckPerms-Bukkit-5.3.48, NashornPlus-1.1.0, PlaceholderAPI-2.10.10-DEV (1.17 dev build which can be found on their discord), ProtocolLib b526 and Vault`. The server runs under Paper 1.17 (b63) & OpenJDK 16.0.1.

Here's the content of my chat.yml file : 
```yaml
Parts:

  delete-chat:
    Message: '&8[&4X&8] &f'
    Hover: '&cRemove this message from chat for all players.'
    Run_Command: /{label} internal remove {message_uuid}
    Receiver_Permission: chatcontrol.removemessages

  vip-prefix:
    Message: '&8[&6VIP&8] '
    Sender_Permission: chatcontrol.group.vip
  
  read-prefix:
    Message: '&8[&bRead&8] '
    Receiver_Condition: '''{player_channel_mode_{channel}}'' == ''read'''

  version-prefix:
    Message: '&8[&ev{server_version}&8] '

  ping-prefix:
    Message: '&8[&d{player_ping}ms&8] '

  coords-prefix:
    Message: '&8[&5{player_world}, x={player_x], y={player_y}, z={player_z}&8] '
  
  discord-prefix:
    Message: '&8[&9Discord&8] &f'
    Sender_Condition: '{sender_is_discord}'
    Hover: '&bJoin our Discord at mineacademy.org/discord'
    Open_Url: https://mineacademy.org/discord
  
  spies-prefix:
    Message: '&8[&5Spy&8] &f'
    Receiver_Condition: '{player_is_spying_{channel}}'
    Hover: '&dClick to stop spying {channel} channel.'
    Run_Command: /{label_spy} toggle chat {channel}

  prefix:
    Message: '{player_prefix+}'
    Hover:
    - '&7{player_prefix+}{player_name} {player_suffix}'
    - '&7Ping&8: &f{ping}ms'
    - '&7Rank&8: &f{player_group}'
    - '&7Posted: &f{timestamp}'
    - ''
    - '&7Click to learn more about ranks.'
    Open_Url: https://mineacademy.org/project-orion

  player-name:
    Message: '{player_nick}'
    Hover: '&7Click to message.'
    Suggest_Command: '/tell {player_name} '
 
  message:
    Message: '&7: {player_suffix}{message}'
```
The expansions used are `Server` and `Player`.


As for the Plotsquared issue, I don't own the plugin, so I'm unable to test it, but I guess this is due to the fact that they made some API changes.
