### ISSUE TITLE
SilentJoin support

### ISSUE THREAD

**Issue by Curtis73** [kangarko/ChatControl#1154]
Hey,
I've searched around and couldn't find anything so please forgive me if this has already been answered somewhere

We use Essentials to hide our staff when they don't want to be seen, but ever since updating to ChatControl Red, staff with silent join permissions still have their join & leave messages broadcast to the server, which is a slight pain.
Would it be possible to add integration for this with Essentials, or maybe give ChatControl a permission node of its own if we don't want join/leave messages to be shown?

Thank you!

**Comment by VyperzDev** [comment]
if you have chatcontrol on the bungee/proxy server You can edit it in the config to turn it off. 
```yaml
Messages:
  
  # Broadcast messages when player joins/quits the network or switches servers?
  Enabled: false
  
  # List of server names (see the header) that we ignore from broadcasting
  # Server_Aliases NOT SUPPORTED 
  Ignored_Servers:
  - 'silent_server'
  
  # Send messages below to the player that triggered them?
  Send_To_Target: true
  
  # Sent to all players on the network.
  # Player with 'chatcontrol.silence.join' won't have a join message.
  Join_Message: '&8[&a+&8] &e{player} &fjoined the network &7({to_server})'
  
  # Only sent to the server to which player joined.
  Join_Target: '&8[&a+&8] &e{player} &fjoined the network'
  
  # Sent to all players on the network.
  # Player with 'chatcontrol.silence.leave' won't have a leave message.
  Leave_Message: '&8[&c-&8] &e{player} &fleft the network &7({from_server})'
  
  # Only sent to the server which player abandoned.
  Leave_Target: '&8[&c-&8] &e{player} &fleft the network'
  
  # Sent to all players on the network.
  # Player with 'chatcontrol.silence.switch' won't have a server switch message.
  Switch_Message: '&8[&d>&8] &e{player} &fhas switched from &7{from_server} &fto &7{to_server}'
  
  # Only sent to the server to which player switched from another server.
  Switch_Message_To: '&8[&d>&8] &e{player} &fhas switched from &7{from_server}'
  
  # Only sent to the server from which player left to another server.
  Switch_Message_From: '&8[&d>&8] &e{player} &fhas switched to &7{to_server}'

  # Only sent when the player joins for the first time
  First_Join_Message: '&8[&d+&8] &6{player} joined for the first time'
```
