### ISSUE TITLE
Add new permission for chatcontrol.bypass.delay.messages and chatcontrol.bypass.delay.commands

### ISSUE THREAD

**Issue by WolverStones** [kangarko/ChatControl#1158]
Currently there are chatcontrol.bypass.delay permissions, but I think a better solution is to split these two permissions, because for example if I want to allow vip only delay messages, then I can't. I need to give them permissions for both of these bypasses in ChatControl Pro these perms have been separated

**Comment by TheIntolerant** [comment]
This can be done in ``settings.yml`` under ``Groups``
To create a bypass for messages you might want to do something like
```yml
# -------------------------------------------------------------------------------------------------
# Apply different the settings from this file for people with certain permissions.
# See https://github.com/kangarko/ChatControl-Red/wiki/Groups for a quick tutorial.
#
# You can create and remove sections below as you wish. Then give chatcontrol.group.<section>
# permissions and the options for that sections will apply for people with that permission.
# Example: people with chatcontrol.group.admin permission will have no chat message delay.
#
# Available options with their example values:
#   Max_Read_Channels: 1
#   Message_Delay: 2 seconds
#   Message_Similarity: 50 # means 50%
#   Command_Delay: 3 seconds
#   Command_Similarity: 50 # means 50%
#   Rejoin_Cooldown: 4 seconds
#   Sound_Notify_Color: "&6"
# -------------------------------------------------------------------------------------------------
Groups:
  vip:
    Message_Delay: 0 seconds
```
``Message_Delay: 0 seconds`` = disabled
You would need to assign the permission ``chatcontrol.group.<section>``
In this case, as the group is VIP, the perm would be ``chatcontrol.group.vip``
