### ISSUE TITLE
1.16.5 Paper: How to seperate Discord message hover from normal message hover?

### ISSUE THREAD

**Issue by Zalaee** [kangarko/ChatControl#1165]
![image](https://user-images.githubusercontent.com/79696158/126533743-e0eef46e-83e3-4907-b7f0-bcab4299a0cc.png)

How to seperate discord message hover from normal chat messages? From normal players this hover looks correct with all placeholders working, but hover also applies to discord messages causing placeholders not to work.

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
> ![image](https://user-images.githubusercontent.com/79696158/126533743-e0eef46e-83e3-4907-b7f0-bcab4299a0cc.png)
> 
> How to seperate discord message hover from normal chat messages? From normal players this hover looks correct with all placeholders working, but hover also applies to discord messages causing placeholders not to work.
> 
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false

Hey,
This can be done using the `Sender_Condition` variable and one of our placeholders
Here's an example : 
```yaml
  discord-sender-hover: 
    Message: "&f{message}"
    Sender_Condition: "{sender_is_discord}"
    Hover: "&bThis message was sent by a discord user"

  ingame-sender-prefix: 
    Message: "&f{message}"
    Sender_Condition: "{sender_is_discord} == false"
    Hover: "This message was sent from the console or from an ingame player"
```
You can find more informations about the format variables on this page https://github.com/kangarko/ChatControl-Red/wiki/Formats and your can find more informations about our placeholders here : https://github.com/kangarko/ChatControl-Red/wiki/Variables

Let me know if it works properly.
