### ISSUE TITLE
1.17.1: sender_is_discord in formats true for everyone

### ISSUE THREAD

**Issue by saschahi** [kangarko/ChatControl#1168]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: false

I have my Discord chat connection running for a while now. after updating to 1.17.1 (and also updating a lot of plugins at the same time) this this is now being added to every message from any player, and not just those from discord.

```
  discord-prefix:
    Message: '&8[&9Discord&8] &f'
    Sender_Condition: '{sender_is_discord}'
    Hover:
    - '&bJoin our Discord at discord.gg/discordcode'
    Open_Url: https://discord.gg/discordcode
```

debug: https://ufile.io/ylmke331
