### ISSUE TITLE
 clearer wiki how to set up spy and submits my own proposal

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl#117]
Hi, if I´m not miss it you has not add how to set up settings for spy and expiation. So I do it here and you can review it and do you own version of it :)

So i you want set up your spy on channels.

Basic settings, all this add global on each type. You have settings how it look ingame chat in /plugins/ChatControlRed/formats, it is spy.yml ,spy-mail.yml,spy-sign.yml, spy-book.yml and spy-anvil.yml. For how to config look on chat.yml

Settings for the chat is this, you can change **spy** if you whant have different name on your spy.myl file, this get use when you not set it up your own for a channel or use that in chat.yml.
```
  # Format used to spy chat messages.
  # Exclude prefix from above since we already have a custom one in the "chat" format that we use.
  Format_Chat: '@noprefix spy'
```
If you use @noprefix this get not clouded in settings. 
```
  # What prefix should we display before all formats below?
  Prefix: '&8[&5Spy&8] '
```
Look like this ingame, when use different type of spy for channels
![spydiffrent1](https://user-images.githubusercontent.com/16368286/99701826-45888280-2a95-11eb-9a29-6e160907994a.PNG)

Standard spy.  
```
# -------------------------------------------------------------------------------------------------
# Spying allows to see messages, commands, private messages, books, renamed items and more
# from other players. Talking about privacy rights!
#
# [TIP] Give staff chatcontrol.spy.autoenable permission to auto enable spy on join.
# -------------------------------------------------------------------------------------------------
Spy:
  
  # Where should we enable this feature?
  # Options: chat, command, private_message, mail, sign, book, anvil
  Apply_On:
  - 'chat'
  - 'command'
  - 'private_message'
  - 'mail'
  - 'sign'
  - 'book'
  - 'anvil'
  
  # What prefix should we display before all formats below?
  Prefix: '&8[&5Spy&8] '
  
  # The commands that manually show the motd to the player.
  # EDIT AS YOU WISH BUT DO NOT REMOVE THE FIRST ALIAS
  Command_Aliases:
  - 'spy'
  
  # Format used to spy chat messages.
  # Exclude prefix from above since we already have a custom one in the "chat" format that we use.
  Format_Chat: '@noprefix spy'
  
  # Format used to spy commands.
  Format_Command: '&7{player}: &f{message}'
  
  # Format used to spy private messages.
  Format_Private_Message: '&7{sender} &8-> &7{receiver}: &f{message}'
  
  # Format used to spy mails.
  Format_Mail: spy-mail
  
  # Format used to spy signs.
  Format_Sign: spy-sign
  
  # Format used to spy books.
  Format_Book: spy-book
  
  # Format used to spy renamed items.
  Format_Anvil: spy-anvil
  
  # List of commands we should spy. Mail and PMs are spied using their own method. You can use
  # the @blacklist feature as described in the header of this file.
  #
  # We only evaluate the list against the command label such as "/tell", meaning anything later
  # in the command does not matter! "/tell kangarko ahoj" -> only "/tell" will be matched
  # TO DISABLE SPYING ON COMMANDS, SET THIS TO [] OR REMOVE "command" FROM Apply_On SETTING ABOVE
  Commands:
  - '@blacklist'
  - '/register'
  - '/reg'
  - '/login'
  - '/l'
```
Here can you you set up spy for every channel and you can set unique spy format for every Chanel if you wants.
You change from **chat** to what yml file you have for example range-spy (do not include .yml).

```
standard:
      Format: chat
      Format_Spy: '@noprefix chat'
```
Standard spy settings. 
```
  # Channels are preconfigured public chat rooms where players can message each other.
  # You can add various keys and remove those you don't use, see this tutorial:
  # https://github.com/kangarko/chatcontrol-pro/wiki/Channels
  #
  # Channel options:
  #
  # - Format: The only mandatory option. Represents the style of the message 
  #   when sent into the channel. Either type the format directly such as "{player}: {message}"
  #   there, or type the name of a Format from your formats/ folder, such as "chat" if your format
  #   file is called chat.yml. Formats can have fancy hoverable and clickable parts.
  # - Format_Console: Overrides the console format from above. Set to "none" to hide.
  # - Format_Discord: Overrides the discord format from above. Set to "none" to hide.
  # - Format_Spy: Overrides the spy format from the "Spy" section below. Set to "none" to hide.
  # - Range: How far in blocks around player should others see the message?
  #   To make the range per-world, set it to "*", otherwise set it to a number
  #   such as "50" that would be 50 blocks around the sender.
  #   Staff with chatcontrol.bypass.range permission will reach everyone on all worlds.
  #   Players with chatcontrol.bypass.range.world will reach everyone on the same world
  #   and linked worlds.
  # - Range_Worlds: If "Range" is set to "*", which means everyone on world sees the message,
  #   this is a list of worlds that are connected where players chat together.
  # - Bungee: true/false if we shall send data over BungeeCord?
  #   If this is not set, uses the global setting from Integration below.
  # 
  # The Party option does not work over BungeeCord! 
  # Party:
  #
  List:
    standard:
      Format: chat
      Format_Spy: '@noprefix chat'
    admin:
      Format: admin-chat
      Format_Console: '[A-chat {player}] {message}'
    global:
      Format: global-chat
    ranged:
      Format: '&6[ranged] &7{pl_prefix+}{player}:{pl_suffix} {message}'
      Range: 100
      Bungee: false
    towny:
      Format: chat
      Party: towny-town
    helpop:
      Format: helpop
      

```
