### ISSUE TITLE
Pre-purchase question : AntiSpam feature

### ISSUE THREAD

**Issue by blockswerker** [kangarko/ChatControl#1172]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Hello, I have a quesiton and was not sure where else to ask. I run an anarchy server and players use spam bots that repeat phrases from a script with random characters appended. It's very easy for them to change the script and set the spam rate low enough that it does not trigger conventional chat flood mechanisms - usually one message every 5-10 seconds (it can be set).

I have not installed ChatControl-Red yet, but I will buy it and use it if it can help with my scenario.

I've proposed to other anti-chat spam developers that they add a feature to look for messages sent on a timed basis or to compare messages across longer time frames to identify repeated patterns but so far none have taken up my request.

Is ChatControl-Red my solutioin?

**Comment by ElBananaa** [comment]
Hey!
Idk if this is what you're looking for, but the plugin includes a antispam feature, yes.
You can configure it in the main config file, and can chose to block messages based on a similarity percent, a similarity for previous messages (So if you say 5, it'll compare a player's last message to his 5 previous messages), a similarity time limit check, etc...

Here's how the entire Anti-Spam part looks like in the config file : 
```yaml
# -------------------------------------------------------------------------------------------------
# Prevent flooding the chat with junk / repetitive messages.
# -------------------------------------------------------------------------------------------------
Anti_Spam:
  
  # true = Similarity checks below used in chat and commands will compare two messages with their
  # diacritical marks removed (such as á is turned into a) - THIS MAY BREAK RUSSIAN and other
  # languages but prevents bypassing similarity filter for English and European servers
  Similarity_Ignore_Accents: true
  
  # Settings applied to chat:
  Chat:
    
    # How many seconds must the player wait between each message? Set to 0 to disable.
    Delay: 1 second
    
    # Block repetitive messages if they are similar to the previous one, in percent.
    # Set to 0% to disable.
    Similarity: 0%
    
    # The amount of previous messages to check. Prevents spam like this:
    # <player> t
    # <player> lol
    # <player> t
    # <player> lol
    # Since this uses the Similarity key above it only works if Similarity is not disabled.
    Similarity_Past_Messages: 2
    
    # The threshold after which we will forgive the player for writing the same message.
    Similarity_Time: 10 seconds
    
    # Regular expressions that, if match the message, will prevent delay check from applying.
    Whitelist_Delay: []
    
    # Regular expressions that, if match the message, will prevent similarity check from applying.
    Whitelist_Similarity:
    - '^hello \w+$'
    - '^hey \w+$'
    - '^hi \w+$'
    
    # Limit how many messages the player can send in the given period,
    # for example you can restrict sending maximum 5 messages in the last 10 seconds.
    # This works differently then the delay check above because players
    # can type their messages rapidly after each other as long as the total number
    # of messages within the period is lower than the limit.
    Limit:
      
      # The period to check. Set to 0 to disable.
      Period: 10 seconds
      
      # How many messages can players send maximum in the period above?
      Max_Messages: 4
  
    # Block players repeating what others said.
    Parrot:
    
      # Enable this feature?
      Enabled: false
    
      # When scanning for others' messages, only take in account messages newer than this period:
      Delay: 1 second
    
      # How similar must the message be (in percent from 0% to 100%) to be blocked?
      Similarity: 85%
    
      # Regular expressions that, if match the message, will prevent parrot check from applying.
      # By default allow players repeating "hello/hey/hi" and/or with using another player's name.
      Whitelist:
      - '^(hello|hey|hi)( \w+|)(!|)$'
```

Let me know if you need anything else.
