### ISSUE TITLE
1.17.1: Disable general spy

### ISSUE THREAD

**Issue by JustDriessen** [kangarko/ChatControl#1180]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: false

Hello,

I was wondering how I am able to have auto spy enabled for all chats but not for my general chat, this due to everyone is able to see the general by theirselfs ofcourse. I tried to delete some configuration settings in the settings.yml but it did not seem to work.

Is there a tutorial on what to delete or maybe a permission node I am able to deny for everyone for a certain chat channel?

Thanks in advance, BTW I really enjoy using this plugin!

**Comment by ElBananaa** [comment]
Hey!
You can disable spying a specific channel using `/spy toggle chat <channel> <player>`.
You can find more infos about this on our dedicated wiki page : https://github.com/kangarko/ChatControl-Red/wiki/Spy

**Comment by JustDriessen** [comment]
I know that there is a command for it, I just have spy on auto. And I just need to have the general chat off as standard, the command /spy toggle chat general is not saved so you will have to type that every time you are on the server. I am hoping that there is a permission that I am able to set to deny the spying of the General chat completely, spying on the general chat is useless due to everyone having access to that chat, so you are just getting the message twice.

And typing the command everytime is just really annoying to do.

So am I able to:
- Set a certain permission to negative
- Delete the whole spying for the general chat specificly

**Comment by ElBananaa** [comment]
Alright, set `Channels.List.General.Format_Spy`, to `none` in your settings file, it should fix the issue.
Here's an example with my own config:
```yaml
  List:
    general:
      Format: general-chat
      Format_Spy: none
    staffchat:
      Format: staff-chat
      Format_Console: '&7『&c&lSTAFFCHAT&7』{player_prefix} &r{player} &8&l» &r{message}'
```

**Comment by JustDriessen** [comment]
I got this currently but it doesn't disable spy chat for General

```yaml
  List:
    general:
      Format: Chat
      Format_Spy: none
    range:
      Format: Range
      Range: 100
      Format_Spy: '@noprefix chat'
    town:
      Format: Town
      Party: towny-town
    nation:
      Format: Nation
      Party: towny-nation
```
