### ISSUE TITLE
1.17.1: Sender Condition Bypassed

### ISSUE THREAD

**Issue by dbdevc** [kangarko/ChatControl#1201]
Hi, sorry for bothering. I have watched tutorials/read wiki, but I'm really struggling with this issue. It looks like sender condition doesn't work. I have all prefixes listed before my name. It's like [DISCORD] [X] [Y] minecraftname: message. So even If I send a message through Minecraft chat I get discord prefix.

Here's our code in chat.yml:

```
Parts:
  
  # Show the [Discord] prefix if the sender is from Discord (we use our own
  # special variable for this) and add some interactive elements.
  discord-prefix:
    Sender_Condition: '{sender_is_discord}'
    Message: '&8[&9Discord&8] &8• &f{player_name} &8»'
  PlayerPrefix:
    Sender_Permission: essentials.afk
    Message: '{luckperms_prefix} &8• '
  PlayerName:
    Sender_Permission: essentials.afk
    Message: '&f{player_name} '
  PlayerTag:
    Sender_Permission: essentials.afk
    Message: '{alonsotags_tag_chat} &8»'
  Message:
    Message: ' &f{message}'
```

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false
