### ISSUE TITLE
1.16.5 Paper: Trailing not removed for hex color

### ISSUE THREAD

**Issue by MandelV** [kangarko/ChatControl#1218]
Minecraft Version: 1.16.5
Java Version : 11
MySQL: true
BungeeCord: true

Hello,

Despite the fix #1113  / version 10.5.0 The trailing character '&' remains displayed
I'm using last version of Luckperm, Vault, ProtocolLib and PlaceholderAPI  

![image](https://user-images.githubusercontent.com/22980065/128634645-e49b8fc4-cb9c-4e57-99b2-59a61b89b3bf.png)

Also it seems to work for messages but add a space :

![image](https://user-images.githubusercontent.com/22980065/128634739-b91c6480-2519-4435-b5c0-cd8973c37181.png)

Configuration format admin-chat.yml :

```yml
Parts:
  
  # See the chat.yml format file for a tutorial on how this works.
  everything:
    Message: '&8[&4{channel}&8]&r {luckperms_prefix}{display_name}: &f{message}'
```

I probably miss something to configure but I can't find where ^^'

Best,
