### ISSUE TITLE
1.16.5 | command  for Anti_Spam not work soo good any more

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl#1224]
I has try it own own server with limit amount of plugins and get same issue. When a player write cmi rankinfo it work fine, but if they do cmi rankup they get a warning directly and not run the command (has not check if other plugins has same issue with your Anti_Spam  ). but are only some commands some trigger this.

Has other cmi commands some has same issue, but that one works even if you get warning (probably for we admin´s has more perms an players). 

has work fine on this ChatControl-Red-10.3.8 version before, with no issues and I has try on a testserver 10.5.2 same issue. 

Has try change command settings but that not fix it.

Minecraft Version: 1.16.5 paper
MySQL: false
BungeeCord: false
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6969262/debug.zip)

**Comment by broken1arrow** [comment]
I don´t know if it break after like 47 players spam commands at same time ingame (boots). I think it was just before the problem start (if I not had the problem for longer time and miss it).

Has similar setup on testserver and use a normal player perm account there, is no issues.  I run cmi 8.5 and now update to 9.0.2.5 same issue.

**Comment by ElBananaa** [comment]
Hey!
If it works fine on a test server with a clean install, your issue is most likely caused by another plugin or a config issue.
I'd still suggest to wait for Kangarko, but in the meantime, you should also consider reviewing your files/configurations.

**Comment by broken1arrow** [comment]
> Hey!
> If it works fine on a test server with a clean install, your issue is most likely caused by another plugin or a config issue.
> I'd still suggest to wait for Kangarko, but in the meantime, you should also consider reviewing your files/configurations.

I has not touch the config for months and i know it works fine before. I have now update to see if it fix the issue. I use same config on the testserver and plugins.

I try the zip file (from the problem server) on my local computer and get same issue. So i think is the log/database are the problem because 47 boot's spam over 100 command's in one tick. I can test remove log and/or db and see if it fix the issue. 

This parts should be included in the zip too.

**Comment by broken1arrow** [comment]
I downloaded the zip here and make sure is right file i uploaded and yes i find out is the data.db some are the problem. 

So 47 boots seams to break chc, i don´t know if it was the login some or the flood of commands. 

But I don´t see any errors inside the db file. I don´t know if it username or something else trigger this bug.

**Comment by ElBananaa** [comment]
> I downloaded the zip here and make sure is right file i uploaded and yes i find out is the data.db some are the problem.
> 
> So 47 boots seams to break chc, i don´t know if it was the login some or the flood of commands.
> 
> But I don´t see any errors inside the db file. I don´t know if it username or something else trigger this bug.

Hey,
I see, this looks like a pretty weird issue.
I'm not sure if this is either related to the plugin, or related to something else.
I don't think the database even stores the rules, which is even weirder.
So, is your issue currently fixed?

I'd still suggest leaving it open so Kangarko can see it, even if it's been fixed by deleting the database, since, I guess, he may be able to do something about it.

**Comment by broken1arrow** [comment]
> > I downloaded the zip here and make sure is right file i uploaded and yes i find out is the data.db some are the problem.
> > So 47 boots seams to break chc, i don´t know if it was the login some or the flood of commands.
> > But I don´t see any errors inside the db file. I don´t know if it username or something else trigger this bug.
> 
> Hey,
> I see, this looks like a pretty weird issue.
> I'm not sure if this is either related to the plugin, or related to something else.
> I don't think the database even stores the rules, which is even weirder.
> So, is your issue currently fixed?
> 
> I'd still suggest leaving it open so Kangarko can see it, even if it's been fixed by deleting the database, since, I guess, he may be able to do something about it.

Has only try this on a test server to remove db. And only thing it store beside player UUID are points but not see any strange inside this. 

So has wait to remove db on main, some data i don't to be removed.

**Comment by kangarko** [comment]
What is the exact anti-spam message the players see when they run "/cmi rankup"? What part of anti-spam is this triggering?

**Comment by broken1arrow** [comment]
> 
> 
> What is the exact anti-spam message the players see when they run "/cmi rankup"? What part of anti-spam is this triggering?

Please wait one 1 second before your next command. has work fine before with my settings and try on test server remove db and it solve the issue.

**Comment by kangarko** [comment]
Going to reproduce right now.. Until I do, do you remember the exact commands typed? Such as /cmi rankup admin etc etc

**Comment by broken1arrow** [comment]
> 
> 
> Going to reproduce right now.. Until I do, do you remember the exact commands typed? Such as /cmi rankup admin etc etc

I has admin perms for chc but not bypass, I are not op. /cmi rankup or /rankup are no differences, /cmi holograms are other command some notis not work perfect (when you create a holo for example, you will get the warning, but will still create the holo). but are only admins some can use that command.

And /cmi rankup admin do not exist what I know.

**Comment by kangarko** [comment]
I installed CMI, /rankup does not work, that is not a fault of ChatControl, but /cmi rankup works fine.

The 1 seconds delay is applied correctly: https://www.loom.com/share/901db7d34c984e84acef03558c81a69e

What exactly is the problem you are facing here?

**Comment by broken1arrow** [comment]
> 
> 
> I installed CMI, /rankup does not work, that is not a fault of ChatControl, but /cmi rankup works fine.
> 
> The 1 seconds delay is applied correctly: https://www.loom.com/share/901db7d34c984e84acef03558c81a69e
> 
> What exactly is the problem you are facing here?

The problem is has not done like that last time I try it out for one moth ago. was it no issue with any command. But if I remove db it start to work as it should.

**Comment by broken1arrow** [comment]
And is probably not setup 100% right in the zip, because I try to change the values if that mess it up.

```
  # Settings applied to commands:
  Commands:

    # How many seconds must the player wait between each command? Set to 0 to disable.
    Delay: 0 seconds

    Similarity: 80%
    

    Similarity_Past_Commands: 3

    Similarity_Time: 1 seconds
    

    Whitelist_Delay: []
    
 
    Whitelist_Similarity:
    - '/tag'
    - '/nick'
    
    Limit:
      Period: 1 seconds
      Max_Commands: 10
```

**Comment by broken1arrow** [comment]
It should be this we has run all the time on the server with no issues.

**Comment by broken1arrow** [comment]
The strange now is somehow fixed on the testserver, but has the problem on the real server still. Will download a zip from that server again.

**Comment by kangarko** [comment]
Just to be clear, are you saying that if the Commands.Delay is set to "0 seconds", the antispam will ignore this and still say "Please wait X seconds" ?

**Comment by kangarko** [comment]
We have improved our antispam since, namely added support for ignoring online player names, that is why the behavior is different right now. I am not clear on what is the exact issue you are having now.

**Comment by broken1arrow** [comment]
> 
> 
> Just to be clear, are you saying that if the Commands.Delay is set to "0 seconds", the antispam will ignore this and still say "Please wait X seconds" ?

yes, but seams it fixed it self somehow. Was on 0 but try change it. Will look on my old backup.

look like this, but was some month old now (but I think no one has change this settings after that). Only I after get some problems.
```
  # Settings applied to commands:
  Commands:
    
    # How many seconds must the player wait between each command? Set to 0 to disable.
    Delay: 0 seconds
    
    # Block repetitive commands if they are similar to the previous one, in percent.
    # Set to 0% to disable.
    Similarity: 0%
    
    # Amount of previous commands to check. Example: Setting this to 2 prevents spam like this:
    # /tell Notch lol
    # /tell Notch t
    # /tell Notch lol
    # /tell Notch t
    # Since this uses the Similarity key above it only works if Similarity is not disabled.
    Similarity_Past_Commands: 1
    
    # The threshold after which we will forgive the player for running the same command.
    Similarity_Time: 10 seconds
    
    # Commands the player can type bypassing the Delay above. We check the command label
    # so if you put "/tell" there, "/tell ANYTHING" will be matched.
    #
    # Whitelist_Delay:
    #   - /spawn
    #   - /hello
    Whitelist_Delay: []
    
    # Commands the player can type bypassing the Similarity above. We check the command label
    # so if you put "/tell" there, "/tell ANYTHING" will be matched.
    #
    # Whitelist_Similarity:
    #   - /tell
    #   - /pm
    #   - /t
    #   - /w
    #   - /r
    Whitelist_Similarity:
    - '/tag'
    - '/nick'
    
    # Limit how many commands the player can send in the given period,
    # for example you can restrict sending maximum 5 commands in the last 10 seconds.
    # This works differently then the delay check above because players
    # can type their commands rapidly after each other as long as the total number
    # of commands within the period is lower than the limit.
    Limit:
      
      # The period to check. Set to "0 seconds" to disable.
      Period: 0 seconds
      
      # How many messages can players send maximum in the period above?
      Max_Commands: 4

```
