### ISSUE TITLE
1.16.5 format chat from discord to minecraft

### ISSUE THREAD

**Issue by donvdp** [kangarko/ChatControl#1234]
Hi there,

How to format the ingame chat when i send a message from discord to my ingame chat?

I am able to format the messages that are being send FROM minecraft TO discord. Now i am trying to find a way to format the messages that are being send FROM discord TO minecraft.

my channels below: ive linked the admin channel to my discord and gave it the format: "Format_Discord: '{server_name} {player}: {message}'"
![image](https://user-images.githubusercontent.com/10013800/129462565-a0f63ed1-aef3-462e-a446-83691e930deb.png)

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

**Comment by donvdp** [comment]
The way i understand the functionality is that::
![image](https://user-images.githubusercontent.com/10013800/129462697-70fb0317-9ce9-4b89-85f4-1d8652949eda.png)
The "admin-chat.yml" file contains the formatting of the adminchannel in the minecraft game. so is there a setup that i can use inside the "admin-chat.yml" file so that i can format a message from discord to minecraft?

Perhaps anyone here has an example ?

**Comment by ElBananaa** [comment]
> Hi there,
> 
> How to format the ingame chat when i send a message from discord to my ingame chat?
> 
> I am able to format the messages that are being send FROM minecraft TO discord. Now i am trying to find a way to format the messages that are being send FROM discord TO minecraft.
> 
> my channels below: ive linked the admin channel to my discord and gave it the format: "Format_Discord: '{server_name} {player}: {message}'"
> ![image](https://user-images.githubusercontent.com/10013800/129462565-a0f63ed1-aef3-462e-a446-83691e930deb.png)
> 
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true

Hey!
I believe the format used for messages sent on discord to minecraft is the one used for the channel itself.
If you'd like to use a specific format dedicated to discord, you could play with the `Sender_Condition` and `Sender_Condition`.
So here's an example:

```yaml
Parts:
#All parts starting with "global"- won't need the `Require_Sender` or `Require_Receiver` argument because they are shown wether the sender is a discord user or an ingame player.
  global-delete-chat:
    Message: '&7[#cf0e00&lX&7] '
    Receiver_Permission: chatcontrol.removemessages
    Hover:
    - '&cClick to delete this message.'
    Run_Command: /{label} internal remove {message_uuid}

#All parts starting with "minecraft-" will only be shown when a player sends a messages from the game.
  minecraft-report-player:
    Message: '&c⚠ '
    Sender_Permission: chatcontrol.allowreport
    Sender_Condition: '{sender_is_player} == true'
    Receiver_Permission: chatcontrol.allowreport
    Hover:
    - '&e&lClick to report &c{player}&e.'
    Suggest_Command: /report {player}
  minecraft-spy-prefix:
    Message: '&c&lSPY&8&l| '
    Sender_Condition: '{sender_is_player} == true'
    Receiver_Condition: '{player_is_spying_{channel}}'
    Hover:
    - '&cClick to stop spying the &e{channel}&c channel.'
    Run_Command: /{label_spy} toggle chat {channel}
  minecraft-prefix:
    Message: '{player_prefix}'
    Sender_Condition: '{sender_is_player} == true'
    Hover:
    - '&7{player_prefix}{player_name} {player_suffix}'
    - ''
    - '&cClick to open our website.'
    Open_Url: https://google.com
  minecraft-player-nick:
    Message: '{player_nick} '
    Sender_Condition: '{sender_is_player} == true'
    Hover:
    - '&7First Join: &f{player_first_join_date}'
    - ''
    - '&c&nClick to DM'
    Suggest_Command: '/tell {player_name} '

#All parts starting with "discord-" will only be shown when a player sends a messages from discord.
  discord-prefix:
    Message: '&7[&cDiscord] '
    Sender_Condition: '{sender_is_player} == false'
  discord-player-name:
    Message: '{player} '
    Sender_Condition: '{sender_is_player} == false'

  global-message:
    Message: '&8&l» &r{message}'
    Hover:
    - '&7Date: &b{timestamp}'
```

**Comment by donvdp** [comment]
Hey cool example. thanks for this, I have tried to figure out a way to set this up and went to the ChatControlRed wiki page:
- https://github.com/kangarko/ChatControl-Red/wiki/formats
- https://github.com/kangarko/ChatControl-Red/wiki/Variables

There i saw a variable called "{sender_is_discord}" and attempted to use this in my chat formatting. Here is what i came up with.

my admin-chat.yml file:

```
# The parts of this format.
Parts:
  
  # See the chat.yml format file for a tutorial on how this works.
  
  Prefix-StaffChat:
    Message: '&4[Staff Chat] '

  #discord prefix of anders de server waarop het is verstuurd
  Discord-prefix:
    Message: '[discord] '
    Sender_Condition: '{sender_is_discord} == true'

  Server-prefix:
    Message: '&3{server_name} '
    Sender_Condition: '{sender_is_player} == true'

  SpelerNaam:
    Message: '&c{player_name}'

  message:
    Message: '&b: {message}'
```

basicly what im trying to make is an 
"if -senderdiscord- then 
   -use discord prefix- 
else 
   -use server prefix- 
endif" 
statement.


I dont think the "Sender_Condition" part is working properly, because ingame i get an message containing both the discord prefix AND the server prefix. 
![image](https://user-images.githubusercontent.com/10013800/129476378-ea2987ac-216a-4dea-8656-300c8d25f659.png)
