### ISSUE TITLE
1.17.1: DiscordSRV not working

### ISSUE THREAD

**Issue by Skizzles** [kangarko/ChatControl#1242]
Hello,

I am trying to get the Local channel I have setup for ChatControl to go through DiscordSRV. Currently it only works if I have Global set as first.
https://screenshots.skizzles.me/wAnA3/bAraritO32.png

I have tried setting it to Local but then the messages from discord do not get sent to MC. I have this setup here as I don't want ChatControl handling formatting etc and would rather use DiscordSRV.

```
  # Integration with DiscordSRV. 
  Discord:
    
    # Enable all integration with DiscordSRV?
    Enabled: false
    
    # Should we apply anti-spam, anti-caps, rules and other filtering features?
    # Only works if Send_Messages_As_Bot is enabled, see below.
    Filter_Chat: false
    
    # Should we remove smileys from incoming messages from Discord? Recommended as the Minecraft
    # client cannot show many characters so they can show as [] or even kick players.
    Remove_Emojis: false
    
    # Beta: Send player channel messages through the webhook feature of Discord? 
    Webhook: false
    
    # Discord does not let us edit messages, so we must remove the original message and resend
    # it as the bot. You will see your message disappear and reappear in a second or less. 
    # true = messages are sent as bot (username icons not visible)
    # false = we do not edit your discord messages (warning: this breaks antispam, rules and 
    #         removing messages on discord)
    Send_Messages_As_Bot: false
  
    # What chat channels should we map when sending/receiving a message to/from Discord?
    # Write <channel id>: <channel name> (the channel name must equal your ChatControl channel
    #                                     name, but not necessarily the one on Discord)
    Connected_Channels:
      779616144599547904: Local
```

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true
