### ISSUE TITLE
PaperSpigot 1.17.1: Marriage Reloaded Compatibility

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#1243]
The plugin Marriage Reloaded uses chat symbols that appear after a name. It uses variables similar to ChatControl. Snip-it from Marriage Reloaded config:

```yaml
# Chat, set the format of private messages and in-chat status.
# Supported tags for chat: {partner}, for pm: {name}, {message}, chat spy: {sender}, {receiver}, {message}
# Icons are always available: {icon:heart}, {icon:male}, {icon:female}, {icon:genderless}
# If you use a custom chat plugin, put {marriage_status} in the format and set force-status-format & force-gender-format to false
# To show genders in chat, put {marriage_gender} in chat plugin format
chat:
  pm-format: '&4{icon:heart}&c{name}&4{icon:heart} &7{message}'
  status-format: '&4&l<3 &r'
  unmarried-status-format: ''
  spy-format: '&c[CHAT SPY] &7{sender} -> {receiver}&f: {message}'
  force-status-format: false
  force-gender-format: false
  male-prefix: '&b{icon:male} &r'
  female-prefix: '&d{icon:female} &r'
  genderless-prefix: ''
```

My "Part" in chat.yml:
```yaml
  marry:
    Message: '{marriage_gender}{marriage_status}'
```

But in chat, rather then showing the symbols provided by Marriage Reloaded, it simply shows the varibles and appears as 
"Horus {marriage_gender}{marriage_status}" like it's an unregistered placeholder. I have used this previously with several other chat plugins, any way I can make this work here? {marriage_gender} is supposed to show a Male or Female gender symbol, and the {marriage_status} would show a pink heart if that player is married. 

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false
