### ISSUE TITLE
1.17.1: JSON (Hover messages) in Timed.rs

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#1252]
I am really trying to understand timed messages and how to work them in with JSON. I've spent several hours through the wiki, and can get the message to appear with a hover event but it has issues:

No prefix, and when I try to add it manually, it just breaks and errors out in console. 
I cannot find a way to inter-work the JSON so only a select part of the message is hoverable.

What I'm trying to make appear in timed messages:

<prefix> Please see /buy to purchase ranks!

Where only the /buy is clickable/hoverable, rather then the entire message. I've looked quite a lot through formats and the messages section of the wiki. Perhaps a simple answer, but I can't seem to find a way to do this.

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
Hey!
Here are 2 working examples that you can use/edit to help you.


- The first one is a JSON formatted messsage which needs to be pastes in the timed.rs file:
```rs
group whatever-name-your-want
delay 600 seconds
prefix [JSON]
message: 
- ["",{"text":"Please see ","color":"yellow"},{"text":"/buy ","color":"#FF0000","clickEvent":{"action":"run_command","value":"/buy"},"hoverEvent":{"action":"show_text","contents":[{"text":"Click here to run the ","color":"gold"},{"text":"/buy ","bold":true,"color":"light_purple"},{"text":"command!","color":"gold"}]}},{"text":"to purchase ranks!","color":"yellow"}]
```


- This is what you need to do if you'd rather use a format file instead.
First of all, create a format file (in the `format/` folder), named however you want. In my case, I'll name it `buy-ad`.
```yaml
Parts:
  Part1:
    Message:
    - ''
    - '&ePlease see '
  Part2:
    Message:
    - '&c&l/buy '
    Hover:
    - '&cClick here to run the &e/buy &ccommand!'
    Run_Command: /buy
  Part3:
    Message:
    - '&eto purchase ranks!'
    - '&f'
```

Then put the 2nd part in the timed.rs file:

```rs
group whatever-name-your-want
delay 10 seconds
message: 
- buy-ad
```
