### ISSUE TITLE
1.16.5: Chat color problem "player 'xxx' is not stored in our database."

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl#1283]
This may have some relation to the mysql / usermap.csv issue we had not that long ago where storing nicknames were a problem although I'm not sure of that.  In this set up I am NOT using mysql.  However, even if the player in question has no nickname and has not yet chosen a color, bringin up the color gui should still allow them to set their chat color even if a value in the "database" has not yet been established, so the error makes no sense:

/chc color menu
(when entered by a player)

Results in 
"Player 'PlayerName' is not stored in our database."

However, as an OP, I have no problem running this command and using the color menu.  

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

All players with color permissions have the following permissions nodes, if something is missing for either the setting/resetting of colors or using the menu, please let me know:

```
name: g-chatcolor
permissions:
- chatcontrol.color.aqua
- chatcontrol.color.black:
    value: false
- chatcontrol.color.blue
- chatcontrol.color.bold:
    value: false
- chatcontrol.color.dark_aqua
- chatcontrol.color.dark_gray:
    value: false
- chatcontrol.color.dark_green
- chatcontrol.color.dark_purple:
    value: false
- chatcontrol.color.dark_red:
    value: false
- chatcontrol.color.gold
- chatcontrol.color.gray
- chatcontrol.color.green
- chatcontrol.color.italic:
    value: false
- chatcontrol.color.light_purple
- chatcontrol.color.magic:
    value: false
- chatcontrol.color.pink
- chatcontrol.color.red
- chatcontrol.color.reset
- chatcontrol.color.strikethrough:
    value: false
- chatcontrol.color.underline:
    value: false
- chatcontrol.color.white
- chatcontrol.color.yellow
- chatcontrol.command.color
- chatcontrol.guicolor
- chatcontrol.guicolor.aqua
- chatcontrol.guicolor.blue
- chatcontrol.guicolor.dark_aqua
- chatcontrol.guicolor.dark_green
- chatcontrol.guicolor.gold
- chatcontrol.guicolor.gray
- chatcontrol.guicolor.green
- chatcontrol.guicolor.light_purple
- chatcontrol.guicolor.pink
- chatcontrol.guicolor.red
- chatcontrol.guicolor.reset
- chatcontrol.guicolor.white
- chatcontrol.guicolor.yellow
- chatcontrol.use.color.chat
- chatcontrol.use.color.nick
- chatcontrol.use.color.prefix
- chatcontrol.use.color.private_message
- cmi.colors
- cmi.colors.signs
- cmi.colors.signs.aqua
- cmi.colors.signs.black
- cmi.colors.signs.blue
- cmi.colors.signs.bold
- cmi.colors.signs.dark_aqua
- cmi.colors.signs.dark_gray
- cmi.colors.signs.dark_green
- cmi.colors.signs.dark_purple
- cmi.colors.signs.dark_red
- cmi.colors.signs.gold
- cmi.colors.signs.gray
- cmi.colors.signs.green
- cmi.colors.signs.italic
- cmi.colors.signs.light_purple
- cmi.colors.signs.pink
- cmi.colors.signs.red
- cmi.colors.signs.reset
- cmi.colors.signs.rgb
- cmi.colors.signs.strikethrough
- cmi.colors.signs.underline
- cmi.colors.signs.white
- cmi.colors.signs.yellow
- essentials.chat.color
- essentials.editsign.aqua
- essentials.editsign.black
- essentials.editsign.blue
- essentials.editsign.bold
- essentials.editsign.color
- essentials.editsign.dark_aqua
- essentials.editsign.dark_gray
- essentials.editsign.dark_green
- essentials.editsign.dark_purple
- essentials.editsign.dark_red
- essentials.editsign.gold
- essentials.editsign.gray
- essentials.editsign.green
- essentials.editsign.italic
- essentials.editsign.light_purple
- essentials.editsign.pink
- essentials.editsign.red
- essentials.editsign.reset
- essentials.editsign.strikethrough
- essentials.editsign.underline
- essentials.editsign.white
- essentials.editsign.yellow
- essentials.kits.color
- essentials.msg.color
- essentials.nick
- essentials.nick.color
- essentials.signs.aqua
- essentials.signs.black
- essentials.signs.blue
- essentials.signs.bold
- essentials.signs.color
- essentials.signs.dark_aqua
- essentials.signs.dark_blue
- essentials.signs.dark_gray
- essentials.signs.dark_green
- essentials.signs.dark_purple
- essentials.signs.dark_red
- essentials.signs.format
- essentials.signs.gold
- essentials.signs.gray
- essentials.signs.green
- essentials.signs.italic
- essentials.signs.light_purple
- essentials.signs.magic
- essentials.signs.pink
- essentials.signs.red
- essentials.signs.reset
- essentials.signs.rgb
- essentials.signs.strikethrough
- essentials.signs.underline
- essentials.signs.white
- essentials.signs.yellow

```
