### ISSUE TITLE
1.17.1: Bungeecord join/quit/switch message formats

### ISSUE THREAD

**Issue by n-aspen** [kangarko/ChatControl#1308]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

I can't figure out if it's possible to use the formatting system that's available on Spigot servers for the Bungee join/quit/switch messages. Specifically I want to be able to use this format
```
Parts:
  JoinMarker:
    Message: '&6[&a&l+&6]&r '
    Hover:
    - '&7Click welcome &6{player_name}&7 back to the server!'
    Suggest_Command: Welcome back {player_name}!
  Message:
    Message: '&e{player_nick}&e has joined the game!'
```
on the bungee join messages, but the `.rs` files don't seem to take format files the same way it's done on Spigot and they don't use the Spigot formats either.
