### ISSUE TITLE
1.17.1: Announcement chat line is not centered with <center>

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl#1310]
ChatControl Red v10.6.3
Paper 1.17.1 dev 257
ProtocolLib dev 531

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: false

Using the announce command, I noticed that the header line did not seem to be perfectly centered despite <center> being used. I think I recall it use to be fine, but I do not remember when it broke, sorry! Specifically the ``! ANNOUNCE !`` message.

Command used from console.
``/chc announce chat Quick server update, ETA ~3 minutes. You'll reconnect automatically.``

![link](https://i.imgur.com/HexTVdn.png)

messages_en.yml
```
  Announce:
    Usage: <type> <message>
    Description: Announce various messages.
    Usage_Chat: /{label} {sublabel} chat <message> [server:<server>] [type:raw] &7- Broadcast a chat message.
    Usage_Title: /{label} {sublabel} title <title|subtitle> fadein:<ticks> stay:<ticks> fadeout:<ticks> &7- Send a title. If you only want to send subtitle, use '/{label} {sublabel} title |your message here'.
    Usage_Actionbar: /{label} {sublabel} actionbar <message> server:creative &7- Send actionbar message to 'creative' server.
    Usage_Bossbar: /{label} {sublabel} bossbar <message> time:<seconds> color:<color> style:<style> &7- Send boss bar to this server.
    Usage_Toast: /{label} {sublabel} toast <message> icon:<material> &7- Send a toast message.
    Usage_Image: /{label} {sublabel} image <path> <linesHeight> [message|anotherMessage]
    Usage_Footer: ''
    No_Type: Please specify a message to broadcast.
    Empty: Your message cannot be empty!
    Image_Lines: Please enter a valid number representing how many chat lines the image will strech over.
    Invalid_Image: Unable to find image at '{0}'
    Invalid_Type: 'Does not know how to send: ''{0}''.'
    Invalid_Raw_Type: Invalid type! Only 'raw' is supported at the moment.
    Invalid_Time_Ticks: Please enter a valid integer representing a time in ticks.
    Invalid_Time_Seconds: Please enter a valid integer representing time in seconds.
    Invalid_Key: 'Invalid key ''{0}'' value: {1}. Available: {2}'
    Invalid_File: 'No such file: {0}'
    Image_Error: 'Failed to broadcast image from ''{0}'': {1}. Please see console for more information.'
    Invalid_Image_Height: Image height must be between {0} and {1}.
    Chat_Body:
    - '&8{chat_line}'
    - '<center>&f&l! &b&l{type} &f&l!'
    - '&8{chat_line}'
    - '&f{lines}'
    - '{remaining_space}'
    - '&8{chat_line}'
    Chat_Body_Line_Color: WHITE
    Type: ANNOUNCEMENT
    Success: Your announcement has been sent.
    Success_Network: Your announcement was sent to the {0} server.
```
