### ISSUE TITLE
1.17.1: Chat messages are not being shown in discord server channels unless the user has * perms

### ISSUE THREAD

**Issue by SecretarySami** [kangarko/ChatControl#1315]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

Chat messages are not being shown in discord server channels unless the user has * perms. They are also not going through to in game chat from discord anymore. https://www.youtube.com/watch?v=Wn8aKTxd0Vg

**Comment by ElBananaa** [comment]
Hey,
Sorry for the delay,
Could you please provide us your `/chc debug` log from the server in the video?

**Comment by MasonX3** [comment]
I'm having the same issue on a single server without MySQL and without BungeeCord; however, even with the * permission assigned to a user, the message is not sent.

Here's my debug:
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7171913/debug.zip)

**Comment by ElBananaa** [comment]
> I'm having the same issue on a single server without MySQL and without BungeeCord; however, even with the * permission assigned to a user, the message is not sent.
> 
> Here's my debug:
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/7171913/debug.zip)

Thanks!
So, first of all, you can remove NashornPlus, it's not needed anymore with the latest version of the plugin under mc 1.16+ & Java 15+.

In a previous update of the plugin (v10.5.6 : https://www.mc-market.org/resources/18217/update?update=74195), the DiscordSRV integration has been rewritten, which is, I guess, the cause of your issue since it changed a few options.
i'd suggest taking a look at our wiki page to update your settings file correctly : https://github.com/kangarko/chatcontrol-red/wiki/Discord

If you're having troubles updating your file, please provide us your `settings.yml` file (Don't forget to remove any sensitive information such as the database credentials), and I'd be more than happy to help fixing both your issues. 😃

**Comment by MasonX3** [comment]
> > I'm having the same issue on a single server without MySQL and without BungeeCord; however, even with the * permission assigned to a user, the message is not sent.
> > Here's my debug:
> > [debug.zip](https://github.com/kangarko/ChatControl-Red/files/7171913/debug.zip)
> 
> Thanks!
> So, first of all, you can remove NashornPlus, it's not needed anymore with the latest version of the plugin under mc 1.16+ & Java 15+.
> 
> In a previous update of the plugin (v10.5.6 : https://www.mc-market.org/resources/18217/update?update=74195), the DiscordSRV integration has been rewritten, which is, I guess, the cause of your issue since it changed a few options.
> i'd suggest taking a look at our wiki page to update your settings file correctly : https://github.com/kangarko/chatcontrol-red/wiki/Discord
> 
> If you're having troubles updating your file, please provide us your `settings.yml` file (Don't forget to remove any sensitive information such as the database credentials), and I'd be more than happy to help fixing both your issues. 😃

Okay, so I've gotten it back now to where I can send and receive formats; however, ChatControlRed is overriding the formats that I had set in DiscordSRV. Is there a way for me to differentiate the formats in ChatControl or is there a way for me to revert back to my DiscordSRV formats that worked fine before the update?

**Comment by ElBananaa** [comment]
I believe the only way to format your messages using DiscordSRV is to completely disable our implementation, and let DiscordSRV handle this.
However, I'm not sure about it, so I'd suggest waiting for Kangarko to have a look at this issue (which shouldn't take more than a few days hopefully). In the meantime, I'll try to run some tests on my end tonight just to be sure.

Anyways, I'll keep you updated here ^^

**Comment by MasonX3** [comment]
> I believe the only way to format your messages using DiscordSRV is to completely disable our implementation, and let DiscordSRV handle this.
> However, I'm not sure about it, so I'd suggest waiting for Kangarko to have a look at this issue (which shouldn't take more than a few days hopefully). In the meantime, I'll try to run some tests on my end tonight just to be sure.
> 
> Anyways, I'll keep you updated here ^^

I was able to successfully format the in-game messages with ChatControl; however, I can't seem to find where I can format the Discord to Minecraft messages.

**Comment by ElBananaa** [comment]
> > I believe the only way to format your messages using DiscordSRV is to completely disable our implementation, and let DiscordSRV handle this.
> > However, I'm not sure about it, so I'd suggest waiting for Kangarko to have a look at this issue (which shouldn't take more than a few days hopefully). In the meantime, I'll try to run some tests on my end tonight just to be sure.
> > Anyways, I'll keep you updated here ^^
> 
> I was able to successfully format the in-game messages with ChatControl; however, I can't seem to find where I can format the Discord to Minecraft messages.

Well, you have multiple ways of editing the discord to minecraft messages format : 

- First way : In the settings file, near the top, there is : `Format_Discord: "{player}: {message}"`. You can edit this part and the format used will be the same for all the channels (if you have multiple channels using the discord chat relay.

- Second way : Using the `Format_Discord` option, and editing the format in the settings file. This way you can have a different format for each channel. Here's an example:
```yaml
  List: 
    standard: 
      Format: chat
      Format_Spy: "@noprefix chat"
      Format_Discord: "[Discord-standard] {player} {message}"
    admin: 
      Format: admin-chat
      Format_Console: '[A-chat {player}] {message}'
      Format_Discord: "[Discord-admin] {player} {message}"
```

- Third way : Using the `Format_Discord` option, but specifying a format file instead of editing the format in the settings file:
```yaml
  List: 
    standard: 
      Format: chat
      Format_Spy: "@noprefix chat"
      Format_Discord: standard-discord
    admin: 
      Format: admin-chat
      Format_Console: '[A-chat {player}] {message}'
      Format_Discord: admin-discord
```

Of course you can mix the 2 last ways, so it can look like : 
```yaml
  List: 
    standard: 
      Format: chat
      Format_Spy: "@noprefix chat"
      Format_Discord: "[Discord-standard] {player} {message}"
    admin: 
      Format: admin-chat
      Format_Console: '[A-chat {player}] {message}'
      Format_Discord: admin-discord
```

**Comment by MasonX3** [comment]
> > > I believe the only way to format your messages using DiscordSRV is to completely disable our implementation, and let DiscordSRV handle this.
> > > However, I'm not sure about it, so I'd suggest waiting for Kangarko to have a look at this issue (which shouldn't take more than a few days hopefully). In the meantime, I'll try to run some tests on my end tonight just to be sure.
> > > Anyways, I'll keep you updated here ^^
> > 
> > 
> > I was able to successfully format the in-game messages with ChatControl; however, I can't seem to find where I can format the Discord to Minecraft messages.
> 
> Well, you have multiple ways of editing the discord to minecraft messages format :
> 
> * First way : In the settings file, near the top, there is : `Format_Discord: "{player}: {message}"`. You can edit this part and the format used will be the same for all the channels (if you have multiple channels using the discord chat relay.
> * Second way : Using the `Format_Discord` option, and editing the format in the settings file. This way you can have a different format for each channel. Here's an example:
> 
> ```yaml
>   List: 
>     standard: 
>       Format: chat
>       Format_Spy: "@noprefix chat"
>       Format_Discord: "[Discord-standard] {player} {message}"
>     admin: 
>       Format: admin-chat
>       Format_Console: '[A-chat {player}] {message}'
>       Format_Discord: "[Discord-admin] {player} {message}"
> ```
> 
> * Third way : Using the `Format_Discord` option, but specifying a format file instead of editing the format in the settings file:
> 
> ```yaml
>   List: 
>     standard: 
>       Format: chat
>       Format_Spy: "@noprefix chat"
>       Format_Discord: standard-discord
>     admin: 
>       Format: admin-chat
>       Format_Console: '[A-chat {player}] {message}'
>       Format_Discord: admin-discord
> ```
> 
> Of course you can mix the 2 last ways, so it can look like :
> 
> ```yaml
>   List: 
>     standard: 
>       Format: chat
>       Format_Spy: "@noprefix chat"
>       Format_Discord: "[Discord-standard] {player} {message}"
>     admin: 
>       Format: admin-chat
>       Format_Console: '[A-chat {player}] {message}'
>       Format_Discord: admin-discord
> ```

Okay... so I think I need to rephrase what I'm looking for here. I don't need to format how the bot sends the message to Discord. 
I attempted to change the format in the way you said in Method 2 and it changed my Minecraft to Discord messages. I had already used Method 1 previously, so it really just kinda screwed my previous format over.

I.e. this is my current format for Discord using Method 1, which I had already had:
`{player_prefix}{player}{player_suffix}: {message}`

So if I type in chat with the prefix `Owner |` and suffix ` $`, it shows up in Discord as:
`Owner | MasonX3 $: test`

However, when I write a message on my Discord account, let's say I say "test2" in the discord channel, the message in the in-game chat is:
`MasonX3: test2` in all white text.

I'm wanting to be able to change that format because it looks really ugly in-game with all white text. Are you following?

**Comment by ElBananaa** [comment]
Oh yeah, right, I misunderstood you, my bad 😅
The discord to minecraft format is the format used ingame for the channel. So you need to edit this file.
You can play with our `Sender_Condition` feature combined with the `{sender_is_discord}` placeholder to show/hide some parts of the format if the sender is an ingame player or a discord user.
There's an example in the default file, which will basically only show the `[Discord]` prefix if the message is sent from discord:
```yaml
  discord-prefix: 
    Message: "&8[&9Discord&8] &f"
    Sender_Condition: "{sender_is_discord}"
    Hover: "&bJoin our Discord at mineacademy.org/discord"
    Open_Url: "https://mineacademy.org/discord"
```

**Comment by MasonX3** [comment]
> Oh yeah, right, I misunderstood you, my bad 😅
> The discord to minecraft format is the format used ingame for the channel. So you need to edit this file.
> You can play with our `Sender_Condition` feature combined with the `{sender_is_discord}` placeholder to show/hide some parts of the format if the sender is an ingame player or a discord user.
> There's an example in the default file, which will basically only show the `[Discord]` prefix if the message is sent from discord:
> 
> ```yaml
>   discord-prefix: 
>     Message: "&8[&9Discord&8] &f"
>     Sender_Condition: "{sender_is_discord}"
>     Hover: "&bJoin our Discord at mineacademy.org/discord"
>     Open_Url: "https://mineacademy.org/discord"
> ```

Okay so I've gotten that into `global-chat.yml`, but I'm guessing there's not really a good way for me to format the entire message as opposed to just adding the Discord prefix?

**Comment by ElBananaa** [comment]
> > Oh yeah, right, I misunderstood you, my bad 😅
> > The discord to minecraft format is the format used ingame for the channel. So you need to edit this file.
> > You can play with our `Sender_Condition` feature combined with the `{sender_is_discord}` placeholder to show/hide some parts of the format if the sender is an ingame player or a discord user.
> > There's an example in the default file, which will basically only show the `[Discord]` prefix if the message is sent from discord:
> > ```yaml
> >   discord-prefix: 
> >     Message: "&8[&9Discord&8] &f"
> >     Sender_Condition: "{sender_is_discord}"
> >     Hover: "&bJoin our Discord at mineacademy.org/discord"
> >     Open_Url: "https://mineacademy.org/discord"
> > ```
> 
> Okay so I've gotten that into `global-chat.yml`, but I'm guessing there's not really a good way for me to format the entire message as opposed to just adding the Discord prefix?

You can format the entire message.
Simply use `Sender_Condition: "{sender_is_discord}"` for each part of the message sent from discord, and use `Sender_Condition: "{sender_is_player}"` for each part of the message sent from the game. If it isn't clear enough, just send me your format file, and i'll try to format something for you as a better example ^^

**Comment by MasonX3** [comment]
> > > Oh yeah, right, I misunderstood you, my bad 😅
> > > The discord to minecraft format is the format used ingame for the channel. So you need to edit this file.
> > > You can play with our `Sender_Condition` feature combined with the `{sender_is_discord}` placeholder to show/hide some parts of the format if the sender is an ingame player or a discord user.
> > > There's an example in the default file, which will basically only show the `[Discord]` prefix if the message is sent from discord:
> > > ```yaml
> > >   discord-prefix: 
> > >     Message: "&8[&9Discord&8] &f"
> > >     Sender_Condition: "{sender_is_discord}"
> > >     Hover: "&bJoin our Discord at mineacademy.org/discord"
> > >     Open_Url: "https://mineacademy.org/discord"
> > > ```
> > 
> > 
> > Okay so I've gotten that into `global-chat.yml`, but I'm guessing there's not really a good way for me to format the entire message as opposed to just adding the Discord prefix?
> 
> You can format the entire message.
> Simply use `Sender_Condition: "{sender_is_discord}"` for each part of the message sent from discord, and use `Sender_Condition: "{sender_is_player}"` for each part of the message sent from the game. If it isn't clear enough, just send me your format file, and i'll try to format something for you as a better example ^^

Yeah, I'll be honest this is throwing me for a complete loop. Not very happy about having to change a configuration that worked beforehand. What I'm trying to do is format my Minecraft to Discord chat to be something like 
`[D] <Role> | <Username>: <Message>`
I'd like to be able to have all those parts configurable, but I need to see what that looks like. 
[global-chat.zip](https://github.com/kangarko/ChatControl-Red/files/7173602/global-chat.zip)

**Comment by ElBananaa** [comment]
> > > > Oh yeah, right, I misunderstood you, my bad 😅
> > > > The discord to minecraft format is the format used ingame for the channel. So you need to edit this file.
> > > > You can play with our `Sender_Condition` feature combined with the `{sender_is_discord}` placeholder to show/hide some parts of the format if the sender is an ingame player or a discord user.
> > > > There's an example in the default file, which will basically only show the `[Discord]` prefix if the message is sent from discord:
> > > > ```yaml
> > > >   discord-prefix: 
> > > >     Message: "&8[&9Discord&8] &f"
> > > >     Sender_Condition: "{sender_is_discord}"
> > > >     Hover: "&bJoin our Discord at mineacademy.org/discord"
> > > >     Open_Url: "https://mineacademy.org/discord"
> > > > ```
> > > 
> > > 
> > > Okay so I've gotten that into `global-chat.yml`, but I'm guessing there's not really a good way for me to format the entire message as opposed to just adding the Discord prefix?
> > 
> > 
> > You can format the entire message.
> > Simply use `Sender_Condition: "{sender_is_discord}"` for each part of the message sent from discord, and use `Sender_Condition: "{sender_is_player}"` for each part of the message sent from the game. If it isn't clear enough, just send me your format file, and i'll try to format something for you as a better example ^^
> 
> Yeah, I'll be honest this is throwing me for a complete loop. Not very happy about having to change a configuration that worked beforehand. What I'm trying to do is format my Minecraft to Discord chat to be something like
> `[D] <Role> | <Username>: <Message>`
> I'd like to be able to have all those parts configurable, but I need to see what that looks like.
> [global-chat.zip](https://github.com/kangarko/ChatControl-Red/files/7173602/global-chat.zip)

Thanks!
Alright, Right now there's no way to get a user's ingame rank (I believe DiscordSRV doesn't offer any placeholder for that) for messages sent from discord. So basically, the format will be : `[D] <Username>: <Message>`
Anyways, this is something that should do the trick:

```yaml
# -----------------------------------------------------------------------------------------
# The default chat format used in the global channel.
# -----------------------------------------------------------------------------------------

# The parts of this format.
Parts:
  spies-prefix:
    Message: '&8[&5Spy&8] &f'
    Receiver_Condition: '{player_is_spying_{channel}}'
    Hover: '&dClick to stop spying {channel} channel.'
    Run_Command: /{label_spy} toggle chat {channel}

# This part will only be sent if the sender of the message is an ingame player
  ingame-prefix:
    Message: '{player_prefix}'
    Sender_Condition: '{sender_is_player}'
    Hover:
    - '&7╔════&a&lPlayer Info&7════╗'
    - '&a&lName&8: &b%player_name%'
    - '&b&lRank&8: {vault_prefix_color}{player_primary_group}'
    - '&a&lBalance&8: &a&lⓍ&f %vault_eco_balance_commas%'
    - '&6&lMcMMO Power&8: &a%mcmmo_power_level%'
    - '&e&lVotes&8: &e{voteparty_player_votes}'
    - '&7╚═══════════════╝'
    Open_Url: https://xcsurvival.com

# This part will only be sent if the sender of the message is a discord user
  discord-prefix:
    Message: '&8[#5865F2&lD&8] #5865F2'
    Sender_Condition: '{sender_is_discord}'
    Hover: '#5865F2Join our Discord!'
    Open_Url: https://discord.gg/xcraftsurvival

# These parts will be sent no matter if the sender is a discord user or an ingame player because no matter the origin of the message, you want to see their name and their messages
  general-player-name:
    Message: '{player_nick}'
    Hover: '&7Click to message.'
    Suggest_Command: '/tell {player_name} '
  general-message:
    Message: '{player_suffix}&8:&r {message}'
```

**Comment by MasonX3** [comment]
So... I've tried this. I've been able to successfully get the Discord messages separate by adding

```
  discord-message:
   Message: '&8:&#5865F2 {message}'
   Sender_Condition: '{sender_is_discord}'
```

The only thing left is that no matter what, the Discord username is white. How can I change their Discord username's color in-game?

**Comment by ElBananaa** [comment]
> So... I've tried this. I've been able to successfully get the Discord messages separate by adding
> 
> ```
>   discord-message:
>    Message: '&8:&#5865F2 {message}'
>    Sender_Condition: '{sender_is_discord}'
> ```
> 
> The only thing left is that no matter what, the Discord username is white. How can I change their Discord username's color in-game?

Well, simply add a color in front of the name part in your format file. Here's how it would look like if you want to have a different name color if the sender is a discord user or a player:
```yaml
# -----------------------------------------------------------------------------------------
# The default chat format used in the global channel.
# -----------------------------------------------------------------------------------------

# The parts of this format.
Parts:
  spies-prefix:
    Message: '&8[&5Spy&8] &f'
    Receiver_Condition: '{player_is_spying_{channel}}'
    Hover: '&dClick to stop spying {channel} channel.'
    Run_Command: /{label_spy} toggle chat {channel}

# This part will only be sent if the sender of the message is an ingame player
  ingame-prefix:
    Message: '{player_prefix}'
    Sender_Condition: '{sender_is_player}'
    Hover:
    - '&7╔════&a&lPlayer Info&7════╗'
    - '&a&lName&8: &b%player_name%'
    - '&b&lRank&8: {vault_prefix_color}{player_primary_group}'
    - '&a&lBalance&8: &a&lⓍ&f %vault_eco_balance_commas%'
    - '&6&lMcMMO Power&8: &a%mcmmo_power_level%'
    - '&e&lVotes&8: &e{voteparty_player_votes}'
    - '&7╚═══════════════╝'
    Open_Url: https://xcsurvival.com

# This part will only be sent if the sender of the message is a discord user
  discord-prefix:
    Message: '&8[#5865F2&lD&8] #5865F2'
    Sender_Condition: '{sender_is_discord}'
    Hover: '#5865F2Join our Discord!'
    Open_Url: https://discord.gg/xcraftsurvival

  ingame-player-name:
    Message: '{player_nick}'
    Sender_Condition: '{sender_is_player}'
    Hover: '&7Click to message.'
    Suggest_Command: '/tell {player_name} '

  discord-player-name:
    Message: '#5865F2{player_nick}'
    Sender_Condition: '{sender_is_discord}'

# These parts will be sent no matter if the sender is a discord user or an ingame player because no matter the origin of the message, you want to see their name and their messages
  general-message:
    Message: '{player_suffix}&8:&r {message}'
```
