### ISSUE TITLE
Minecraft Version: I am trying to block plugin commands which is in the tab of /bukkit:? [TAB]

### ISSUE THREAD

**Issue by MohammedPro1** [kangarko/ChatControl#1349]
Minecraft Version: 1.8.9
MySQL: false
BungeeCord: false

I am trying to block the tab list of /bukkit:? [TAB] and I couldn't using this plugin,
could you please tell me the correct way of doing it?

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.8.9 MySQL: false BungeeCord: false
> 
> I am trying to block the tab list of /bukkit:? [TAB] and I couldn't using this plugin, could you please tell me the correct way of doing it?

Hey!
Turning the blacklist into a whitelist solved the issue on my side!
To do so, you only need to remove `'@blacklist'` at the top of the list.
This is how it looks like with the default file, which basically means all the commands listed under the `@blacklist` part are blocked : 
```yaml
Tab_Complete:
  
  # Enable this feature?
  Enabled: false
  
  # Prevent completions for words shorter that the given amount of letters.
  # **On Minecraft older than 1.13 this only works properly on the first command argument.**
  Prevent_If_Below_Length: 0
  
  # What commands should we prevent from being tab-completed? Uses regular expressions.
  # [TIP] This is turned into blacklist by default, see header of this configuration.
  Whitelist:
  - '@blacklist'
  - '(/ver|/version)\b'
  - '(/pl|/plugins)\b'
  - '/hiddenCommand'
```
Removing the `@blacklist` part as I did in the part below simply turns the list to a whitelist. It basically means that only commands listed there can be tab-completed:
```yaml
Tab_Complete:
  
  # Enable this feature?
  Enabled: false
  
  # Prevent completions for words shorter that the given amount of letters.
  # **On Minecraft older than 1.13 this only works properly on the first command argument.**
  Prevent_If_Below_Length: 0
  
  # What commands should we prevent from being tab-completed? Uses regular expressions.
  # [TIP] This is turned into blacklist by default, see header of this configuration.
  Whitelist:
  - '(/ver|/version)\b'
  - '(/pl|/plugins)\b'
  - '/hiddenCommand'
```

This is how it now looks ingame
![image](https://user-images.githubusercontent.com/53318613/135679249-db910086-7f55-4bef-918a-c75082076adb.png)
