### ISSUE TITLE
[How can I make a clickable message]

### ISSUE THREAD

**Issue by Arthuuurr** [kangarko/ChatControl#1357]
Hello, how could I make an automatic message when I click take me to a link?
Image= https://cdn.discordapp.com/attachments/873262504069971998/887784450493120563/unknown.png

**Comment by ElBananaa** [comment]
Hey,
There should be an example in the default file on the latest version, in the `messages/timed.rs` file : 
```rs
# You can also send raw JSON messages using this example here:
#group json-sample
#delay 600 seconds
#prefix [JSON]
#message: 
#- ["",{"text":"Please see ","color":"yellow"},{"text":"/buy ","color":"#FF0000","clickEvent":{"action":"run_command","value":"/buy"},"hoverEvent":{"action":"show_text","contents":[{"text":"Click here to run the ","color":"gold"},{"text":"/buy ","bold":true,"color":"light_purple"},{"text":"command!","color":"gold"}]}},{"text":"to purchase ranks!","color":"yellow"}]
```
So basically, here, we used json. You can find more informations about how does it works exactly by taking a look at our dedicated wiki page : https://github.com/kangarko/ChatControl-Red/wiki/JSON and you can create your own JSON messages using an online generator like this one : https://www.minecraftjson.com/

You can also create a format file (https://github.com/kangarko/ChatControl-Red/wiki/Formats) and simply use the format name in the message part.
So, as example, let's create a file named `shop-ad.yml` in the `formats/` folder, with this content:
```yaml
Parts:
  everything:
    Message:
    - ''
    - '&e&eYou would like to support the server?'
    - '&8➢ &c&l/SHOP'
    - '&f'
    Hover:
    - '&cClick to access our online shop.'
    Open_Url: https://shop.yourserver.com/
  part2:
    Message: '&f'
```
Once this is done, go in `messages/timed.rs` and add the following:
```rs
group shop-ad
delay 300 seconds
message:
- shop-ad
```
And that's it!

You can chose to either use JSON, or format files to do, and you can of course mix both (So you can use JSON for some messages, and format files for some others).
