### ISSUE TITLE
No support for color gradients in prefix/suffix ?

### ISSUE THREAD

**Issue by Help3rL** [kangarko/ChatControl#1392]
Hey i am not sure, but i cant find any information about color gradient settings (where is allowed or disallowed to use) and for me it doesn't work in prefix and suffix.
Permissions plugin: Luckperms
Chat formatting plugin: Chatcontrol red & CMI(for tab and couple other minimal things) 
Anyone would know the issue? Because prefix and suffix formatting with CMI with color gradients was no issue. But i still would like to keep using CControl as main chat formatting and control plugin so any way i can fix that?
Etc.:
Trying to do something like this {#475466}[{#514766>}Time{#2e3299<}{#2e3299>}less{#514766<}{#475466}]
![Screenshot_221](https://user-images.githubusercontent.com/68181784/137644361-a6ebe274-a1cf-4a37-89e5-2d59df1c8742.png)
Photo showing currently formatted prefix and chat it as it should be

**Comment by ElBananaa** [comment]
> Hey i am not sure, but i cant find any information about color gradient settings (where is allowed or disallowed to use) and for me it doesn't work in prefix and suffix. Permissions plugin: Luckperms Chat formatting plugin: Chatcontrol red & CMI(for tab and couple other minimal things) Anyone would know the issue? Because prefix and suffix formatting with CMI with color gradients was no issue. But i still would like to keep using CControl as main chat formatting and control plugin so any way i can fix that? Etc.: Trying to do something like this {#475466}[{#514766>}Time{#2e3299<}{#2e3299>}less{#514766<}{#475466}] ![Screenshot_221](https://user-images.githubusercontent.com/68181784/137644361-a6ebe274-a1cf-4a37-89e5-2d59df1c8742.png) Photo showing currently formatted prefix and chat it as it should be

Hey!
In order to use gradients with the plugin, you either need to configure your gradient in your format file (here's an example from the default chat.yml format):
```yaml
  # Gradient: <from> - <to> (such as RED - GOLD or #123456 - #123456) Gradients for MC 1.16+.
  # Display a typical player name to players with the given permission. change {player_name} 
  # to {player_nick} to show nick instead. We'll revert to show normal name if player has no nick.
  # To display a name in rainbow colors, uncomment "Gradient". This requires MC 1.16+
  player-name: 
    Message: "{player_nick}"
    #Message: "{player_name}"
    Gradient: RED - YELLOW
    Hover: "&7Click to message."
    Suggest_Command: "/tell {player_name} "
```
Or, you can use the PlaceholderAPI Gradient expansion: https://api.extendedclip.com/expansions/gradient/
