### ISSUE TITLE
1.17.1: /spy menu channel list shows duplicate channels

### ISSUE THREAD

**Issue by RetGoatCopper** [kangarko/ChatControl#1396]
When viewing list of channels in /spy menu, the channels are duplicated. But inside the menu it displays correctly (See below images).

```
List:
    Network:
      Format: network_chat
      Bungee: true
    Server:
      Format: server_chat
      Bungee: false
    Admin:
      Format: admin_chat
      Bungee: true
    Staff:
      Format: staff_chat
      Bungee: true
    Help:
      Format: help_chat
      Bungee: true
```

![image](https://user-images.githubusercontent.com/43792057/137930802-3bdb94e5-8815-4e8e-849c-c90a75ad6673.png)

![image](https://user-images.githubusercontent.com/43792057/137930843-a938615d-8143-4636-ac57-7fe51504f5ee.png)

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true
