### ISSUE TITLE
1.16.4 | So I try out to bug report discord problems 

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl#142]
So I think the plugin, is so ready it can be :) so I can start reporting other problems together with discord. If you think I was late (is because I wanted to wait until you got the plugin stable enough).

I think it was in version 10.0.8 that it worked pretty well with discord.
But the latter sends it out to discord even if it says in the console that not stop the msg.

You can not broadcast from dc (stopped working the latest versions and says it misses global again)
[ChatControlRed] No ChatControl channel for Discord channel global id

 

```
 List:
    mc-✆hjälp:
      Format: hjalp
      Format_Console: '[mc-hjälp {player}] {message}'
      Format_Spy: '@noprefix spy5'
      Format_Discord: none
    chat:
      Format: chat
      Format_Console: '[D-chat {player}] {message}'
      Format_Discord: none
    mc-admin:
      Format: admin-chat
      Format_Console: '[mc-admim {player}] {message}'
    mc-globalt:
      Format: global-chat
      Format_Console: '[mc-globalt {player}] {message}'
    mc-lokalt:
      Format: lokal_chat
      Range: 100
      Format_Discord: none
      Worlds:
      - 'Midgardsaga'
      - 'Midgardsaga_nether'
      Format_Console: '[lokal-chat {player}] {message}'
    towny:
      Format: chat
      Party: towny-town
    helpop:
      Format: helpop
```
Discord settings https://bin.scarsz.me/3d5ed2b4-645c-4be9-a5e2-ba95d6433e26#qCLx4qZwSlUMU6vBCINmAnrV5KO1hhaa
