### ISSUE TITLE
1.17.1: Is it possible to disable/hide the "no one in range for you to talk to" mesage

### ISSUE THREAD

**Issue by morgan2233** [kangarko/ChatControl#1451]
Is it possible to disable/hide the "no one in range for you to talk to" message?

Minecraft Version: 1.7.1
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> Is it possible to disable/hide the "no one in range for you to talk to" message?
> 
> Minecraft Version: 1.7.1 MySQL: true BungeeCord: true

Hey!
Yeah, go to your localization file `ChatControlRed/localization/` and look for `Channel_Range_Notification` part.
Remove it's content, and reload the plugin.

This is how it looks like with the default english file : 
```yaml
  Kick_Relogin: '&cPlease wait {0} second(s) before joining again!'
  Channel_Range_Notification: ''
  Already_Conversing: '{0} is already having an ongoing server conversation!'
```
