### ISSUE TITLE
Allow URLs only in PMs

### ISSUE THREAD

**Issue by DrkMatr1984** [kangarko/ChatControl#1481]
I want to allow sharing of URLs but only in private messages. Is there a way to do this?

Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

**Comment by TheIntolerant** [comment]
Using the ``ignore command`` operator you can allow URL's in PM's
Example, in my "settings.yml" I have this under "private_messages".
```yml
  Tell_Aliases:
  - 'tell'
  - 'w'
  - 'm'
  - 't'
  - 'pm'
  - 'message'
  - 'msg'
  - 'whisper'
  
  # The reply command aliases.
  # EDIT AS YOU WISH BUT DO NOT REMOVE THE FIRST ALIAS
  Reply_Aliases:
  - 'reply'
  - 'r'
  ```
So I would just add a line with the ``ignore command`` operator to the rule to allow URL's in PM's using the commands listed above.

In my case, it would be: ``ignore command /tell|/w|/m|/t|/pm|/message|/msg|/whisper|/reply|/r`` 
This can be added in either of the following:

---

1) In ``plugins/ChatControlRed/rules/groups.rs`` under the ad group which should be something like ``group advertisement``. In which it should look like this <https://pastebin.com/ieEVCR4B>

**OR**

2) In ``plugins/ChatControlRed/rules/global.rs`` under the rule for URL's which should have ``# Domain/URL filter.`` just before the "match" operator. In which it should look like this <https://pastebin.com/4B7d3ZU0>
