### ISSUE TITLE
1.17.1: Improper placement of JSON components in messages

### ISSUE THREAD

**Issue by BakiDance** [kangarko/ChatControl#1497]
Minecraft Version: 1.7.1
MySQL: false
BungeeCord: false

JSON components within `motd.yml` load before all other lines, regardless of placement in the file. (I have not tested JSON in other files.)

```
Parts:
  everything:
    Message:
    - '&8*----------------------------------------------------*'
    - '<center>&f&lHey, {player}! Welcome back to Prism Party!&r'
    - '<center>   &7It''s good to see you! There are currently &b{bungee_total}&7 players online.'
    - '&r'
    - '<center>&fFeel free to explore the lobby or connect'
    - '<center>&f to a server using an NPC ahead!'
    - '&r'
    - '[JSON] ["",{"text":"  Join Survival ","color":"light_purple","clickEvent":{"action":"run_command","value":"/server survival"},"hoverEvent":{"action":"show_text","value":["",{"text":"Click
    to join server","italic":true}]}},{"text":"&f| &dJoin Creative ","color":"light_purple","clickEvent":{"action":"run_command","value":"/server creative"},"hoverEvent":{"action":"show_text","value":["",{"text":"Click
    to join server","italic":true}]}},{"text":"&f| &dJoin Discord ","color":"light_purple","clickEvent":{"action":"open_url","value":"discord link"},"hoverEvent":{"action":"show_text","value":["",{"text":"Click
    to open link","italic":true}]}},{"text":"&f| &dNetwork Rules ","color":"light_purple","clickEvent":{"action":"run_command","value":"/rules"},"hoverEvent":{"action":"show_text","value":["",{"text":"Click
    to open menu","italic":true}]}}]'
    - '&8*----------------------------------------------------*'
```

Instead of the JSON appearing on the second to last line, as desired, it appears before all other content.
![image](https://user-images.githubusercontent.com/43658058/142915618-70c13455-d27a-4386-92b9-cc3e7f8fcbf7.png)

Although the placement is incorrect, the JSON itself does function (click events run properly).

**Comment by ElBananaa** [comment]
Hey,
Did you try to split your motd in 2 different parts, like the following? Does it change anything?:
```yaml
Parts:
  Part1:
    Message:
    - '&8*----------------------------------------------------*'
    - '<center>&f&lHey, {player}! Welcome back to Prism Party!&r'
    - '<center>   &7It''s good to see you! There are currently &b{bungee_total}&7 players online.'
    - '&r'
    - '<center>&fFeel free to explore the lobby or connect'
    - '<center>&f to a server using an NPC ahead!'
    - '&r'
  Part2:
    Message:
    - '[JSON] ["",{"text":"  Join Survival ","color":"light_purple","clickEvent":{"action":"run_command","value":"/server survival"},"hoverEvent":{"action":"show_text","value":["",{"text":"Click
    to join server","italic":true}]}},{"text":"&f| &dJoin Creative ","color":"light_purple","clickEvent":{"action":"run_command","value":"/server creative"},"hoverEvent":{"action":"show_text","value":["",{"text":"Click
    to join server","italic":true}]}},{"text":"&f| &dJoin Discord ","color":"light_purple","clickEvent":{"action":"open_url","value":"discord link"},"hoverEvent":{"action":"show_text","value":["",{"text":"Click
    to open link","italic":true}]}},{"text":"&f| &dNetwork Rules ","color":"light_purple","clickEvent":{"action":"run_command","value":"/rules"},"hoverEvent":{"action":"show_text","value":["",{"text":"Click
    to open menu","italic":true}]}}]'
    - '&8*----------------------------------------------------*'
```

**Comment by BakiDance** [comment]
I opened the file to try your suggestion and first saw that the plugin had restructured the contents, like so:

```
Parts:
  converted-8-1:
    Message: '&f'
  converted-8-2:
    Message: '&d  Join Survival '
    Hover:
    - '§f§f§oClick to join server'
    Run_Command: /server survival
  converted-8-3:
    Message: '&d&f| &dJoin Creative '
    Hover:
    - '§f§f§oClick to join server'
    Run_Command: /server creative
  converted-8-4:
    Message: '&d&f| &dJoin Discord '
    Hover:
    - '§f§f§oClick to open link'
    Open_Url: LINK REMOVED
  converted-8-5:
    Message: '&d&f| &dNetwork Rules '
    Hover:
    - '§f§f§oClick to open menu'
    Run_Command: /rules
  
  # See the chat.yml format file for a tutorial on how this works.
  everything:
    Message:
    - '&8*----------------------------------------------------*'
    - '<center>&f&lHey, {player}! Welcome back to Prism Party!&r'
    - '<center>   &7It''s good to see you! There are currently &b{bungee_total}&7 players online.'
    - '&r'
    - '<center>&fFeel free to explore the lobby or connect'
    - '<center>&f to a server using an NPC ahead!'
    - '&r'
    - '&8*----------------------------------------------------*'
```

So, in moving the JSON to this format (why?), it didn't account for the original spacing.

I'm sure there's a reason, but this conversion seems like an unnecessary and confusing extra step as I wasn't expecting the file to be overwritten by the plugin as I was editing it. This behavior should probably be mentioned on the [JSON wiki page](https://github.com/kangarko/ChatControl-Red/wiki/JSON) as this isn't something most people will consider while configuring their messages.

Trying your solution did work, although the JSON in that was also converted, like above, and required a bit of extra editing to get right.
