### ISSUE TITLE
1.17.1: DiscordSRV placeholders in messages aren't working

### ISSUE THREAD

**Issue by n-aspen** [kangarko/ChatControl#1499]
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true

I'm trying to use the `discordsrv_user_top_role_name` placeholder from DiscordSRV in messages sent from discord by using the `sender_is_discord` Sender Condition and it isn't working at all. 

I've attached an image showing a message coming from discord and the placeholder being parsed by the `papi parse` command. 
This is the message part I'm using to add the prefix to Discord messages. 
``` YAML
discordPrefix:
    Sender_Condition: '{sender_is_discord}'
    Message: '{discordsrv_user_top_role_name}'
```
![MOV-2021-11-23__7991](https://user-images.githubusercontent.com/16448318/143083904-9ba7dd78-6c28-4965-8322-3a287daf4427.png)
