### ISSUE TITLE
Spy channel between bungeecord

### ISSUE THREAD

**Issue by div2005** [kangarko/ChatControl#1549]
Hi! I have a problem with connecting my local chat between bungeecord servers. It works fine beetween one server , but when i send a message to local chat on server "A" all of players on server "B" receive it too. I don't want to show to for all player, only to staff as a spy.

**Configuration:**
```yml
Local:
  Format: local-chat
  Format_Console: '&f[&7L&f] {pl_prefix}&7{player_nick}&8: &7{message}'
  Format_Spy: spy-local
  Bungee: true
  Range: 100
```

Minecraft Version: 1.18
MySQL: true
BungeeCord: true
Latest ChatControlRed version
