### ISSUE TITLE
1.17.1: Stuck in Message_Delay

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl#1557]
```
Channels:
  List:
    global:
      Format: global-chat
      Message_Delay: 10 minutes
      Bungee: true
```

Configuring a substantially long Message_Delay gets you stuck into a channel. You can't speak (which is normal), but you can't execute commands either. Meaning you can't leave (the global channel in this case) to another channel.
 
 Any workarounds? Or does this need to be fixed?
 
Minecraft Version: 1.17.1
MySQL: true
BungeeCord: true
