### ISSUE TITLE
Mysql Potential Config Bug

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#158]
chc 10.1.0 this appears in the `settings.yml` of a fresh install. Should probably be removed in favour of that `mysql.yml` file.
```yaml
# -------------------------------------------------------------------------------------------------
# MySQL connection allows to store same information over multiple servers.
# -------------------------------------------------------------------------------------------------
MySQL:

  # Save players' data to the database when they exit the server and load them on join?
  Enabled: true

  # Use host/database/user/password information from mysql.yml file (will be created) instead of
  # the information below.
  Separate_Logins: true
  
  # The host and the port to connect to.
  Host: localhost:3306
  
  # The database name.
  Database: minecraft

  # The username.
  User: ''

  # The password.
  Password: ''
```
