### ISSUE TITLE
1.17.1 You are broardcasting the admin chat to Dynmap public chat.

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1581]
Not sure whats going on here, but when I post in my admin chat it appears in my live dynmap chat as tho its global chat, this is a little bit of a security issue.
Its something to do with OP/Admin because other people writing in admin chat are not appearing in it, so what crazy weird permission does that?

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
Hey,
In your settings file, set `Cancel_Event: true` in the `List;` part, like the following:
```
  List:
    general:
      Format: general-chat
      Format_Spy: none
    staffchat:
      Format: staff-chat
      Format_Spy: none
      Format_Console: none
      Cancel_Event: true
```

It should solve your issue.
Let me know down below if it doesn't.
