### ISSUE TITLE
[VIP] Showing up before my name and I dont see where to remove it.

### ISSUE THREAD

**Issue by SlothUS** [kangarko/ChatControl#159]
How do I remove the [VIP] tag before my name?

**Comment by EvilOlaf** [comment]
Pre- and Suffixes are parsed through Vault and your permissions plugin. Remove the affected prefix there and you are good to go.

**Comment by SlothUS** [comment]
@EvilOlaf I don't have a VIP rank though. Here is what it looks like: http://imgur.com/a/W4nVr

CM is my only rank that I should have but this random VIP thing pops up. There is no VIP group at all in perms

**Comment by SlothUS** [comment]
So I disabled interactive chat and it fixed both of my problems. Any way to fix this with interactive chat on?

**Comment by EvilOlaf** [comment]
For further investigation please stick to the issue report template and provide all necessary information: https://github.com/kangarko/ChatControl/blob/master/CONTRIBUTING.md

**Comment by kangarko** [comment]
You are using the pro version, while this issue section is for the free one.

Please navigate to chat.yml and from

Formats:

```
  # Name doesn't matter, but you can refer to it from other parts of the plugin.
  Example_Format:
    
    # Create as many as you like.
    # Hover actions are: SHOW_TEXT, SHOW_ACHIEVEMENT and SHOW_ITEM
    # Click actions are: OPEN_URL, OPEN_FILE, RUN_COMMAND and SUGGEST_COMMAND
    Parts:
      
      Staff:
        Message: "&6[VIP] "
        ....
```

Remove all Staff lines.
