### ISSUE TITLE
1.17.1: pm-sender Suggest_Command placeholder works, but helpop.yml does not, identicle formatting.

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1609]
I have identical formatting in pm-sender.yml and helpop.yml, where if you click the prefix it puts their message into chat so the player can effectively/copy paste a message sent to them, but for some unknown reason its not working in helpop and just outputting {Message} even tho its identical.

Its a simple Idea I came up with that would be extremely handy for all messages in-game chat which is just adding:
`Suggest_Command: '{message}'` Then we can easily copy/paste things sent to us from any channel (if it worked)

Why does this work in pm-sender and not the helpop channel?

pm-sender.yml
```
Parts:
  prefix:
    Message: '&c✉ '
    Hover:
    - '<center>&8[ &eCopy Message &8]'
    - '&6Click to copy message into chat'
    - '&6Then you can copy/paste it'
    Suggest_Command: '{message}'
  mainmessage:
    Message: '&8[&cyou &7-> &f{receiver}&8] &f{message}'
    Hover:
    - '<center>&8[ &ePrivate Message &8]'
    - '&6Sent: &f{timestamp}'
    - '&6Receiver: &f{sender}'
    - '&6Body: &f{message}'
    - ''
    - '&7Click to reply.'
    Suggest_Command: '/r '
```
Helpop.yml
```
Parts:
  prefix:
    Message: '#FFDD00HELP '
    Hover:
    - '<center>&8[ &eCopy Message &8]'
    - '&6Click to copy message into chat'
    - '&6Then you can copy/paste it'
    Suggest_Command: '{message}'
  Player:
    Message: '&f{display_name} '
    Hover:
    - '&7Rank&8: &e{pl_group}'
    - '&7Ping&8: &b{player_ping}'
    Suggest_Command: '/msg {player} '
  mainmessage:
    Message: '#FFDD00{message}'
    Hover:
    - '&7Posted: &b{timestamp}'
    - '&7Click to reply in chat'
    Suggest_Command: '/h '

```

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false
