### ISSUE TITLE
1.17.1 Deleting player messages stopped working after a few seconds of enabeling it?

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1612]
I copied this directly from chat.yml into my global-chat.yml 

```
  # Show the [X] button only visible to people having permission on 'Receiver_Permission'
  # that enables you to remove chat messages by clicking on them!
  # PS: They are still saved to log and can be viewed with "/chc log".
  # TIP: Give yourself chatcontrol.bypass.spamkick to prevent being kicked when removing mass messages.
  delete-chat:
    Message: '&8[&4X&8] &f'
    Receiver_Permission: chatcontrol.removemessages
    Hover:
    - '&cRemove this message from chat for all players.'
    Run_Command: /{label} internal remove {message_uuid}
```
I gave the staff `chatcontrol.removemessages` which showed them the X and they could delete messages, then we talked a bit more, and none of us can delete any more messages, theres no console/in-game messages to say why, nothing else was changed, we deleted a few then wrote some more and it no longer works.

Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false
