### ISSUE TITLE
1.18.1: ChatControlRed 10.9.1 encountered a FoException - Key 'message_uuid' is already in the map

### ISSUE THREAD

**Issue by Terminal-Access** [kangarko/ChatControl#1616]
Minecraft Version: 1.18.1
Server Version: paper-1.18.1-133
Chat Control Red Version: 10.9.1
Java: 17.0.1 2021-10-19 LTS
MySQL: False
BungeeCord: False

### Double Chat output and console is spilling a "FoException" over and over when ever some one talks.

Console Error Snippet:
```
ChatControlRed 10.9.1 encountered a FoException
~snip
Key 'message_uuid' is already in the map -->
```

Logs below show from my dev environment, with two clients connected, one set as an owner (highest rank on the server) the other is a regular player, attempted to PM across that seemed to work but still console was filling the the same "FoException" error. included full server log file (latest.log) in case it was needed.

Full [Error.log](https://pastebin.com/3Ef0Ujbp)
Full [latest.log](https://pastebin.com/vsVhiCaj)
Full CHC Debug: [debug.zip](https://github.com/kangarko/ChatControl-Red/files/7809740/debug.zip)

Screenshot of Chat (first output is correct, second is the duplicated.)
![2022-01-04_18 50 07](https://user-images.githubusercontent.com/6170786/148109147-3288e1b5-c93e-45a7-b6e8-a5e2d3ea0bde.png)

**Comment by TehZombiJesus** [comment]
I have a similar issue but mine prevent sending private messages.

Minecraft Version: 1.18.1
Server Version: paper-1.18.1-133
Chat Control Red Version: 10.9.1
Java: 17.0.1 2021-10-19 LTS
MySQL: False
BungeeCord: False

[Error.log](https://pastebin.com/aCAMALQZ)
[latest.log](https://pastebin.com/4jhSm7K9)

**Comment by pupshadow** [comment]
I have a similar issue here with discord messages and regular chat.

I'm also getting a Unhandled exception listening to PlayerCommandPreprocessEvent error as well with the other ones on here.


Minecraft Version: 1.18.1
Server Version: paper-1.18.1-133
Java: 17.0.1 2021-10-19 LTS
MySQL: False
BungeeCord: False

error log file: https://pastebin.com/TT3fGPkg

**Comment by c0wg0d** [comment]
I have the same problem on Paper 1.17.1.  I'm rolling back to ChatControl 10.8.8 for now.

```
ChatControlRed 10.9.1 encountered a FoException
~snip
Key 'message_uuid' is already in the map -->
```

**Comment by pupshadow** [comment]
Found a workaround turn off the spy for chat.

**Comment by Terminal-Access** [comment]
> Found a workaround turn off the spy for chat.

Sadly that did not work for me, with spy completely disabled i still get the same error's popping and double chat output being shown.

**Comment by pupshadow** [comment]
> > Found a workaround turn off the spy for chat.
> 
> Sadly that did not work for me, with spy completely disabled i still get the same error's popping and double chat output being shown.

So you don't have anything in your config for spy it should look like this?
```
Spy:
  
  # Where should we enable this feature?
  # Options: chat, command, private_message, mail, sign, book, anvil
  Apply_On:


  
  # What prefix should we display before all formats below?
  # You can disable this per-format by prepending it with "@noprefix"
  Prefix: '&8[&5Spy&8] '
```


I turned off everything in this setting here and it fully fixed the 
```
ChatControlRed 10.9.1 encountered a FoException
~snip
Key 'message_uuid' is already in the map -->
```
for me.

**Comment by Terminal-Access** [comment]
```
Spy:
  
  # Where should we enable this feature?
  # Options: chat, command, private_message, mail, sign, book, anvil
  Apply_On:


  
  # What prefix should we display before all formats below?
  # You can disable this per-format by prepending it with "@noprefix"
  Prefix: '&8[&5Spy&8] 
```

Mines almost similar however I commented mine out. will try completely removing so it mirrors yours and report back.
  
  
  ### Important Update:  
  Seems I can neither comment out or completely remove thease from my settings.yml as since the update all my CCR config / formatting files get re-written if their missing some thing from the defaults at server start every time.
  
  At this rate id have to lock the file after editing to prevent it "over riding my changes"  this may very well be a major bug in its self with the new yml changes spigot introduced in to the recent bukkit upstream.
