### ISSUE TITLE
Double messages

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#163]
After migrating and using `/papi ecloud download luckperms` and `/papi reload`:
chat.yml:
```yaml
Parts:
  Prefix:
    Message: '{luckperms_prefix}'
    Hover:
    - '&8*-----* &f{player} &8*-----*'
    - '&8This user is a &6{pl_group}&8,'
    Run_Command: /info
  Player:
    Message: '{cmi_user_display_name}&f:'
    Hover:
    - 'click to private message'
    Suggest_Command: '/msg {player} '
  The_Rest:
    Message: '{luckperms_suffix} {message}'
```
My chat.yml appears to be sending 2 messages for every 1 message I send.
(note before reloading (/papi reload) it was sending 1 message, and after it's sending 2)
I am assuming this has to do with placeholder handling because it started when i reloaded the papi.
Gif for reference: https://gyazo.com/0d2413e7b6ccad986985768334988576

Chc 10.1.0
