### ISSUE TITLE
Auto recognise hyperlinks in chat, color them and make them clickable. 

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1631]
There's an issue with hyperlinks (that are allowed) that if you have a click event on your chat, you can not click hyperlinks.
We should already be detecting hyperlinks using the regex, so ones that are allowed can we:

1. Make them clickable, even if the formatting has its own click action.
2. Give them a color or an underline, so that we can see its a link.

**Comment by kangarko** [comment]
It is on the client to automatically find www and http links, I believe that's out of my scope or expertise at the moment, apologies!

But if you have a click event set in your format and that doesn't work, please post me that format and I'll have a look since it may just be a bug.

**Comment by TomLewis** [comment]
It dousn't work with any click action.
```
  mainmessage:
    Message: '#FFDD00{message}'
    Hover:
    - '&7Posted: &b{timestamp}'
    - '&7Click to reply in chat'
    Suggest_Command: '/h '
```

Main message when clicked is to /h, but hyperminks cannot be clicked.
