### ISSUE TITLE
1.18.1: When /msg'ing on my server, "Player %player% is not online on this server"

### ISSUE THREAD

**Issue by Jupitour** [kangarko/ChatControl#1632]
1) Every version is latest.
2) No errors happen when trying to /msg

Description:
As described in the title, /msg'ing completely doesn't work as the plugin doesn't recognise anyone as online, even if the player is in fact on the server.

ChatControlRed v10.9.0
Minecraft Version: 1.18.1
Purpur version git-Purpur-1497 (MC: 1.18.1)
MySQL: false
BungeeCord: false

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7835792/debug.zip)

**Comment by internationalcrisis** [comment]
We are currently experiencing the same issue. This extends past /msg to anything involving online players, including other commands such as /motd and /list. This issue is reproducible across fresh server installs running the plugin by itself. We are unable to determine when the issue has started occurring.

/msg will reply with an error that the requested player is not online, even if they are on the server, while /list will return an error that it could not retrieve the page, presumably because the list of online players is empty.

There are no further errors or stack-traces (that I know of) that I can share,

ChatControl Red Version: v10.9.0
Minecraft Version: 1.18.1
Paper Version: #142 [a736c1a]
MySQL: false
BungeeCord: false

Seen below is our debug.zip. Some things have been redacted due to the large scope of info dumped. but nothing that should affect any debugging efforts.

Thanks.
~Crisis

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7836485/debug.zip)

**Comment by ACFC2** [comment]
We are currently experiencing the same issue exactly as described in the post by @internationalcrisis. 

Paper: #142
ChatControl: v10.9.0
MC: 1.18.1

**Comment by lerndmina** [comment]
Currently experiencing the exact same issue as @internationalcrisis 

ChatControlRed v10.9.0
Minecraft Version: 1.17.1-R0.1-SNAPSHOT
Paper version git-Paper-402 (MC: 1.17.1)
MySQL: true
BungeeCord: true

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/7848747/debug.zip)

# EDIT
I messed up and forgot to check the config line 
```yml
# Integration with BungeeCord.
  BungeeCord:
 
    # Hook to BungeeCord? **Requires BungeeControl Red**
    # [IMPORTANT] Change your server-name key in server.properties first (make this key unique
    # for each server)
    Enabled: true
```
It's working now
