### ISSUE TITLE
What is the permisison to toggle msg now?

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#1653]
Im confused with how all these toggle permissions work, I just want to give players the ability to toggle their messages.
but in https://github.com/kangarko/ChatControl-Red/wiki/Permissions its saying its the ignore command?
and in verbose LP its showing `chatcontrol.command.toggle.pm`...

**Comment by TheIntolerant** [comment]
These are the permissions here.
```
@Permission("Toggle seeing parts of the plugin. Replace type with: mail, announcement, me, pm, death, join, kick, quit, list, me, pm, quit")
public static final String TOGGLE = "chatcontrol.command.toggle.{type}";

@Permission("Toggle a given plugin part on, see the main toggle permission.")
public static final String TOGGLE_STATE_ON = "chatcontrol.command.toggle.on";

@Permission("Toggle a given plugin part off, see the main toggle permission.")
public static final String TOGGLE_STATE_OFF = "chatcontrol.command.toggle.off";

```

**Comment by kangarko** [comment]
Closing since Tom seems not to have more questions. I will also make the toggle.on and toggle.off true by default from the next version, two less perms to give.

**Comment by TomLewis** [comment]
incase anyone else finds this, it also required `chatcontrol.command.toggle` this is what I ended up with.
```
- chatcontrol.command.toggle:
    value: true
- chatcontrol.command.toggle.on:
    value: true
- chatcontrol.command.toggle.off:
    value: true
- chatcontrol.command.toggle.pm:
    value: true
- chatcontrol.command.toggle.join:
    value: true
- chatcontrol.command.toggle.death:
    value: true
- chatcontrol.command.toggle.quit:
    value: true
```
