### ISSUE TITLE
1.18.1: Can "/" be used in books?

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#1682]
Hi, I have a very small doubt
How do I make the full urls appear in my books?
![image](https://user-images.githubusercontent.com/55666349/151284390-b28a41c1-8118-47b4-b93d-2480b304c7cc.png)
![image](https://user-images.githubusercontent.com/55666349/151284410-7264846a-3bc3-41c8-8e80-2ede8ea03e54.png)

It doesn't show me the slash "/"

Minecraft Version: 1.18.1
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
> Hi, I have a very small doubt How do I make the full urls appear in my books? ![image](https://user-images.githubusercontent.com/55666349/151284390-b28a41c1-8118-47b4-b93d-2480b304c7cc.png) ![image](https://user-images.githubusercontent.com/55666349/151284410-7264846a-3bc3-41c8-8e80-2ede8ea03e54.png)
> 
> It doesn't show me the slash "/"
> 
> Minecraft Version: 1.18.1 MySQL: false BungeeCord: false

Hey,
Please try adding a backslash, like the following `www.google.com\/google`

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/55666349/151647922-0b5012b4-8378-4a55-a954-8656b7646369.png)
![image](https://user-images.githubusercontent.com/55666349/151647929-c3aeb6d1-18c4-4454-bcce-066bb26fda1b.png)
Is the same

**Comment by ElBananaa** [comment]
Seems like an issue with the plugin.
Please wait for Kangarko to take a look at it ^^

**Comment by kangarko** [comment]
Cannot reproduce, must be something going on with the server or your other plugins. If you use ViaVersion or ProtocolLib try without them.

<img width="371" alt="Screenshot 2022-02-01 at 16 27 16" src="https://user-images.githubusercontent.com/1918426/151997789-1b2ba4cb-c05b-4b17-82fd-8cc7b644273c.png">

**Comment by vitaly-rudenko** [comment]
@kangarko I can reproduce

<img width="421" alt="image" src="https://user-images.githubusercontent.com/1491646/161131643-dc73ef4e-0354-4a2e-9d6d-a9293e4ce3b8.png">
<img width="654" alt="image" src="https://user-images.githubusercontent.com/1491646/161133037-470b2add-4c10-4a32-8a81-7d6faf394a3b.png">
<img width="733" alt="image" src="https://user-images.githubusercontent.com/1491646/161133080-acd5230a-8df6-400b-9476-9768f676ad0b.png">

```
Data:
  Title: Help
  Author: user
  Pages:
  - |2
    &1/reg <password>
```

Client 1.18.2 (not cracked, no mods, no optifine)
<img width="305" alt="image" src="https://user-images.githubusercontent.com/1491646/161134138-0743bba1-047d-4d67-bd88-4e7959030f61.png">

With this command:
```
/chc book open help user
```

In my case, previous version where "/" was shown in books properly:
- ChatControlRed: 10.3.5
- PaperMC 1.16.5-592

**Comment by vitaly-rudenko** [comment]
Btw even tried to create a new book with `/chc book new` and it has been saved like this (without "/"):
```
Data:
  Title: test
  Author: user
  Pages:
  - reg <password>
  Signed: true
  Last_Modified: 1648755237725
  Unique_Id: 486faf49-6cb3-4d48-ab26-68da1b3093a5
```

**Comment by vitaly-rudenko** [comment]
Btw even tried to create a new book with `/chc book new` and it has been saved like this (without "/"):
```
Data:
  Title: test
  Author: user
  Pages:
  - reg <password>
  Signed: true
  Last_Modified: 1648755237725
  Unique_Id: 486faf49-6cb3-4d48-ab26-68da1b3093a5
```

@ElBananaa will ping you just in case
