### ISSUE TITLE
1.18.1: Setting up Towny channels properly.

### ISSUE THREAD

**Issue by jga01** [kangarko/ChatControl#1687]
Minecraft Version: 1.18.1
MySQL: false
BungeeCord: false

Hello! This is how I setup my Towny town/nation channels:

Settings.yml:

```
    town:
      Format: town-chat
      Party: towny-town
    nation:
      Format: nation-chat
      Party: towny-nation
```

Format (town-chat):

```
    Parts:
      delete-chat:
        Message: '&8[&4X&8] &f'
        Receiver_Permission: chatcontrol.removemessages
        Hover:
        - '&cRemove this message from chat for all players.'
        Run_Command: /{label} internal remove {message_uuid}
      spies-prefix:
        Message: '&8[&5Spy&8] &f'
        Receiver_Condition: '{player_is_spying_{channel}}'
        Hover:
        - '&dClick to stop spying {channel} channel.'
        Run_Command: /{label_spy} toggle chat {channel}
      channel-tag:
        Message: '&8[&eTown Chat&8] '
        Hover:
        - '&7Only your town can read this.'
      prefix:
        Message: '{player_prefix+}'
        Hover:
        - '&7{player_prefix+}{player_name} {player_suffix}'
        - '&7Ping&8: &f{ping}ms'
        - '&7Rank&8: &f{player_group}'
        - '&7Posted: &f{timestamp}'
        - ''
        - '&7Click to learn more about ranks.'
        Open_Url: https://mineacademy.org/project-orion
      player-name:
        Message: '&7{player_nick}'
        Hover:
        - '&7Click to message.'
        Suggest_Command: '/tell {player_name} '
      message:
        Message: :&f {player_suffix}{message}
```

Format (nation-chat):

```
    Parts:
      delete-chat:
        Message: '&8[&4X&8] &f'
        Receiver_Permission: chatcontrol.removemessages
        Hover:
        - '&cRemove this message from chat for all players.'
        Run_Command: /{label} internal remove {message_uuid}
      spies-prefix:
        Message: '&8[&5Spy&8] &f'
        Receiver_Condition: '{player_is_spying_{channel}}'
        Hover:
        - '&dClick to stop spying {channel} channel.'
        Run_Command: /{label_spy} toggle chat {channel}
      channel-tag:
        Message: '&8[&eNation Chat&8] '
        Hover:
        - '&7Only your nation can read this.'
      prefix:
        Message: '{player_prefix+}'
        Hover:
        - '&7{player_prefix+}{player_name} {player_suffix}'
        - '&7Ping&8: &f{ping}ms'
        - '&7Rank&8: &f{player_group}'
        - '&7Posted: &f{timestamp}'
        - ''
        - '&7Click to learn more about ranks.'
        Open_Url: https://mineacademy.org/project-orion
      player-name:
        Message: '&7{player_nick}'
        Hover:
        - '&7Click to message.'
        Suggest_Command: '/tell {player_name} '
      message:
        Message: :&f {player_suffix}{message}
```

Issue: Townless/Nationless players are able to join these channels.
