### ISSUE TITLE
1.16.5 - Variables for Spy status on certain chc components.

### ISSUE THREAD

**Issue by Alucardz997** [kangarko/ChatControl#1699]
Hi Team,

I need your help in order to understand how a particular variable shall be used.
I'm trying to build a custom GUI Menu using Deluxemenus in order to cover the /spy functionalities, as below:

```
      '1':
        material: 'hdb-31896'
        slot: 22
        display_name: '&c☏ &a&nComenzi Executate&r &c☏'
        lore:
        - ' '
        - '&f&nDescriere'
        - ' '
        left_click_commands: 
        - '[console] spy toggle command %player_name%'
        right_click_commands: 
        - '[console] spy toggle command %player_name%'
      '2':
        material: 'hdb-31896'
        slot: 22
        display_name: '&c☏ &a&nComenzi Executate&r &c☏'
        view_requirement:
          requirements:
            spyactivatedcmds:
             type: string contains
             input: "%chatcontrolred_player_is_spying_command%"
             output: "true"
        enchantments:
          - DIG_SPEED;1
        lore:
        - ' '
        - '&f&nDescriere'
        - ' '
        left_click_commands:
        - '[console] spy toggle command %player_name%'
        right_click_commands: 
        - '[console] spy toggle command %player_name%'
```

The idea is that when the variable %chatcontrolred_player_is_spying_command% returns the value "true" the second item would overide the first one and offer the glowing effect.
That glowing effect would confirm that the spy is active on that particular chc component.
I need to understand what variables I shall use for commands and private messages in order to make this work.
Below is a similar application of this view requirements and it works as described above.

```
      '1':
        material: golden_axe
        slot: 19
        priority: 3
        display_name: '&a&lPadurar &8▪ &7%jobsr_totalplayers_Woodcutter% angajati'
        hide_attributes: true
        lore:
        - '&8Angajat: %jobsr_user_isin_Woodcutter%'
        - ''
        - '&aDescriere:'
        - ''                
        left_click_commands:
        - '[player] jobs join Woodcutter'
        - '[refresh]'
        right_click_commands:
        - '[openguimenu] woodcutter'
      '2':
        material: golden_axe
        slot: 19
        priority: 2
        view_requirement:
          requirements:
            joined:
             type: string contains
             input: "%jobsr_user_isin_Woodcutter%"
             output: "True"
        enchantments:
          - DIG_SPEED;1
        hide_enchantments: true 
        hide_attributes: true               
        display_name: '&a&lPadurar &8▪ &7%jobsr_totalplayers_Woodcutter% angajati'
        lore:
        - '&8Angajat: %jobsr_user_isin_Woodcutter%'
        - ''
        - '&aDescriere:'
        - ''
        left_click_commands:
        - '[player] jobs leave Woodcutter'
        - '[refresh]'
        right_click_commands:
        - '[openguimenu] woodcutter'
```

Thank you!
