### ISSUE TITLE
1.18.1: In-discord formatting ignores formatting file

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl#1728]
I have my chat configured like this:
```
List:
    global:
      Format: global-chat
      Format_Console: '[GLOBAL] {player}: {message}'
      Format_Discord: global-chat-discord
      Format_Spy: none
      Discord_Channel_Id: 807805085988028427
```
And my `global-chat-discord.yml` configured like this:
```
Parts:
  Not_Discord:
    Message: '[_{pl_prefix}_] **{player}**: {message}'
    Sender_Condition: '{sender_is_player}'
  Discord:
    Message: '{#7289da}&lＤ &r{player_nick}&r: {#ebc59b}{message}'
    Sender_Condition: '{sender_is_discord}'
    Hover:
    - '{#7289da}This is a message from Discord'
    - '{#7289da}Welcome!'
    Open_Url: LINK_DELETED
```
In-game I see the format as specified in `Discord` section. But in discord I see it like this:
![image](https://user-images.githubusercontent.com/43506080/153856134-bbe0d3ff-7e97-43ec-981a-da439cb714b1.png)
Instead of of receiving same messages I expected to see player messages.

CCR: 10.9.9
Minecraft Version: 1.18.1
MySQL: false
BungeeCord: false
