### ISSUE TITLE
1.18.1: Messages from discord are not sent if username contains non-latin chars

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl#1729]
I set username `Радиант` in discord: messages are getting stuck and never deleted by the bot or sent to the server. (1st message)
I set username `Radiant` in discord: messages successfully are sent to the server. (2nd message)

![image](https://user-images.githubusercontent.com/43506080/153859315-10eaf924-30cd-463b-ad7c-8afd82acb437.png)

CCR: 10.9.9
Minecraft Version: 1.18.1
MySQL: false
BungeeCord: false

**Comment by radiant-ai** [comment]
Issue was caused because {player_nick} was used in format and it looks like it tried to find player with same name

**Comment by TheIntolerant** [comment]
Just adding this for future reference should anyone come checking, 

To implement this fix as mentioned something similar to the following, was added to the format file for that channel:
```yml
  player-name:
    Message: '{player_nick}'
    Sender_Condition: '!{sender_is_discord}'
  discord-name:
    Message: '{player_name}'
    Sender_Condition: '{sender_is_discord}' 
```
