### ISSUE TITLE
1.18.1: Join,death,quit messages are not forwared to discord

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/ChatControl#1731]
As well as other issues after the update. Join,quit,death messages are not forwared to Discord, but they did before the update:
```
  Discord:
   join: 807805085988028427
   quit: 807805085988028427
   death: 807805085988028427
```

CCR: 10.9.9
Minecraft Version: 1.18.1
MySQL: false
BungeeCord: false
