### ISSUE TITLE
1.16.4 | special characters are not allowed error

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl#176]
Rename the file, I add this so plugin not load it.

console error
https://pastebin.com/W7AXzQAn

[regler2.zip](https://github.com/kangarko/ChatControl-Red/files/5607998/regler2.zip)

**Comment by kangarko** [comment]
There's some weird bug regarding NULL characters at the end of the file:
![a](https://i.imgur.com/qEudtxj.png)

If you use Notepad++ to edit you will see those. If you're on MacOS, use Sublime Text. Just remove those and it'll work. Or copy the code without these below:

```
Parts:
  regler:
    Message:
    - '                &4&l♛ Regler för Midgardsaga ♛'
    - '&2'
    - '&a∮1. Förstör//ta inte saker från andras byggen.'
    - '&9∮2. Bygg inte nära någon annan utan tillåtelse.'
    - '&a∮3. Ingen spamm eller reklam i chatten eller DC.'
    - '&9∮4. Vårda ditt språk barnvänlig server.'
    - '&a∮5. Inga Mods//Fusk eller Glitch utnyttjanden.'
    - '&9∮6. Inga Politiska//Rasistiska//Sexistiska yttranden.'
    - '&a∮7. Respektera andra spelare.'
    - '&9∮8. PvP skall endast hållas på utsata platser.'
    - '&a∮9. All redstone byggen skall gå att stänga av.'
    - '&9∮10. Lyssna på Admin'
    - '&6 Föklaring finns på Midgardsaga discord (tryck på texten)'
    Hover: '&fTryck för få länk till discord'
    Run_Command: 'https://discord.gg/vnVAVPkb'
```
