### ISSUE TITLE
1.18.2: Join/Leave messages

### ISSUE THREAD

**Issue by Suinalk** [kangarko/ChatControl#1801]
Minecraft Version: 1.18.2
MySQL: false
BungeeCord: false

Join/leave messages cannot be changed or modified, still stays default.

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/8311868/debug.zip)

**Comment by Suinalk** [comment]
Sorry I'm new to github, I couldn't find the older  chat thing.

**Comment by james090500** [comment]
You don't have join or leave messages turned on. 

Line 155 of your config

```yaml
Messages:
  Apply_On: []
  Stop_On_First_Match:
  - join
  - quit
  - kick
  - death
  - timed
  Prefix: {}
  Discord: {}
  Defer_Join_Message_By: 1 tick
  Timed_Delay: 10 seconds
  Async: []
```

It should be

```yaml
Messages:
  Apply_On:
  - join
  - quit
  Stop_On_First_Match:
  - join
  - quit
  - kick
  - death
  - timed
  Prefix: {}
  Discord: {}
  Defer_Join_Message_By: 1 tick
  Timed_Delay: 10 seconds
  Async: []
```
