### ISSUE TITLE
1.18.2: Links not working in chat

### ISSUE THREAD

**Issue by dandyjay** [kangarko/ChatControl#1816]
Minecraft Version: 1.18.2
MySQL: false
BungeeCord: false

Wondering how I can get links to embed in my chat? Whenever I post a link it can't be clicked on. Is this some setting I am not seeing that needs to be enabled?

Thanks

**Comment by TheIntolerant** [comment]
If you have essentials installed, if users do not have the following permission nodes ``essentials.chat.url``, ``essentials.msg.url``, this can cause the links to break which are posted into chat.

If this is not the case for you and the links themselves do not contain spaces (due to essentials breaking the links themselves etc), please post your format file below regarding the channel this is happening to so that it can be reviewed.

**Comment by dandyjay** [comment]
I'm using CMI, and it looks like _some_ links are working but not others. When I post links to a lightshot screenshot it embeds but when I try to link to our own website https://bitrealm.online/ it doesn't embed. I'm not sure what the difference is other than the domain suffix. I'm assuming it only embeds traditional .coms or .nets

Here is my format file:
```yml
Parts:

  delete-chat:
    Message: '&8[&4X&8] &f'
    Receiver_Permission: chatcontrol.removemessages
    Hover:
    - '&cRemove this message from chat for all players.'
    Run_Command: /{label} internal remove {message_uuid}
  
  read-prefix:
    Message: '&8[&bRead&8] '
    Receiver_Condition: '''{player_channel_mode_{channel}}'' == ''read'''
  
  discord-prefix:
    Message: '&8[&9Discord&8] &f'
    Sender_Condition: '{sender_is_discord}'
    Hover:
    - '&bJoin our Discord at mineacademy.org/discord'
    Open_Url: https://mineacademy.org/discord
  
  spies-prefix:
    Message: '&8[&5Spy&8] &f'
    Receiver_Condition: '{player_is_spying_{channel}}'
    Hover:
    - '&dClick to stop spying {channel} channel.'
    Run_Command: /{label_spy} toggle chat {channel}
  class-prefix:
    Message: '&8&l[%tab_replace_mmocore_class%&f {mmocore_level}&8&l]'
    Hover:
    - '&7{player_prefix+}&f{player_name} {player_suffix}'
    - '&7Class: {mmocore_class}'
    - '&7Level: &f{mmocore_level}'

  prefix:
    Message: '{player_prefix+}'
    Hover:
    - '&7{player_prefix+}&f{player_name} {player_suffix}'
    - '&7Rank: &f{player_group}'
    - '&7Posted: &f{timestamp}'

  player-name:
    Message: '&f{player_nick}'
    Hover:
    - '&7Click to message {player_name}.'
    Suggest_Command: '/tell {player_nick} '

  message:
    Message: '{player_suffix}&f » {message}'
```

Here's an example of a link that works
`https://gyazo.com/b795233830333ed9fa61eaa7a30574ba`
`https://dandycorp.net/`
Here's an example of a link that doesn't
`https://bitrealm.online/donate/`
