### ISSUE TITLE
1.18.2 - Deleting individual messages in chat

### ISSUE THREAD

**Issue by itsBeaco** [kangarko/ChatControl#1824]
Minecraft Version: 1.18.2
MySQL: true
BungeeCord: true

Hey,

I have the format set up so that if you click the red [x] and it should delete individual messages from a player, and we have the permission `chatcontrol.removemessages`, but it doesn't seem to work for us. 

This is what our chat looks like:

![image](https://user-images.githubusercontent.com/77558094/160295238-29ee2e66-d3be-40a0-8105-1fd26972240d.png)

And this is part of our global chat format:
```
Parts:
  delete-chat:
    Message: '&8[&4X&8] &f'
    Receiver_Permission: chatcontrol.removemessages
    Hover:
    - '&cRemove this message from chat for all players.'
    Run_Command: /{label} internal remove {message_uuid}
```

Is there anything I can change to fix this and get it working?

Thank you in advance!
