### ISSUE TITLE
1.16.4 | Cannot measure distance between Midgardsaga_nether and Midgardsaga

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl#183]
The chat stop work and format not work when player are in nether.

```
mc-lokalt:
      Format: lokal_chat
      Format_Console: '&9Lokalt-&f{player}: &9{message}'
      Range: '100'
      Format_Spy: '@noprefix spy5'
```

Unhandled exception listening to AsyncPlayerChatEvent

https://pastebin.com/xdA3AK1J

**Plugins**
chatcontrol 1.0.1.2
cmi
