### ISSUE TITLE
Suggestion: Change to default file 'chat.yml'

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#1880]
Change to default files due to recent changes in **10.11.1**

Inside "chat.yml", this
```yml
  # And finally, show the message the player has typed out, prepending it with player's
  # suffix from your permission plugin. We replace {chat_color} and {chat_decoration} with the 
  # color and decoration set in '/chc color'.
  message: 
    Message: "&7: {player_suffix}{chat_color}{chat_decoration}{message}"
```
Should be changed to this
```yml
  # And finally, show the message the player has typed out, prepending it with player's
  # suffix from your permission plugin. We replace {chat_color} and {chat_decoration} with the 
  # color and decoration set in '/chc color'.
  # This format is used if the sender is not from discord!
  message: 
    Sender_Condition: '"{sender_is_discord}" == "false"'
    Message: "&7: {player_suffix}{chat_color}{chat_decoration}{message}"
  
  # Since {chat_color} and {chat_decoration} do not work if a message is sent from discord to minecraft,
  # we have two parts for {message}, the "message" part is used when the sender is not from discord, 
  # whereas the "message_discord" part is used when the sender is from discord
  message_discord: 
    Sender_Condition: '"{sender_is_discord}" == "true"'
    Message: "&7: &f{message}"
```
