### ISSUE TITLE
Format_From_Discord channel option?

### ISSUE THREAD

**Issue by Squeej** [kangarko/ChatControl#1893]
1. Would be nice to easily separate discord messages sent from game and from discord. I noticed in the notes, chc uses the standard option for this, but unfortunately the standard option is what I need for messages sent from Minecraft.

2. It's not a deal breaker, but would be a nice to have a bit more control, and I figured it wouldn't be too much to implement. Thanks for your consideration.

**Comment by TheIntolerant** [comment]
Could you please explain in further details the issue with having messages sent from discord handled via the standard Format option as this seems redundant. Especially since this is something that has changed before but ended up being reverted back to the original state due to issues caused by such changes.

---

Here is basic example of how I can customise the format of messages depending if they are sent from in-game or discord format using ``Sender_Condition``

Lets say I made a format file in the folder "formats" inside the chatcontrol folder and call this file ``global_channel.yml`` to use this file for my channel "global" inside my settings I use this

![image](https://user-images.githubusercontent.com/48093184/168464937-aaa5fa16-be17-47e4-b731-5d71860f27fa.png)
(so basically just the name of the file without the ".yml" part)

In that file I am using these conditions to help define my format depending on where the message is coming from.


``Sender_Condition: '!{sender_is_discord}'`` is used for all messages NOT sent from discord

``Sender_Condition: '{sender_is_discord}'`` is used for all messages sent from discord

```yml
Parts:
  player:
    Message: '&r{pl_prefix}&r{display_name}&r{pl_suffix}&8:'
    Sender_Condition: '!{sender_is_discord}'
  discord:
    Message: '&9[D] &7{top_role_alias} &f{player}&8:'
    Sender_Condition: '{sender_is_discord}'
  chat_message:
    Message: '&r &f{chat_color}{chat_decoration}{message}'
```
