### ISSUE TITLE
1.18.2: Question about structure of formats

### ISSUE THREAD

**Issue by leonardopilz** [kangarko/ChatControl#1989]
is there a way to set the tags in the chat by group and not by permission?

as per permission set all tags of all groups together in chat when there is an op

Minecraft Version: 1.18.2
MySQL: false
BungeeCord: false

**Comment by TheIntolerant** [comment]
If using permission based conditions, to removing the tags for OP's you must negate the permissions, but to answer your question yes this is possible.

In the default ``chat.yml`` you may have seen this
```yml
  vip-prefix: 
    Message: "&8[&6VIP&8] "
    Sender_Permission: chatcontrol.group.vip
```
---

If you don't want to use ``Sender_Permission`` you could change it for ``Sender_Condition``

Example:
```yml
  vip-prefix: 
    Message: "&8[&6VIP&8] "
    Sender_Condition: '"{luckperms_highest_group_by_weight}" == "vip"'
```
---
## Important things to note!

Make sure to check the output of the placeholder via
```
/chc info variables <name> <placeholder>
```
Example:
```
/chc info variables <name> {luckperms_highest_group_by_weight}
```
Because if the output is "VIP" but you write "vip" in the condition above, then people in the vip group won't get the tag

This setup will require you have PlaceholderAPI installed in order to use such placeholders in chatcontrol
