### ISSUE TITLE
1.19: Custom Variable seems to break at random

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#2005]
Hello, I have a custom variable to display a little star symbol if player has X permission. It works fine 99% of the time, but 1% of the time it will simply show the name of my variable, rather then what they're supposed to be seeing. Not sure if there is a better way to do this or if this is a bug, but any help appreciated.

Variable:
```js
getPronoun(); // call the function below that returns the tag or prefix

  function getPronoun() {
      // replace with the tag
      var tag = "{luckperms_check_permission_milestones.10}" == "yes";
     
      // if the tag is empty, return blank, else return tag
      return tag == "" ? "" : "#a19d94✦";
  }
```
I have 4 of the above variables, 10, 20, 30 and 40.
In my chat.yml format: 

```yml
  player-milestone:
    Message: '{milestones10}{milestones20}{milestones30}{milestones40}'
    Hover:
    - '&7Click to learn more!'
    Run_Command: /milestones
```
![image](https://user-images.githubusercontent.com/64336395/180079155-ad4e843f-9736-4110-ba81-7afe7624b87a.png)

This is what happens that 1% of the time, for basically a single message. After this screenshot, it returned to the normal star and was fine. No lag was occurring on the server at this time, and only had about 12 people on.
Minecraft Version: 1.19
MySQL: false
BungeeCord: false
