### ISSUE TITLE
How do I send a message to someone using a command?

### ISSUE THREAD

**Issue by MithrandirCraft** [kangarko/ChatControl#2079]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

Is there a way to send a formatted message to a player through a command?

My idea was to use the formating system usable in /messages and send players custom messages with a command.

I could then use a command to send these messages through other plugins.

For example, a MythicMob could display a message for a player using ChatControl.

The command could be something like /message1 <player>
Mythicmobs, any other plugin, or a player with permission for this command, would fill in the player part.

Is this currently possible or is there something similar that I could use?

**Comment by TheIntolerant** [comment]
So to do this you'll want to make a format file in ``/plugins/ChatControlRed/formats``

Say I call this new file ``example_format.yml`` and inside the file it looks like this
```yml
Parts:
  section1:
    Message:
    - '&4&m--------------------------------------------------&r'
    - '&r &fThis is an example'
    - '&4&m--------------------------------------------------'
```

Then say I want to make the command ``/test`` that send this message, I would go into ``/plugins/ChatControlRed/rules/command.rs`` and add this into the file
```
# This sends a message to a user when they type /test
match ^\/(test)\b
then warn example_format
dont verbose
then deny
```

If your still unsure have a read thru [[Format-Wiki]](https://github.com/kangarko/ChatControl-Red/wiki/Formats) and [[Rules-Wiki]](https://github.com/kangarko/ChatControl-Red/wiki/Rules)

Otherwise just comment below but hopefully I was clear enough!
