### ISSUE TITLE
[1.16.5] Help with DiscordSRV

### ISSUE THREAD

**Issue by anhvuquang0512** [kangarko/ChatControl#2083]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

I just want to use only 1 channel for messaging and I want to make it a format for chatting in the server and a format for messaging from discord to the server. Both are different chat format but the same channel, can you help me how to do it?

**Comment by ElBananaa** [comment]
Hey, sorry for the delay,
This can easily be achieved by editing your chat format file and playing around the `Sender_Condition: '{sender_is_discord}'` feature, like in the default chat.yml format file.
```yaml
Parts:

  # Show the [Discord] prefix if the sender is from Discord (we use our own
  # special variable for this) and add some interactive elements.
  discord-prefix:
    Message: '&8[&9Discord&8] &f'
    Sender_Condition: '{sender_is_discord}'
    Hover: '&bJoin our Discord at mineacademy.org/discord'
    Open_Url: https://mineacademy.org/discord
```


So basically, let's say you want some parts of you message to only be sent if the message comes from ingame players, you will use `Sender_Condition: '!{sender_is_discord}'`. If you want to display parts that will only be sent if the message comes from a discord user, you will use `Sender_Condition: '{sender_is_discord}'`


Here's an example made from the default chat format file
```yaml
Parts:

############################
############################ THE PARTS BELOW WILL ONLY BE SHOWN IF THE PLAYER IS INGAME
############################


  # Show the [X] button only visible to people having permission on 'Receiver_Permission'
  # that enables you to remove chat messages by clicking on them!
  # PS: They are still saved to log and can be viewed with "/chc log".
  # TIP: Give yourself chatcontrol.bypass.spamkick to prevent being kicked when removing mass messages.
  delete-chat:
    Message: '&8[&4X&8] &f'
    Sender_Condition: '!{sender_is_discord}
    Hover: '&cRemove this message from chat for all players.'
    Run_Command: /{label} internal remove {message_uuid}
    Receiver_Permission: chatcontrol.removemessages

  # Show the [VIP] prefix if sender, not receiver like above, has the 
  # permissions. All players will thus see the message.
  ingame-prefix:
    Sender_Condition: '!{sender_is_discord}
    Message: '&8[&6VIP&8] '
    Sender_Permission: chatcontrol.group.vip
  
  # Show the [Read] prefix if the receiver is only reading this channel.
  read-prefix:
    Sender_Condition: '!{sender_is_discord}
    Message: '&8[&bRead&8] '
    Receiver_Condition: '''{player_channel_mode_{channel}}'' == ''read'''

############################
############################ The part below will only be shown if the sender is a discord user
############################


  # Show the [Discord] prefix if the sender is from Discord (we use our own
  # special variable for this) and add some interactive elements.
  discord-prefix:
    Message: '&8[&9Discord&8] &f'
    Sender_Condition: '{sender_is_discord}'
    Hover: '&bJoin our Discord at mineacademy.org/discord'
    Open_Url: https://mineacademy.org/discord

############################
############################ THE PARTS BELOW WILL BE SHOWN NO MATTER IF THE MESSAGE COMES FROM AN INGAME PLAYER OR A DISCORD USER 
############################

  player-name:
    Message: '{player_nick}'
    #Message: "{player_name}"
    #Gradient: RED - YELLOW
    Hover: '&7Click to message.'
    Suggest_Command: '/tell {player_name} '

  # And finally, show the message the player has typed out, prepending it with player's
  # suffix from your permission plugin. We replace {chat_color} and {chat_decoration} with the 
  # color and decoration set in '/chc color'.
  message:
    Message: '&7: {player_suffix}{chat_color}{chat_decoration}{message}'
```
