### ISSUE TITLE
Server version 1.19.2 - Problem whit chat prefixes for ranks

### ISSUE THREAD

**Issue by gabriel262m** [kangarko/ChatControl#2198]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

No

### Question

![image](https://user-images.githubusercontent.com/48396708/204149366-96583d7d-8c1c-4873-92f1-7cdc284a2de0.png)
When i add in global 2 different ranks whit their respective prefix and other things, when the other player has inherited other ranks it seems duplicated instead of take the prefix based on priority, i couldnt find something for that, i aprreciate the help

**Comment by gabriel262m** [comment]
in the last one, i remove the other rank format in global-chat.yml

**Comment by TheIntolerant** [comment]
This is most likely caused by an innocent setup. Could you please provide the format file used for this channel and I might be able to provide some solutions based on your format.

**Comment by gabriel262m** [comment]
this is my global format
```yml
Parts:
  
  # See the chat.yml format file for a tutorial on how this works.
  everything:
    Message: '%img_usuario% {player_name}&7: {chat_color}{chat_decoration}{message}'
  pro:
    Message: '%img_pro% {player_name}&7: {chat_color}{chat_decoration}{message}'
    Sender_Permission: chatcontrol.group.pro
```

**Comment by TheIntolerant** [comment]
Try this
```yml
Parts:
  everything:
    Message: '%img_usuario% {player_name}&7: {chat_color}{chat_decoration}{message}'
    Sender_Condition: !player.hasPermission("chatcontrol.group.pro")
  pro:
    Message: '%img_pro% {player_name}&7: {chat_color}{chat_decoration}{message}'
    Sender_Permission: chatcontrol.group.pro
```
That way the "everything" part is only applied if the user does NOT have the permission ``chatcontrol.group.pro`` so it should stop it from doubling up
