### ISSUE TITLE
1.19.2: Console & Legacy Item name support with Death messages

### ISSUE THREAD

**Issue by TZ122** [kangarko/ChatControl#2217]
### "/version ChatControlRed" - plugin version

10.15.1

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

When using the death messages feature items with console and legacy format names do not format correctly. Many plugins use this format for custom item names.

How to replicate
1. Set death messages to enabled
2. Have a player kill another player with console format or legacy format item name
3. Result https://cdn.discordapp.com/attachments/755325303689052200/1046893785315037244/image.png

Example console format: §x§0§8§4§c§f§bt§x§1§3§5§7§f§be§x§1§e§6§2§f§bs§x§2§9§6§d§f§bt§x§3§4§7§9§f§cl§x§3§f§8§4§f§ce§x§4§a§8§f§f§cg§x§5§5§9§a§f§ca§x§6§0§a§5§f§cc§x§6§b§b§0§f§cy§x§7§6§b§b§f§cf§x§8§1§c§6§f§co§x§8§c§d§2§f§dr§x§9§7§d§d§f§dm§x§a§2§e§8§f§da§x§a§d§f§3§f§dt

Example legacy format
&x&0&8&4&c&f&bt&x&1&3&5&7&f&be&x&1&e&6&2&f&bs&x&2&9&6&d&f&bt&x&3&4&7&9&f&cl&x&3&f&8&4&f&ce&x&4&a&8&f&f&cg&x&5&5&9&a&f&ca&x&6&0&a&5&f&cc&x&6&b&b&0&f&cy&x&7&6&b&b&f&cf&x&8&1&c&6&f&co&x&8&c&d&2&f&dr&x&9&7&d&d&f&dm&x&a&2&e&8&f&da&x&a&d&f&3&f&dt

**Comment by kangarko** [comment]
As I told you elsewhere Bukkit has a hard limit on the length of the item and thus the data it provides to us are already "cut off", I am afraid I can't do much at the moment since we rely on the API from Bukkit

**Comment by TZ122** [comment]
> As I told you elsewhere Bukkit has a hard limit on the length of the item and thus the data it provides to us are already "cut off", I am afraid I can't do much at the moment since we rely on the API from Bukkit

Thanks! Apologies as I thought this was just an issue with those two formats since its the only time the error happens for me.

Will this be looked at in the future? (Its the only thing stopping me from switching to using CHCR for death messages) if not no worries. Thanks again^^

**Comment by kangarko** [comment]
What plugin are you using for death messages right now?

**Comment by TZ122** [comment]
> What plugin are you using for death messages right now?

https://www.spigotmc.org/resources/deathmessages.3789/

Its god awful want to get off of it fast aha. However it does work with all the above mentioned formats for itemnames

**Comment by kangarko** [comment]
It does work that means it removes the color codes and renders white name of the killer item?

**Comment by TZ122** [comment]
If the format of the item name is in console and a player kills another player it shows up in chat formatted correctly and not like this: https://cdn.discordapp.com/attachments/755325303689052200/1046893785315037244/image.png

Example console format: §x§0§8§4§c§f§bt§x§1§3§5§7§f§be§x§1§e§6§2§f§bs§x§2§9§6§d§f§bt§x§3§4§7§9§f§cl§x§3§f§8§4§f§ce§x§4§a§8§f§f§cg§x§5§5§9§a§f§ca§x§6§0§a§5§f§cc§x§6§b§b§0§f§cy§x§7§6§b§b§f§cf§x§8§1§c§6§f§co§x§8§c§d§2§f§dr§x§9§7§d§d§f§dm§x§a§2§e§8§f§da§x§a§d§f§3§f§dt

**Comment by kangarko** [comment]
Can you paste a screenshot how it looks like please?

**Comment by TZ122** [comment]
Item name is: &#084cfbb&#195dfbi&#296dfbr&#3a7efcd&#4a8ffcf&#5ba0fcl&#6bb0fco&#7cc1fcp&#8cd2fdc&#9de2fdo&#adf3fdm

Chatcontrol output: https://imgur.com/mCt5OVr

Deathmessages plugin output:  https://imgur.com/2N51xXk

**Comment by TZ122** [comment]
Seemed to happen for me for on Default &#rrggbb format and not console. Sorry for any confusion

**Comment by kangarko** [comment]
Thank you, that is clear now! I am going to investigate and try to fix.

**Comment by kangarko** [comment]
Okay I tried your other plugin but it still did not work... :D

<img width="1137" alt="Screenshot 2022-12-18 at 14 38 41" src="https://user-images.githubusercontent.com/1918426/208301573-fb53772e-1e76-4819-820c-0d83e3471302.png">

One thing you CAN do that is actually making the item look really nice in game also is giving it a unique name such as custom-item-1 or birdflopcom, and then adjusting your killer-item.yml file to manually return the HEX colorized name:

<img width="1146" alt="Screenshot 2022-12-18 at 14 41 28" src="https://user-images.githubusercontent.com/1918426/208301667-1b6ab6fc-492d-4f14-a3cc-847bc4f031f8.png">



That works fine! See line 45:

```yaml
# -------------------------------------------------------------------------------------------------
# ChatControl supports dynamic, high performance variables you create! They can be used across
# the plugin, for example in formatting your chat or death messages. Currently, the folder
# variables/ stores all custom variables in each separate yml file.
#
# Variables can not only be used to display information, but because you can write your own full
# code in JavaScript to display them, they can also do whatever you would wish for your
# players/server, such as sneaking in code to send sounds or spawn monsters.
#
# Coding this variable requires a little bit of JavaScript knowledge, see the link below.
#
# For documentation and help, please see this link:
# https://github.com/kangarko/ChatControl-Red/wiki/JavaScript-Variables
# -------------------------------------------------------------------------------------------------

# Where should this variable be used?
#
# FORMAT = used in your formats with {syntax}, players cannot use it
# MESSAGE = players can use it with [syntax] in their chat messages
Type: message

# The key we look for in the chat surrounded by [] brackets, example:
# chat message: "Hello everyone, I have an [item] in my hand" if your key is equal to "item"
Key: killer_item

# The value the key will be replaced to. This uses JavaScript.
Value: |-
    
    // A valid JavaScript code follows below. You can use the "player" variable to get
    // Bukkit's player instance. 
    itemDisplayName();
    
    function itemDisplayName() {
        var item = player.getInventory().getItemInHand();
    
        // Change these three variables to alter the color of the killer item and what name
        // shall we use if killer had no item
        var textColor = '&a';
        var bracketColor = '&f';
        var airName = 'fists';
    
        if (item.hasItemMeta() && item.getItemMeta().hasDisplayName()) {
            var itemName = player.getInventory().getItemInHand().getItemMeta().getDisplayName();
    
            if (itemName == "custom-name-1")
                return "&#084cfbb&#195dfbi&#296dfbr&#3a7efcd&#4a8ffcf&#5ba0fcl&#6bb0fco&#7cc1fcp&#8cd2fdc&#9de2fdo&#adf3fdm";

            return bracketColor + '[' + textColor + itemName + bracketColor + ']';
    
        } else {
            var wordUtils = Java.type("org.apache.commons.lang.WordUtils");
    
            var itemMaterial = player.getInventory().getItemInHand().getType().name();
            var itemDefaultName = wordUtils.capitalizeFully(itemMaterial.equals("AIR") || itemMaterial.contains("_AIR") ? airName : itemMaterial.replaceAll('_', ' '));
    
            return bracketColor + '[' + textColor + itemDefaultName + bracketColor + ']';
        }
    }

# What JavaScript condition must return true for this variable to show?
# You can put variables in here to get replaced.
Sender_Condition: ''

# What permission must the message sender have in order for this variable to display to him?
Sender_Permission: ''

# See Sender_Condition, except that we evaluate the JavaScript for each chat message receiver
# and only show the message to those receivers for which the condition returns true.
Receiver_Condition: ''

# What permission must the message receiver have in order for this variable to display to them?
Receiver_Permission: ''

# What texts should be displayed when we hover the mouse
# over this variable in the chat
Hover: []

# What ItemStack should be displayed when we hover the mouse over this variable in the chat
Hover_Item: player.getItemInHand()

# What website URL should be opened when we click with the mouse
# on this variable in the chat
Open_Url: ''

# What command should appear in the player command box on his screen
# if he clicks on this variable in the chat
Suggest_Command: ''

# What command should run as the sender when he clicks the mouse on this variable?
# Minecraft only supports 1 command!
Run_Command: ''

```
