### ISSUE TITLE
[Question] Discord format

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#225]
When I type from discord this shows in-game: 
![image](https://user-images.githubusercontent.com/5664135/101094451-b616bf80-35bc-11eb-832c-5d3caabd381d.png)

I watched the tutorial https://www.youtube.com/watch?v=8i3vaE6byxY but I don't seem to understand/see what I can do about this when I don't use placeholders from ChatControl.

**Comment by broken1arrow** [comment]
> When I type from discord this shows in-game:
> ![image](https://user-images.githubusercontent.com/5664135/101094451-b616bf80-35bc-11eb-832c-5d3caabd381d.png)
> 
> I watched the tutorial https://www.youtube.com/watch?v=8i3vaE6byxY but I don't seem to understand/see what I can do about this when I don't use placeholders from ChatControl.

You cant use placeholders if it send from DC (because is the console some send it in game) and console do not know ho is the in game player.

**Comment by Sikatsu** [comment]
That makes sense, but how would I use a different placeholder for messages from discord?

```
  discord-prefix:
    Message: '#7289da[Discord] &f'
    Sender_Condition: '{sender_is_discord}'
    Hover:
    - '&6Join onze discord via discord.villagercraft.nl'
```

```
  prefix:
    Message: '{itags_display}{pl_prefix}{cmi_user_display_name}&f: '
    Hover:
    - '&7+-+ &3{player} &7| &bCreative &7+-+'
    - '&6| &7Speelt sinds: &3{player_first_join_date}'
    - '&6| &7Speeltijd: &3{statistic_hours_played} uren'
    - '&6| &7Aantal plots: &3{plotsquared_plot_count}'
    - ''
    - '&6Klik om mij een bericht te sturen!'
    Suggest_Command: '/w '
```

**Comment by broken1arrow** [comment]
> That makes sense, but how would I use a different placeholder for messages from discord?
> 
> ```
>   discord-prefix:
>     Message: '#7289da[Discord] &f'
>     Sender_Condition: '{sender_is_discord}'
>     Hover:
>     - '&6Join onze discord via discord.villagercraft.nl'
> ```
> 
> ```
>   prefix:
>     Message: '{itags_display}{pl_prefix}{cmi_user_display_name}&f: '
>     Hover:
>     - '&7+-+ &3{player} &7| &bCreative &7+-+'
>     - '&6| &7Speelt sinds: &3{player_first_join_date}'
>     - '&6| &7Speeltijd: &3{statistic_hours_played} uren'
>     - '&6| &7Aantal plots: &3{plotsquared_plot_count}'
>     - ''
>     - '&6Klik om mij een bericht te sturen!'
>     Suggest_Command: '/w '
> ```

I can be wrong, but when I test it seam like work like this. 

Because I only need one true in discord, cc do the job to send it to discord (so placeholders work from ingame to discord). I set perms for parts discord shall not use (he cant bypass this ether).
````
DiscordChatChannelDiscordToMinecraft: true
DiscordChatChannelMinecraftToDiscord: false

````

**Comment by Sikatsu** [comment]
For me from in-game to discord works fine, but discord to in-game doesn't as it shows these placeholders though

**Comment by broken1arrow** [comment]
> For me from in-game to discord works fine, but discord to in-game doesn't as it shows these placeholders though

yes, is because it is discord some send the msg and I think CC not hock to the msg when discord send (even if player are linked).

I see this a good thing, I have problems when a player rename on discord to broken and send ingame as normal msg as me (was not good players get spammed in my name (my ingame name is broken_arrow1 ). I have not test for long time if the bug still exist, but I think it was cmi some course this.

**Comment by Sikatsu** [comment]
Hmm I see, only staff can chat from discord to in-game though in my case. But there must be a way that discord > in-game uses just a normal placeholder rather then the same we use in-game?

**Comment by broken1arrow** [comment]
> Hmm I see, only staff can chat from discord to in-game though in my case. But there must be a way that discord > in-game uses just a normal placeholder rather then the same we use in-game?

Yes it is probably some way, but seems to be a fairly unsafe method. When it is only triggered by certain parts of the name, I do not really know which plugin was the problem, but it used ingame placeholders and my ingame name (would have been better in that case it used the UUID in some way).

I try on discordSrv support what the error is and they complained about cmi even though I turned off so cmi would not listen to discordsrv.

**Comment by kangarko** [comment]
Right now you can use a system like this:

```yaml
mc-name: 
    Message: "{itags_display}{pl_prefix}{cmi_user_display_name}"
    Sender_Condition: "!{sender_is_discord}"

discord-name: 
    Message: "{player_name}"
    Sender_Condition: "{sender_is_discord}"
```

You see what I did there? I just negated the condition and created two format parts, one is for Discord and the other one is for Minecraft.

I hope that helps! Thanks everyone for being so helpful <3

**Comment by kangarko** [comment]
Some explanation: We cannot parse player-related variables when your message is coming from Discord since they require a player instance.

You can also use a separate Discord format using the channel's Discord_Format option to have another chat outlook for those messages that come from Discord.

**Comment by Sikatsu** [comment]
Thanks, this works perfectly fine for what I need! ^^

**Comment by lukaplayz** [comment]
> Some explanation: We cannot parse player-related variables when your message is coming from Discord since they require a player instance.
> 
> You can also use a separate Discord format using the channel's Discord_Format option to have another chat outlook for those messages that come from Discord.

Which section of config do we put it in

**Comment by ElBananaa** [comment]
> > Some explanation: We cannot parse player-related variables when your message is coming from Discord since they require a player instance.
> > You can also use a separate Discord format using the channel's Discord_Format option to have another chat outlook for those messages that come from Discord.
> 
> Which section of config do we put it in

Hey!
It's in your settings file, under the channel list. Here's an example:
```yaml
  List:
    general:
      Format: general-chat
      Format_Spy: none
    staffchat:
      Format: staff-chat
      Format_Spy: none
      Format_Discord : '&7『&c&lDISCORD&7』{player_prefix} &r{player} &8&l» &r{message}'
      Format_Console: '&7『&c&lSTAFFCHAT&7』{player_prefix} &r{player} &8&l» &r{message}'
```
