### ISSUE TITLE
Formats screwing up empty string

### ISSUE THREAD

**Issue by Teslicek** [kangarko/ChatControl#2251]
### "/version ChatControlRed" - plugin version

10.16.3

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Information about the issue/bug

This was not happening when I was using version 10.14.1

```
Parts:
  store:
    Message:
    - ''
    - '&r  &#ffff00&lSTORE'
    - '&r   &#ffff00↪ &7Support us by buying a rank and get access to special'
    - '&r    &#ffff00↪ &7perks, such as &e/hat&7, &e/craft&7, &e/itemname &7and more!'
    - ''
    - '&r  &#ffff00&l/store&7 ➡ &f&nstore.lifestealsmp.com&r'
    - ''
    Hover:
    - '&eClick to open the link'
    Open_Url: https://store.lifestealsmp.com
```
![image](https://user-images.githubusercontent.com/87967222/211100809-c69347f4-6744-4e24-809d-949c481b2c9e.png)
