### ISSUE TITLE
/ignore command

### ISSUE THREAD

**Issue by Sh3r1ffCZ** [kangarko/ChatControl#2286]
### Summary

Hello, could an option be added for players to enter /ignore nick and not see messages from that person from then on? This feature is pretty popular and searchable, I think it would be a cool new feature.

Next, a good command:
/ignorelist (List all ignored people)

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

A lot of players sometimes want to be away from some players they don't like very much. That's why I think it would be great.

**Comment by ElBananaa** [comment]
This feature is already available, please simply read the settings file (comments are there to be read) ^^
```yaml
# -------------------------------------------------------------------------------------------------
# Ability to ignore chat and private messages from certain players.
# -------------------------------------------------------------------------------------------------
Ignore:
  
  # Should we enable this feature
  Enabled: false
  
  # true = hide messages from players you ignore or if they ignore you, and disallow PMing players
  #        that you ignore (useful to prevent trolling)
  # false = only hide messages from players you ignore
  Bidirectional: false
  
  # The commands that invoke the ignore feature.
  # EDIT AS YOU WISH BUT THERE MUST BE AT LEAST ONE ALIAS
  Command_Aliases: [ignore, ig]
  
  # Hide chat messages from ignored players?
  Hide_Chat: true

  # Prevent players you ignore from private messaging you?
  Stop_Private_Messages: true
```
