### ISSUE TITLE
1.19.3: Tab-completion in /msg uses nickname instead of ign

### ISSUE THREAD

**Issue by HorusApl** [kangarko/ChatControl#2300]
### "/version ChatControlRed" - plugin version

10.16.15

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

![image](https://user-images.githubusercontent.com/64336395/220854488-6b8c5941-f6e2-4007-8703-6a8ed1dbde8f.png)
All player names when using /msg are being replaced by their nick, while this would be a nice feature it results in not being able to msg them at all if you follow the tab complete. My full ign is Horus_Apl, but as you see from the photo it only appears as my nick. Regular tab complete for any other command appears to be fine.

**Comment by kangarko** [comment]
Sorry for the delay, revieweing in 24 hours

**Comment by kangarko** [comment]
Sorry for the big delay, I forgot to keep a track of this ticket. I can add a toggle to disable this feature if you want?

**Comment by HorusApl** [comment]
Yeah it'd be great if you could msg the nick so /msg Horus can be a valid command vs using my ign. Or just remove the nicks from the tab complete, I'm happy for either

**Comment by kangarko** [comment]
Sure, just set Tab_Complete.Use_Nicknames to false in the current version and it will only show real names :)

**Comment by HorusApl** [comment]
I would love to use nicknames, this functionality doesn't appear to function though. If I type /msg Horus, it will say Horus is an invalid player. I do use Essentials for nicks, so I'm assuming that is why. Any way to have that work?

**Comment by HorusApl** [comment]
As well, the disable doesn't appear to be working. I have it disabled:

```
Tab_Complete:
  
  # Enable this feature?
  Enabled: false
  
  # Use nicknames rather than real names in tab completion?
  Use_Nicknames: false
  
  # Prevent completions for words shorter that the given amount of letters.
  # **On Minecraft older than 1.13 this only works properly on the first command argument.**
  Prevent_If_Below_Length: 0
  
```
  
![image](https://user-images.githubusercontent.com/64336395/226093899-abf7e117-9878-4ff1-96c0-dc814b67bdbf.png)
