### ISSUE TITLE
1.19.2: URL link in format files - Do they require "open_url"

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#2302]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

This is regarding format files.
If I had a format MOTD file like this
```yml
Parts:
  everything:
    Message:
    - '<center>&fWelcome &b%player%&f! Make sure to &b/vote'
    - ''
    - ' &bᴅɪsᴄᴏʀᴅ:&f discord.example.net'
    - ' &bsʜᴏᴘ:&f shop.example.net'
    - ' &bᴠᴏᴛᴇ:&f Type /vote in chat'
    - ''
```
While these links work in other parts of the plugin if it comes from a format file as shown above, the links cannot be clicked on.

Is this just a technical limitation of format files, which requires [open_url](https://github.com/kangarko/ChatControl-Red-Src/blob/master/src/main/resources/formats/ad-info.yml) for links to work or is this something that can change?

**Comment by kangarko** [comment]
I believe it's a technical limitation, unfortunately. Could you try splitting the format like this?

```
Parts:
  everything:
    Message:
    - '<center>&fWelcome &b%player%&f! Make sure to &b/vote'
    - ''
    - ' &bᴅɪsᴄᴏʀᴅ:&f '
  another-part:
    Message: 'discord.example.net'
  third-part:
    Message:
    - ' &bsʜᴏᴘ:&f shop.example.net'
    - ' &bᴠᴏᴛᴇ:&f Type /vote in chat'
```
