### ISSUE TITLE
[Issue] Hover over private message shows wrong sender

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#233]
It should say Bearly_Awake_, the sender of the private message. Instead it shows the receiver as the sender.

![image](https://user-images.githubusercontent.com/5664135/101243244-24639b00-36ff-11eb-8a54-85330a3ff41d.png)

The other way around works, the receiver is being shown as receiver. In both cases the {player} placeholder is being used.

Works:
```
Parts:
  Everything:
    Message: '&6[&eIk &6-> &e{receiver}&6]&6 {message}'
    Hover:
    - '&3&lPrivebericht'
    - '&8&oVerstuurd {timestamp}'
    - '&7Ontvanger: &3{player}'
    Suggest_Command: '/tell {player} '
```

Doesn't work:
```
Parts:
  Everything:
    Message: '&6[&e{sender} &6-> &eIk&6]&6 {message}'
    Hover:
    - '&3&lPrivebericht'
    - '&8&oOntvangen {timestamp}'
    - '&7Afkomst: &3{player}'
    - ''
    - '&6Klik om te reageren!'
    Suggest_Command: '/r '
```

Minecraft: 1.16.4 Tuinity
MySQL: true
Bunege: true
