### ISSUE TITLE
1.19.4 BungeeControl-Red Cannot execute FORWARD_COMMAND

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl#2338]
### "/version ChatControlRed" - plugin version

ChatControlRed version 10.17.8 up to 10.18.2

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Information about the issue/bug

When a player swears, points are given etc, the settings file can execute something like:
```yaml
Warning_Points:
  Sets:
    swear:
      2:
      - 'bungeeconsole bungee tempmute {player} 5m Swearing is prohibited
```
BungeeControl-Red then gives this error and the command is not executed
```
[BungeeControl-Red] Cannot execute FORWARD_COMMAND because the sender of the command (PlayerABC123) lacks 'chatcontrol.command.forward' permission.
```
I can't remember having to give the player this permission as this command should be executed by the console.
