### ISSUE TITLE
Better sound notifications

### ISSUE THREAD

**Issue by Dusreza** [kangarko/ChatControl#2344]
### Summary

Dear Support Team,

I hope this message finds you well. I am writing to suggest a new feature that could be added to the ChatControlRed plugin. Specifically, I think it would be helpful to have the ability to play a sound for everyone in a channel. This feature would be particularly useful for places like staff chats where important announcements need to be made quickly and efficiently.

I believe this feature would greatly enhance the functionality of the ChatControlRed plugin and make it an even more valuable tool for managing and moderating channels. I would love to hear your thoughts on this suggestion and whether it is something that could be implemented in the near future.

Thank you for your time and consideration, and I look forward to hearing back from you soon.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

1. Missed Notifications: Without this feature, important announcements or messages might go unnoticed if users are not actively looking at the chat window. This could lead to missed opportunities or critical information being overlooked.

2. Inefficient Communication: If users need to constantly check the chat window to stay up to date, it can be time-consuming and inefficient. Having the ability to play a sound notification would ensure that important messages are delivered to everyone in a timely and effective manner.

3. Staff Chat Issues: In staff chats, where quick communication is essential, not having a sound notification feature could lead to misunderstandings or miscommunications. For example, if a staff member sends an urgent message, but the other staff members are not actively monitoring the chat, they may not see the message in time to take action.

Overall, having the ability to play a sound for all inside of a channel would improve communication efficiency and ensure that important messages are delivered promptly and effectively.

**Comment by kangarko** [comment]
@Dusreza sure, is it enough if I add "/chc announce sound" command that will play a sound to all players or those in a channel?

**Comment by Dusreza** [comment]
You could do that, but I think you should also add a channel option in settings.yml called ''-announce (sound)'' as I'd want every message in my staffchat to make a sound, even if its through discord :)

**Comment by TheIntolerant** [comment]
> @Dusreza sure, is it enough if I add "/chc announce sound" command that will play a sound to all players or those in a channel?

I think adding a sound option under the "Channel options:" part of the settings is what this person is wanting.

For example anyone who is reading/writing in a specific channel with the "sound" option added, will hear a sound every time a message is sent

So for example the default setting could have something like this
```yml
  List: 
    standard: 
      Format: chat
      Format_Spy: "@noprefix chat"
    admin: 
      Format: admin-chat
      Format_Console: '[A-chat {player}] {message}'
    global: 
      Format: global-chat
    ranged: 
      Format: "&6[ranged] &7{pl_prefix+}{player}:{pl_suffix} {chat_color}{chat_decoration}{message}" 
      Range: 100 
      Bungee: false
    towny: 
      Format: chat
      Sound: ENTITY_CHICKEN_EGG 1F 1.5F 
      Party: towny-town
    helpop:
      Format: helpop
```
So anyone who gets a message from the twony channel, hears that sound you set
