### ISSUE TITLE
[Question] Showing Variables Through Read Channels

### ISSUE THREAD

**Issue by iwentafk** [kangarko/ChatControl#236]
Minecraft Version: 1.14.4
MySQL: false
BungeeCord: false

Is there a way to make a specific prefix to get called when someone reads a channel?

To put it in retrospect, I want my players that aren't inside my "global" channel, that have it on read, for the chat format to change to something else, so currently it would produce "(Member) Username: Hey, how's it going?" when they're inside the "global" channel. I want it so when they leave the channel to produce "(/ch j global) (Member) Username: Hey, how's it going" that way my players know they're not in the global channel, and they see the command to join it, once they join it, it goes back to the original format of "(Member) Username: some message"

This would be helpful to me cause it just gives a more understandable aspect to the server.

Thanks!

**Comment by kangarko** [comment]
Good, starting the next version you can use the following script for Sender_Condition and Receiver_Conditions:

```
  # Show the [Read] prefix if the receiver is only reading this channel.
  read-prefix:
    Message: '&8[&bRead&8] '
    Receiver_Condition: '''{player_channel_mode_{channel}}'' == ''read'''
```
