### ISSUE TITLE
join.rs does not work after changes

### ISSUE THREAD

**Issue by Timoti11** [kangarko/ChatControl#2403]
### "/version ChatControlRed" - plugin version

10.19.4

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/1dec49c140f04804b94d62a9056c534c

### "/chc debug" output (strongly recommended)

"/chc debug" - https://ufile.io/cf9qhkny
https://paste.gg/p/anonymous/1dec49c140f04804b94d62a9056c534c - proxy log
https://paste.gg/p/anonymous/0cd57c11fac04387ad063bc6e89c639a - lobby log

### Information about the issue/bug

After a clean installation of the bungee plugin there is a message about quit and login, after trying to change anything in join.rs the message stops appearing, even if you return everything as it was after installation.

```
Messages:
  Apply_On: [JOIN, QUIT, SWITCH]
  Ignored_Servers:
    - "silent_server"
  Stop_On_First_Match: false
  Prefix: {}
  Defer_Join_Message_By: 1 tick

```
