### ISSUE TITLE
1.20.1: Question / problem with chc not sending message in standard, so the prefix doesn't shows up, like on my other servers.

### ISSUE THREAD

**Issue by CtrlAiDel** [kangarko/ChatControl#2416]
### Are you using MySQL?

No

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

Hi everyone, i have a problem with prefixes on one of my server. 

All the others sub server are working. CHC is up to date(ChatControl-Red-10.19.8.jar). Velocity control is updated too.
Paper is updated to 1.20.1: version 100

![chat scrap](https://github.com/kangarko/ChatControl-Red/assets/40178706/16fe583f-6321-469e-b32a-04a8a74a1739)
This is what it looks like

![ch list TC](https://github.com/kangarko/ChatControl-Red/assets/40178706/69950f17-cb39-4e6c-8db1-7e27bfba3d74)
[debug TC.zip](https://github.com/kangarko/ChatControl-Red/files/12243462/debug.TC.zip)
This is the /ch list on the server where it's working + the debug

![ch list TC hardcore](https://github.com/kangarko/ChatControl-Red/assets/40178706/72a536f6-eeda-4252-a261-0242849b22cc)
[debug Hardcore.zip](https://github.com/kangarko/ChatControl-Red/files/12243464/debug.Hardcore.zip)
And the same for the server where it's not working

These are the same permissions that I am using on both servers:
![257003433-1f885ecf-99f1-4e02-a9b0-98e4dec86de0](https://github.com/kangarko/ChatControl-Red/assets/40178706/7419e915-2fa5-4b20-8f19-af252af0d819)
![257003434-827de0c6-7043-4046-ba19-6bf349191f86](https://github.com/kangarko/ChatControl-Red/assets/40178706/d8498410-2d0a-488d-b0bb-a7772e63a585)
![257003435-8f7aa705-d6a6-4c22-847d-e210f43e0755](https://github.com/kangarko/ChatControl-Red/assets/40178706/4f3fd6ba-ef1e-4f96-ad09-648b49453166)

This is what it should look like with prefix: 
![image](https://github.com/kangarko/ChatControl-Red/assets/40178706/7930e1ad-a6f4-4f37-b596-3e3c620f6850)

I hope it's more precise this time, i have a broken arm right now.

Please help me fix this weird problem :S ! Thank you

**Comment by CtrlAiDel** [comment]
We just found out a part of the problem. The prefix seems to be working, the problem is the fact that my message aren't being sent in standard.

I've tried the command /ch sendas username standard message

and this is popping up
![image](https://github.com/kangarko/ChatControl-Red/assets/40178706/9e1b035b-ba34-4bee-8104-77928256bdc9)

I'll get back a bit to the wiki, but could you please direct me a little be too ? Thank you sir.

**Comment by Izocel** [comment]
To resume:
- `/ch sendas {username} {channel} I'm a teapot` --> Works fine with prefixes and is sent to the channel

![image](https://github.com/kangarko/ChatControl-Red/assets/68454661/0b158dc8-197f-4e91-a452-53e857856bd6)

- regular chat message --> No prefix, is the problem the message not going into channel ?

![image](https://github.com/kangarko/ChatControl-Red/assets/68454661/88805253-8c63-4a2b-adbf-83330fe6b238)

**Comment by kangarko** [comment]
Thanks for reporting. I had to leave office, will be getting back on you in 2-3 days max.

**Comment by CtrlAiDel** [comment]
Thank you for your help, no rush. I'll wait for a feedback!

**Comment by CtrlAiDel** [comment]
Last information:
![image](https://github.com/kangarko/ChatControl-Red/assets/40178706/458eed9e-41e9-46dd-918e-17275991ce40)

I can see that i am sending message in standard when I look into the console(normal chat), I have also tried to switch to global write, it does change to global into the console, but still no prefix in game

thank you matej no rush take your time. I'll hit you up in a few days if you haven't

**Comment by kangarko** [comment]
Hey, I am back, I have read through the ticket multiple times because I could not reproduce the bug, but I saw you don't use MySQL while you have VelocityControl - could you enable MySQL for me please? We store channel data over database but the plugin was originally not designed not to be used with MySQL with Velocity/Bungee, it might be a bug there

**Comment by kangarko** [comment]
Also please try on 10.19.10

**Comment by CtrlAiDel** [comment]
Hi Kangarko. I did update on all my server to 10.19.10. No issue except for the "hardcore", the same issue is happening.

I already had Mysql activated. (in CHC).
I turned it off and tried it back, so now it's back on.

I've check in Velocity Control if there was an mysql option but it doesn't seems.

So why do you think mysql was off, if it's on on my side. 
PS: When mysql is on I can join other channel, and when it's off I cannot, so it tells me it works, so again, I really don't know where and why in my logs you think I don't have mysql turn on :) 

You can contact me anytime on discord @WeConnected .

Thanks for the support sorry to be a problem right now!

**Comment by CtrlAiDel** [comment]
I've tried to load CHC & LuckPerms only, without any other plugins and that didn't help. Same behavior.

**Comment by kangarko** [comment]
Sorry for the time it takes. I still can't reproduce.

Just to be clear that I understand you properly > the prefix won't show when you type /ch sendas, but it works when you just chat?

![a](https://i.imgur.com/GNKxV9y.png)

Works for me on both chat and /ch sendas.

Did you try with Vault plugin installed? We need Vault to properly get the prefix from LuckPerms.

**Comment by kangarko** [comment]
Also, make sure you do not have the same chat format assigned to more than one channel. You had both standard and global use the "chat" format. Duplicate it for the global channel.

Next, I simplified your chat format a bit, try using this:

```yaml
Parts:
  icon-delete-chat:
    Message: '&8[&4X&8] &f'
    Hover: '&cRemove this message from chat for all players.'
    Run_Command: /{label} internal remove {message_uuid}
    Receiver_Permission: chatcontrol.removemessages
  prefix-read:
    Message: '&8[&bRead&8] '
    Receiver_Condition: '''{player_channel_mode_{channel}}'' == ''read'''
  prefix-luckperms:
    Message: '{player_prefix+}'
    Hover:
    - '&7{player_prefix+}&f{player_name} {player_suffix}'
    - '&7Ping&8: &f{ping}ms'
    - '&7Rank&8: &f{player_group}'
    - '&7Posted: &f{timestamp}'
    - ''
    - '&7Click to learn more about ranks.'
    Open_Url: https://mineacademy.org/project-orion
  player:
    Message: '&f{player_nick}'
    Hover: '&7Cliquer sur le nom pour DM.'
    Suggest_Command: '/tell {player_name} '
  player-message:
    Sender_Permission: group.default
    Message: '&7: {player_suffix}&e{message}'
```
