### ISSUE TITLE
1.20.1: Bungee discord for the servers that do not have discordSRV installed

### ISSUE THREAD

**Issue by SpectreVoid** [kangarko/ChatControl#2429]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

Hey, so I have a waterfall/paper 1.20.1 network. I am having trouble setting up the DiscordSRV using the bungee forward method on the servers that do not have the discordSRV installed. 

My lobby server (without DiscordSRV-related config)

````
standard:
  Format: chat
  Format_Spy: '@noprefix chat'
  Bungee: true
      
Discord: 
  Enabled: false
  Filter_Chat: true
  Remove_Emojis: true
  Webhook: false
  Send_Messages_As_Bot: true
  Forward_From_Bungee: false
````

And the config for my survival server with the discordSRV installed. (It works on this server, but not the other ones that have the same settings as the lobby)

````
standard:
  Format: chat
  Format_Spy: '@noprefix chat'
  Bungee: true
  Discord_Channel_Id: 1140759262906286171
      
Discord:
  Enabled: true
  Filter_Chat: false
  Remove_Emojis: true
  Webhook: true
  Send_Messages_As_Bot: false
  Forward_From_Bungee: true
````

In summary, the discordSRV works on the survival server, but the 'Forward_From_Bungee' doesn't seem to register. Not sure if it is my config that is incorrect, or what? Let me know if you need more information. Edit: Yes bungee chat works in the standard channel all over, no trouble there.
