### ISSUE TITLE
[Question] Bold color stays on other lines

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#245]
It should only be on the first line (the title), but also spreads on the other lines. Not sure if this is an issue, or if I should do it differently?

![image](https://user-images.githubusercontent.com/5664135/101346804-6882a700-3889-11eb-94f9-cfd62961ad6b.png)

```
Parts:
  Everything:
    Message: '&6[&e{sender} &6-> &eIk&6]&6 {message}'
    Hover:
    - '&3&lPrivebericht'
    - '&8&oOntvangen {timestamp}'
    - '&7Afkomst: &3{sender}'
    - ''
    - '&6Klik om te reageren!'
    Suggest_Command: '/r '
```
