### ISSUE TITLE
1.18.2 /me not respecting color permissions, players able to bypass and use whatever formatting they want

### ISSUE THREAD

**Issue by TomLewis** [kangarko/ChatControl#2463]
### "/version ChatControlRed" - plugin version

10.20.2

### Are you using MySQL?

Yes

### Are you using BungeeCord?

Yes

### Information about the issue/bug

Im not on the latest version of chatcontrol so maybe this has already been fixed, but I just accidentally found out but any player can use /me &bColor codes to bypass and spam chat with any colors
Even when they dont have permission for any colors in chat

**Comment by kangarko** [comment]
Can't reproduce:

![a](https://i.imgur.com/MBfvn0V.png)

Assuming OP gives all perms and non-OP takes all. Must be a permission issue somewhere on your end, sorry. My nonOP has these:

```
default:
  permissions:
  - cowcannon.command.cow
  - cowcannon.cow.use
  - chatcontrol.command
  - chatcontrol.command.tell
  - chatcontrol.command.me
```

Check if players that should not, have some of these perms:

![b](https://i.imgur.com/7DkBWrM.png)

**Comment by TomLewis** [comment]
Oh its not permissions this is the first thing I searched for. The permissions for color should be global to the plugin right? They are blocked elsewhere in the plugin, just not `/me`
did you test with this specific version of Chat Control? Im using 10.20.2 atm.

Its definitely running via ChatControl as its the formatting I set in ChatControl.

So unless somehow its displaying the /me via ChatControl but either CMI or Essentials is taking over permission of the colors for it?

**Comment by kangarko** [comment]
Can you please test with 10.21.10?

Correct observation, can you double check if you don't have EssentialsX/CMI permissions there, just in case? Not sure how that would interfere except if they listened to the command event which lets them modify the message, although it's unlikely.

**Comment by TomLewis** [comment]
I'm now using the latest chat control red and this is still an issue.

**Comment by kangarko** [comment]
Try embedding the format in settings.yml:

![a](https://i.imgur.com/jkS5CH6.png)

I still reproduce with/without OP:

![b](https://i.imgur.com/8uO1w5R.png)

Give explicit negative -chatcontrol.use.color.me to those players who cant use it in /me and it will block all. Debug with your perm plugin if the issue persists please.

**Comment by kangarko** [comment]
Here is my permission setup to prevent /me color use:

![a](https://i.imgur.com/muZYAoP.png)

**Comment by TomLewis** [comment]
```
- chatcontrol.use.color.me:
    world: PirateCraft_1
    value: false
```
    
Does nothing, so its not being inherited, if you want I can do a luckperms verbose to double check?

I already have a format set for /me that forces color
```
# -------------------------------------------------------------------------------------------------
# A /me is a command allowing you to broadcast your message in a different way then chat.
# -------------------------------------------------------------------------------------------------
Me:

  # Should we enable this feature?
  Enabled: true
  
  # What commands will invoke the me feature?
  # EDIT AS YOU WISH BUT THERE MUST BE AT LEAST ONE ALIAS
  Command_Aliases:
  - 'me'
  
  # The format used in the command. You can type the format here or reference to one in formats/.
  Format: me
```

me.yml
```
# -----------------------------------------------------------------------------------------
# Represents a chat format file that can be used to stylize messages.
# See the chat.yml for a tutorial on how this works.
# -----------------------------------------------------------------------------------------

# The parts of this format.
Parts:
  Normal:
    Message: '&d►&r '
  Player:
    Message: '{pl_prefix}{nick}'
    Suggest_Command: '/me {player} '
  Suffix:
    Message: '{pl_suffix} '
  The_Rest:
    Message: '&5&o{message}'
    Hover:
    - '&6Describes an action in the context of the pirate.'
 ```
