### ISSUE TITLE
formats Message newline

### ISSUE THREAD

**Issue by BearLeonLight** [kangarko/ChatControl#2499]
### Summary

I haven't been able to find the answer after trying and searching the WIKI, so I hope this function can be improved.

I wish there was a built-in placeholder <newline> or similar that would force the text to newline.

### What would happen if we didn't implement this feature? Why not having this feature is a problem?

When I want the player to see different or more messages based on conditions, if the previous line is not long enough, they will be connected together. I have tried using \n and an error will be displayed. I don't have any solution.

```yaml
Parts:
  # See the chat.yml format file for a tutorial on how this works.
  everything:
    Message:
    - '&8*--------------------------------------------------*'
    - '&fTest'
    - ''
    - '&6Version: &f{nms_version}'
    - '&6Changelog:'
    - '&7- &fAdded ChatControl Red plugin.'
    - ''
    - '&6Help &7- &f/help &6Settings &7- &f/menu &6Web &7- &f/web'
    - '&8*---------------------------------------------------*'
  discord-invite:
    Message:
    - '&8[&9Discord&8] &f'
    Receiver_Permission: group.1-player
    Hover: '&bJoin Discord'
    Open_Url: https://invite.XXX.com/
```
![image](https://github.com/kangarko/ChatControl-Red/assets/52900334/688fc497-bea0-441d-9699-0f4b24db6f7d)
