### ISSUE TITLE
Velocity 1.20.2: Trials and Tribulations of Cross-Server Chat

### ISSUE THREAD

**Issue by JerichoTorrent** [kangarko/ChatControl#2509]
### "/version ChatControlRed" - plugin version

10.22.5

### Are you using MySQL?

Yes

### "/chc debug" output (strongly recommended)

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/13710831/debug.zip)

### Information about the issue/bug

I use VelocityControl on the proxy (Velocity 1.20.2) and ChatControl Red 10.22.5 on my 3 1.20.2 backend servers. I provided a debug from one backend. My issue is twofold.
1. I can't find either in the wiki, discord, or through my trial and error a tried and true method to enable cross-server chat in my global channel. I have my settings.yml channels list written as follows:
```
  List:
    Survival:
      Format: chat
      Format_Spy: '@noprefix chat'
      Discord_Channel_Id: 1100905925507817533
      Format_Discord: none
    Global:
      Format: global-chat
      Discord_Channel_Id: 1182819310574518393
      Bungee: true
    Admin:
      Format: admin-chat
      Format_Console: '[Admin-chat {player}] {message}'
      Discord_Channel_Id: 1100917607642693672
      Bungee: true
      Format_Discord: none
    Ranged:
      Format: '&6[ranged] &7{pl_prefix+}{player}:{pl_suffix} {chat_color}{chat_decoration}{message}'
      Range: 100
      Bungee: false
    Staff:
      Format: staff
      Bungee: true
```
All 3 backends are formatted very similarly. The only differences are the "survival" channel is of course named differently on other servers and has different discord channel IDs. That's just context and not relevant. I also have the bungee.integration set to true. I assume the word "Bungee" can be substituted for Velocity, since I'm not seeing an official full-suite integration of Velocity into this plugin. No matter what I try I can't read messages from other servers even though I am in the global channel. Same thing for staff and admin channels.
2. I use VelocityControl as mentioned prior and I'm running into a couple issues. I have join and quit messages turned off on the backend in favor of VelocityControl's join, quit and switch messages which I like much more. However, sometimes VelocityControl misses a player joining. I'll see people chat without me seeing them having ever joined. I'll see people leave then see them still on the server, because VelocityControl missed when they joined back. Is there any help you can provide on how to set this up properly? It just seems like a lack of consistency with catching join and quit messages. Before it is asked, yes the server names in Velocity and VelocityControl are setup right.
Any clarity you can provide on both issues would be most appreciated.
