### ISSUE TITLE
1.20.1: MOTD Messages Not Separating Correctly Without Extra Empty Lines

### ISSUE THREAD

**Issue by Kaludii** [kangarko/ChatControl#2510]
### "/version ChatControlRed" - plugin version

10.23.0

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

Hello, our messages set for the MOTD are not starting on new lines as intended without added extra empty lines. if I add an extra line it works, but then there is an empty line which makes the MOTD look too long, and I'd like to just have each of the links in the MOTD on a new line rather than adding a new empty line. 1st image link is without an empty line, and 2nd image is with the empty line.
https://media.discordapp.net/attachments/755325303689052200/1186245957575245887/image.png?ex=65928ca3&is=658017a3&hm=e9cf185f51681267a42cee259cb153913564c9632d8b79fc0cfc7433e8eb00e7&=&format=webp&quality=lossless
https://media.discordapp.net/attachments/755325303689052200/1186366515746971758/image.png?ex=6592fcea&is=658087ea&hm=acdad276b358bff003018973beb3e694c2bf5e8483ead8ca25bd5196536abdc2&=&format=webp&quality=lossless

MOTD for 1st:
```
Parts:
  begin-motd:
    Message:
    - ''
    - '&7&m-----------------------------------------'
    - '&f&lWELCOME TO PROTECTORSCRAFT'
  website:
    Message:
    - 'WEBSITE: &fProtectorsCraft.us'
    Open_Url: http://ProtectorsCraft.us
    Hover: '&eClick to visit our website!'
  discord:
    Message:
    - 'DISCORD: &fProtectorsCraft.us/discord'
    Open_Url: http://ProtectorsCraft.us/discord
    Hover: '&eClick to join our Discord!'
```

MOTD for 2nd:
```
Parts:
  begin-motd:
    Message:
    - ''
    - '&7&m-----------------------------------------'
    - '&f&lWELCOME TO PROTECTORSCRAFT'
    - ''
  website:
    Message:
    - 'WEBSITE: &fProtectorsCraft.us'
    - ''
    Open_Url: "http://ProtectorsCraft.us"
    Hover: '&eClick to visit our website!'
  discord:
    Message:
    - 'DISCORD: &fProtectorsCraft.us/discord'
    Open_Url: "http://ProtectorsCraft.us/discord"
    Hover: '&eClick to join our Discord!'
    ```
