### ISSUE TITLE
1.20.1: DiscordSRV Discord to Minecraft Messages Show Player Name as Null When Not Online

### ISSUE THREAD

**Issue by Kaludii** [kangarko/ChatControl#2513]
### "/version ChatControlRed" - plugin version

10.23.1

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

Hello, my messages from discord to the server show a null error on my name, but it works fine when I'm in-game and try messaging on discord to the minecraft server. The first `From Discord` in the screenshot below is when I was logged on, and the second is the moment I left and tried. I'm able to hover over the name and see my information, it just shows null when I'm not online. How can I fix this?

Chat.yml:
```
  # Show the [Discord] prefix if the sender is from Discord (we use our own
  # special variable for this) and add some interactive elements.
  discord-prefix:
    Message: '&8[&3From Discord&8] &f'
    Sender_Condition: '{sender_is_discord}'
    Hover: '&bJoin our Discord at protectorscraft.us/discord'
    Open_Url: https://protectorscraft.us/discord
```

![image](https://github.com/kangarko/ChatControl-Red/assets/63890666/3e821335-357a-4c23-b374-5cf2a5849f71)

**Comment by kangarko** [comment]
Can you show me the relevant format part? The format part discord-prefix is printing [From Discord] and is working correctly, I need to see the next one printing that error.

**Comment by Kaludii** [comment]
> Can you show me the relevant format part? The format part discord-prefix is printing [From Discord] and is working correctly, I need to see the next one printing that error.

Hello, this is the format for my chat messages, is this what you were asking for?
```
  player-name:
    Message: '&r%essentials_nickname%'
    #Message: "{player_name}"
    #Gradient: RED - YELLOW
    Hover:
    - '&7%luckperms_prefix_element_highest_on_track_staff%%luckperms_prefix_element_highest_on_track_donator%&f%luckperms_prefix_element_highest_on_track_player%%eternaltags_tag% &r%essentials_nickname%'
    - ''


  alternative-player-name-owner:
    Message: '&#D700FFK&#AC30FFa&#8160FFl&#568FFFu&#2BBFFFd&#00EFFFi'
    Hover:
    - '&7%luckperms_prefix_element_highest_on_track_staff%%luckperms_prefix_element_highest_on_track_donator%&f%luckperms_prefix_element_highest_on_track_player%%eternaltags_tag% &r%essentials_nickname%'
    - ''
    - '&bUsername: &d%player_name%'
    - ''
    - '&8→ ᴄʟɪᴄᴋ ᴛᴏ ᴘʀɪᴠᴀᴛᴇ ᴍᴇssᴀɢᴇ.'
    Suggest_Command: '/whisper {player_name} '
    Sender_Condition: '''%luckperms_primary_group_name%'' == ''owner'''
    

prefix:
    Message: '%javascript_getPrefix% '
    Hover:
    - '&7%luckperms_prefix_element_highest_on_track_staff%%luckperms_prefix_element_highest_on_track_donator%&f%luckperms_prefix_element_highest_on_track_player%%eternaltags_tag% &r%essentials_nickname%'
    - ''
    
```

**Comment by Kaludii** [comment]
I also tried replacing the alternative-player-name-owner message with `{player_name}` and `{player_nick}`, but still same null error.

Same with player-name:
```
  player-name:
    Message: '&r{player_nick}'
```

**Comment by Kaludii** [comment]
Update: It seems like it is due to the `%javascript_getPrefix%` Javascript placeholder. It just shows the prefix based on donator/player ranks. Is there a way we can make another `prefix` section but it'll be only for showing the prefix for when a player messages from discord to in-game?

**Comment by kangarko** [comment]
Thanks for keeping me updated.

Yes, please create two format parts, one for discord and the other for normal players:

```
prefix-discord:
    Message: 'your prefix for discord users '
    Sender_Condition: '{sender_is_discord}'
prefix-normal:
    Message: '%javascript_getPrefix% '
    Sender_Condition: '!{sender_is_discord}'
    Hover:
    - '&7%luckperms_prefix_element_highest_on_track_staff%%luckperms_prefix_element_highest_on_track_donator%&f%luckperms_prefix_element_highest_on_track_player%%eternaltags_tag% &r%essentials_nickname%'
    - ''
```

Something like this. I haven't tested, please let me know if you'll encounter any errors with this.
