### ISSUE TITLE
1.20.1: Command arguments in chat

### ISSUE THREAD

**Issue by distribate** [kangarko/ChatControl#2518]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

I want to make it so that when a player clicks on a player's name in chat, a /tellraw command is triggered that outputs several actions with their possible events (for example: teleport to the player, send a private message, or trade items).

However, I ran into a problem that when writing the command, I need to take the player's name as an argument, {player_name} in formats/chat.yml.

Is this possible and how can I best make this feature?

command.rs:
```
match ^\/playerChatInteract
dont verbose
then console tellraw {player} [" ",{"text":"\n [Teleport]","color":"#C7C3FB","bold":"true","clickEvent":{"action":"run_command","value":"/tpa {player_name}"},"hoverEvent":{"action":"show_text","contents":["Teleport to {player_name}"]}},{"text":" [Message]","clickEvent":{"action":"suggest_command","value":"/msg {player_name}"},"hoverEvent":{"action":"show_text","contents":["Message to {player_name}"]}}]
then deny
```

chat.yml:
```
Parts:
  delete-chat:
    Message: '&7[X] &f'
    Hover: '&cIgnore'
    Run_Command: /ignore {player_name}
  spies-prefix:
    Message: '&8[&5Spy&8] &f'
    Receiver_Condition: '{player_is_spying_{channel}}'
    Hover: '&dClick to stop spying {channel} channel.'
    Run_Command: /{label_spy} toggle chat {channel}
  type_chat:
    Message: '{#fb0e0e}[near]'
    Hover:
    - '&fThis means that'
    - '&fmessages are visible to players'
    - '&fwithin a radius of 120 blocks.'
  First:
    Message: '%javascript_replaceGuildName%'
  player-name:
    Message: '{player_prefix}&#BEABF6{player_nick}&r{player_suffix}'
    Hover:
    - '&f{player_prefix}&#BEABF6{player_name}'
    - '&fPlays with %player_first_join_date%'
    - ' '
    - '{#00E375}Rating: &r%reputation_reputation%'
    - '{#00E375}Guild: &r%fc_player_guild_name%'
    - '{#00E375}Playtime: &f%cmi_user_playtime_hoursf% h'
    - ''
    - '&8[Click to interact]'
    Run_Command: /playerChatInteract {player_name}
```
