### ISSUE TITLE
1.20.2 - How to silent discord message on /toggle chat

### ISSUE THREAD

**Issue by nhanledev** [kangarko/ChatControl#2535]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - BungeeCord

### Question

When the player is ignoring the chat using `/toggle chat`, other players' messages are hidden BUT the message that sent from Discord doesn't.

I want to hide those messages from chat too, whenever the player is ignoring chat.

I have already try to set `Receiver_Condition` but it still print a blank line on chat, in the view of the player that is ignoring chat.

What is the correct way to hide chat from player that is ignoring chat?

```
  discord-prefix:
    Message: '&bDISCORD '
    Sender_Condition: '{sender_is_discord}'
    Receiver_Condition: '!{is_ignoring_chat}'
  discord-name:
    Message: '{name}'
    Sender_Condition: '{sender_is_discord}'
    Receiver_Condition: '!{is_ignoring_chat}'
  discord-message:
    Message: ': {message}'
    Sender_Condition: '{sender_is_discord}'
    Receiver_Condition: '!{is_ignoring_chat}'
    ```
