### ISSUE TITLE
PlaceholderAPI in chat formatting

### ISSUE THREAD

**Issue by InterStena** [kangarko/ChatControl#254]
I'm using ChatControl (Free version) for chat formatting. But I need some placeholders to be there. They're working in PlaceholderAPI but I don't know how to place them here:
```YAML
Chat:
  Formatter:
    Enabled: true
    Message_Format: '%pl_prefix%player%pl_suffix%message'
    Global_Message_Format: '%pl_prefix%player%pl_suffix%message'
    Spy_Message_Format: '&8SPY: [%world&8]&f %pl_prefix%player%pl_suffix %message'
```
If i place it here as `%player_gamemode%` it won't work. Same happens with `%player_gamemode`
