### ISSUE TITLE
1.20.1: Announcements `Type_V2` and `Type_V2_Network`

### ISSUE THREAD

**Issue by NoxNap** [kangarko/ChatControl#2541]
### "/version ChatControlRed" - plugin version

10.23.3

### Are you using MySQL?

No

### Are you using BungeeCord?

No

### Information about the issue/bug

`localization/messages_en.yml`
```yml
    Chat_Body:
    - '<center>&2&l{type}'
    - '<center>&f{lines}'
    - '{remaining_space}'
    Chat_Body_Line_Color: LIME
    Type_V2: ANNOUNCEMENT
    Type_V2_Network: NETWORK ANNOUNCEMENT
    Success_V2: Your announcement has been sent.
    Success_V2_Network: Your announcement was sent to the {0} server.
```
How do I get {type} to change based on whether it's `Type_V2:` or `Type_V2_Network:`. It seems to just default to the `Type_V2_Network` message. Alternatively, if this is intended behavior; how do I create another announcements message type based on whether `/chc announce <message>` or `/chc announce server:NAME <message>` is used?

**Comment by kangarko** [comment]
Hello,

We will automatically switch to Type_V2_Network when BungeeCord is enabled and use it at all times.

I dont understand your other question. The server:NAME parameter can be used with most announcement types. Or what did you mean?

**Comment by NoxNap** [comment]
I'll explain a bit more, sorry for the confusion;
I want to create two commands. `/announce <msg>` for the server it is run on, in this case, it's for a server called `compbending` and I want `/announce` to output TypeV2's header "ANNOUNCEMENT" since it is not a network announcement.

The other command I want to run is `/networkannounce <msg>` for the entire network, so I want it to run Type_V2_Network's header "NETWORK ANNOUNCEMENT"

The way I tried doing it is by using commands.yml and having the following commands run:
```yml
  announce:
  - chc announce chat $1- server:compbending
  networkannounce:
  - chc announce chat $1-
```
I expected the headers to change depending on whether the `server:NAME` parameter was used. It sounds like that's not what the TypeV2 settings are meant to do though.

My second question 
> how do I create another announcements message type based on whether /chc announce <message> or /chc announce server:NAME <message> is used?
is basically how I can have /chc announce output different formats. The only way I know how to modify the announcement messages is through `localization/messages_en.yml` under the `announce` settings; and if that's the only way then I guess you can only have one announcement format?

The only other idea I have is if I can create a `/formats/networkannounce.yml` and `/formats/serverannounce.yml`; I imagine I'd have to change how the commands.yml works?


Let me know if this clears up any confusion my original comment made.

**Comment by kangarko** [comment]
Hello,

Oh I see now, thanks for the explainer. Unfortunately the network vs non network headline in localization is hard-set depending on the bungeecord option.

If the bungee is on, we always use the network one. If it is off, we never use it. Hope that clarifies things better too.

Yes you can create a local Bukkit-only rule in rules/commands.rs that will broadcast a format. That way you can use whatever format you wish. I think we have a command for bungee broadcasting as well there, check the wiki :)

**Comment by NoxNap** [comment]
hey! I was messing with this today and I'm confused on how to get this working.
I tried 
`ChatControlRed/rules/command.rs`
```rs
match ^(\/testannounce) (.*)
dont verbose
then notify announcements announce
```
with 
`ChatControlRed/formats/announce.yml`
```yml
Parts:
  commands:
    Message:
    - '<center>&2&lAnnouncement'
    - '<center>&a{$0} $0 $1 $2'
    - '<center>&a$0 $1 $2'
    - '<center>&a{$message}'
    - '<center>&a{message}'
```
`{message}` parses but it does the entire match case, so im not really sure how to fix that. I noticed at least 2 others a few months back having similar questions on doing these types of formatting, for them it was for a twitch stream notifier and a store purchase notifier; both of which i would like to do too if i can get announcements working. So maybe you could provide a quick example of those and throw them on the wiki? From what I found neither of them were given any specific solutions for doing those, which is why im here again.

**Comment by kangarko** [comment]
I would replace "then notify" with "then warn announce". It should pickup the format and send it automatically.

**Comment by NoxNap** [comment]
`{message}` is still parsing the entire match case, I tried doing something similar to how helpop is done and adding $2  to `then warn announce` but that doesn't work, probably since it's a format and it doesn't seem possible to use anything but `{message}` in the formats.
```rs
match ^(\/testannounce) (.*)
dont verbose
then warn announce
```
```yml
Parts:
  commands:
    Message:
    - '<center>&2&lAnnouncement'
    - '<center>&a{message}'
```
![image](https://github.com/kangarko/ChatControl-Red/assets/151105845/a4b7b2ca-f0df-4432-b7ed-cdbf108246f2)
