### ISSUE TITLE
1.20.6: How to format MOTD with Image_Head and clickable sections

### ISSUE THREAD

**Issue by ScrapMetalGolem** [kangarko/ChatControl#2685]
### Are you using MySQL?

Yes

### Are you using BungeeCord/Velocity?

Yes - Velocity

### Question

I want to present an MOTD to the players which contains their player head, plus some clickable sections. I want to format it with the head on the left and the text on the right.

I am able to accomplish this desired layout with the head on the left, but not when I create the sections I need for the clickable parts.

This is the format as the below config generates it:

![1bad](https://github.com/kangarko/ChatControl-Red/assets/159202664/5fe29a7a-a7b0-498c-8a6f-c44a057aaf90)

This is the desired format:

![2good](https://github.com/kangarko/ChatControl-Red/assets/159202664/11457177-d064-4fa7-9795-93715c828374)

`
New_Line_Per_Part: true

Parts:

  head:
    Image_Head: "{player}"
    Image_Height: 8
    Image_Type: "BLOCK"
  welcome:
    Message:
    - '&cWelcome to TimeCraft, {player}!'
    - ''
  link:
    Message:
    - '&aLink Your Discord &7- &f/discordsrv link'
    Hover: 'Click to link your discord'
    Run_Command: /discordsrv link
  rules:
    Message:
    - '&aRules &7- &f/rules'
    Hover: 'Click to read the rules'
    Run_Command: /cmi ctext rules
  global:
    Message:
    - '&aJoin Chat &7- &f/ch join global'
    Hover: 'Click to join chat'
    Run_Command: /channel join global
  help:
    Message:
    - '&aHelp &7- &f/ch join helpop'
    Hover: 'Click to get help or report players'
    Run_Command: /channel join helpop
  website:
    Message:
    - '&aWeb &7- &ftimecraftgaming.com'
    Hover: 'Click to visit our website'
    Open_Url: http://www.timecraftgaming.com
  discord:
    Message:
    - '&aDiscord &7- &fhttps://discord.gg/s3cfmMWtnu'
    Hover: 'Click to join our Discord'
    Open_Url: https://discord.gg/s3cfmMWtnu
`

I understand that you are unavailable during holiday; I'll wait for your return.

**Comment by kangarko** [comment]
Hello and thanks for waiting :)

You need to put everything in one part like this:

````yaml
# -----------------------------------------------------------------------------------------
# The default chat format used as a message of the day.
#
# See chat.yml for documentation on all available options in the "Parts" section.
# -----------------------------------------------------------------------------------------

# If true, each section in Parts will begin on a new line automatically.
# See https://github.com/kangarko/ChatControl-Red/issues/2510
New_Line_Per_Part: false

# The parts of this format.
Parts:
  
  # See the chat.yml format file for a tutorial on how this works.
  everything:
    Image_Head: '{player}'
    Image_Height: 8
    Message:
    - '&fHello {player}!'
    - ''
    - '&6Version: &f{nms_version}'
    - '&6Changelog:'
    - '&7- &fAdded ChatControl Red plugin.'
    - ''
    - '&6Help &7- &f/help &6Settings &7- &f/menu &6Web &7- &f/web'
    #- "&7The chat is NOT monitored and we respect your privacy rights. Just kidding."

````
