### ISSUE TITLE
1.16.4 | Chat formats doesn't work as they should (I think)

### ISSUE THREAD

**Issue by tomhula** [kangarko/ChatControl#272]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: false

So, whe nyou have some format devided in parts and there is color code at the end of one and the following has some variable in it ({message}), it won't get colored. Example:
```
Parts:
  prefix:
    Message: '{player_prefix}'
    Hover:
    - '&7{player_prefix+}{player_name} {player_suffix}'
    - '&7Ping&8: &f{ping}ms'
    - '&7Rank&8: &f{player_group}'
    - '&7Posted: &f{timestamp}'
    - ''
    - '&7Click to learn more about ranks.'
  player-name:
    Message: '{player_nick}'
    Hover:
    - '&7Click to message.'
    Suggest_Command: '/msg {player_name} '
  chat-connector:
    Message: ' &3&l> &6'
  normal-message:
    Message: '{message}'
```

Expection: Message in golden color.
Reality: Message in white (none) color.

**Comment by PascalBrassat** [comment]
Put the &6 in front of {message}, I never quite paid attention to how it does that as we tied the chat connector and message together into one, as an example
`  playername:
    Message: ' {player_displayname}'
    Message: '&6: {message}'
`

**Comment by tomhula** [comment]
> Put the &6 in front of {message}, I never quite paid attention to how it does that as we tied the chat connector and message together into one, as an example
> ` playername: Message: ' {player_displayname}' Message: '&6: {message}'`

Yeah this would work in this case, but if you would want to do this:
```
Parts:
  prefix:
    Message: '{player_prefix}'
    Hover:
    - '&7{player_prefix+}{player_name} {player_suffix}'
    - '&7Ping&8: &f{ping}ms'
    - '&7Rank&8: &f{player_group}'
    - '&7Posted: &f{timestamp}'
    - ''
    - '&7Click to learn more about ranks.'
  player-name:
    Message: '{player_nick}'
    Hover:
    - '&7Click to message.'
    Suggest_Command: '/msg {player_name} '
  chat-connector:
    Message: ' &3&l> &6'
  admin:
    Message: '&c'
    Sender_Permission: my.permission,for,players,with.red.text
  normal-message:
    Message: '{message}'
```

**Comment by kangarko** [comment]
For now, the parser resets to white after each section so you'd have to have duplicated normal-message part. I will look forward into remaking it later.

**Comment by tomhula** [comment]
> For now, the parser resets to white after each section so you'd have to have duplicated normal-message part. I will look forward into remaking it later.

Sorry for my stupidity, but how exactly do you mean "duplicated normal-message"?

**Comment by kangarko** [comment]
Something like this :)

```
  normal-red-message:
    Message: '&c{message}'
    Sender_Permission: red.text
  normal-green-message:
    Message: '&2{message}'
    Sender_Permission: green.text
```

**Comment by tomhula** [comment]
> Something like this :)
> 
> ```
>   normal-red-message:
>     Message: '&c{message}'
>     Sender_Permission: red.text
>   normal-green-message:
>     Message: '&2{message}'
>     Sender_Permission: green.text
> ```

ok thanks, also is there any way to negate the permission? (so if he does not have it)
So it could be like this:
```
chat-connector:
    Message: ' &3&l> &7'
  highlited-message:
    Message: '&f{message}'
    Sender_Permission: chatcontrol.format.highlighted
  normal-message:
    Message: '&7{message}'
    Sender_Permission: !chatcontrol.format.highlighted
```
