### ISSUE TITLE
1.20.4: Variables do not properly resolve

### ISSUE THREAD

**Issue by sarhatabaot** [kangarko/ChatControl#2732]
### "/version ChatControlRed" - plugin version

10.27.4

### Are you using MySQL?

Yes

### Are you using BungeeCord?

No

### Error log (if applicable)

https://paste.gg/p/anonymous/6fefcc70fee048da8e354faf57596488

### "/chc debug" output (strongly recommended)

Sent via email.

### Information about the issue/bug

I have a simple variable, see setup below.
When executing via `/chc info script sarhatabaot {player_is_op}` the result is resolved to "yes" instead of "true".

```yaml
Type: FORMAT

# The key we look for in the chat surrounded by [] brackets, example:
# chat message: "Hello everyone, I have an [item] in my hand"
Key: player_is_op

# The value the key will be replaced to.
# This uses JavaScript and must return a boolean value.
Value: player.isOp()

# What JavaScript condition must return true for this variable to show?
# You can put variables in here to get replaced.
Sender_Condition: '{sender_is_player}'

# What permission must the message sender have in order for this variable to display to him?
Sender_Permission: ''

# See Sender_Condition, except that we evaluate the JavaScript for each chat message receiver
# and only show the message to those receivers for which the condition returns true.
Receiver_Condition: ''

# What permission must the message receiver have in order for this variable to display to them?
Receiver_Permission: ''
```
