### ISSUE TITLE
1.21: format part took 853ms to render

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2792]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

10.27.8

### Optional: Error log

https://pastebin.com/dLw75TP5

### Steps to reproduce

Hello, I have this part of the motd:
```yml
  part4:
    Message:
    - '{#ff1414}&l| &fUseful commands: &7/vote /rtp /back /team /home /levels&f.'
    - '{#ff1414}&l---------------------------------------------'
    - ''
    Suggest_Command: /vote

```
and it got tagged for the 
[23:54:27] [Server thread/INFO]: [ChatControlRed] Warning: motd_newcomer format part took 853ms to render! (If you are downloading images/player heads this is expected!) '': {

why it even mentions the image_height & type, when there's no image?
[23:54:27] [Server thread/INFO]: [ChatControlRed] 	'Image_Height' = '8'
[23:54:27] [Server thread/INFO]: [ChatControlRed] 	'Image_Type' = '█'
