### ISSUE TITLE
Add predefined format from formats folder to be able to use in a lot of Channels.List formattings

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [kangarko/ChatControl#2804]
### Summary

So when we are defining a channel in Channels.List, we have
```
Channels:
<...>
  List:
    standard:
      Format: chat
```
There are a lot more options such as `Format_Console`, `Format_Discord_Webhook_Name`, `Format_Discord`, `Format_Spy`, etc...

For the ones i mentioned, maybe for some it is possible, but for discord format and webhook it does not work - to be able to enter "chat" where we are pulling formattings from formats/chat.yml

of course we can have separate discord_webhook_name.yml and format_discord.yml or whatever we like, but i think this would be  very useful and not hard to implement

and options like hovering text and clickable will not work / be ignored if used for format which does not support it, i think there will be no problems with that at all

Thank you in advance if you consider this, much appreciated

PS. only reason i think this is needed is because formats give us PARTS and parts gives us UNLIMITED CONDITIONS to be used, and that is powerful thing, this cannot be done directly in Channels.Lists... and even if it is possible, it would be such a mess if we can add parts there - that is why we have formats and that should be utilized for as much format options in Channels.Lists as possible!

**Comment by MotikaCraft-TheJoshua** [comment]
The thing that is very messed up as of now is `Format_Discord`

you can use format from `formats` folder here, so we can use for example `Format_Discord: chat-discord` where `formats/chat-discord.yml` is used, **but this only works when message is sent From Discord To Minecraft**, when you try to send message from minecraft to discord, this is how it shows on discord:
![image](https://github.com/user-attachments/assets/9f544d84-644f-436e-b546-e0905e302218)

So please, change `Format_Discord` to 2 separate formats:
- `Format_From_Discord`
- `Format_From_Minecraft`

and for sure allow usage of predefined formats from `formats` folder for `Format_From_Discord`, for the `Format_From_Minecraft` this can also be allowed (why not?), admins just need more caution about things that will not work as they are present in minecraft and not on discord (such as text hovering/clicking...)

**Comment by MotikaCraft-TheJoshua** [comment]
I just want to show how easy it would be if Format_Discord would support linking to formats from `formats` folder, no need for separating into 2 formats as i mentioned above:

**`settings.yml`**
```yml
Channels:
  List:
    standard:
      Format: chat
      Format_Console: '[{luckperms_primary_group_name}] {player}&r &8>&r {luckperms_meta_chat_color}{chat_color}{chat_decoration}{message}&r'
      Discord_Channel_Id: 1234567891011121314
      Format_Discord: chat-discord
```

for the **`formats/chat.yml`** we have our regular chat ingame based...

**`formats/chat-discord.yml`**:
```yml
New_Line_Per_Part: false

Parts:
  From_Minecraft_To_Discord-part_1:
    Sender_Condition: '{sender_is_player}'
    Message: '{player_name} > {message}'
  From_Discord_To_Minecraft-part_1:
    Sender_Condition: '{sender_is_discord}'
    Message: '&8[&9Discord&8] &b{discordsrv_user_nickname} &8» &e{message}'
```

And that is everything handled, I really don't know why it's not already working like this...
