### ISSUE TITLE
Color Player Names

### ISSUE THREAD

**Issue by 00Hrtz** [kangarko/ChatControl#282]
I've searched the Wiki but can't find anything, is it possible to have players names in Color?

**Comment by 00Hrtz** [comment]
I'd ask the community of plugin owners but there's no Discord.

**Comment by ElBananaa** [comment]
> I'd ask the community of plugin owners but there's no Discord.

Hey! There's a channel for the testers on the plugin discord. You should've been added to it.
Yeah it is possible to have colored player names, why wouldn't it be possible?
You can even create gradients for the names. There's an example in the default.
Here's an example of the nick system with a gradient.
![image](https://user-images.githubusercontent.com/53318613/102531155-2ab02a80-40a2-11eb-8de8-ae7bd0305030.png)
(Don't pay attention to the {deluxetags_tag} placeholder, I don't have deluxetags installed)

**Comment by 00Hrtz** [comment]
All i can find is something on gradients, i just need my players names colored, be cool if they could choose their own name color.

**Comment by ElBananaa** [comment]
> All i can find is something on gradients, i just need my players names colored, be cool if they could choose their own name color.

They can, just give them the permission to use the nick command. To change the color, just use the default color codes or use hex colors.
Here's an example of the message remove feature using a hex color:
``` 
  delete-chat:
    Message: '&7[#cf0e00&lX&7]&r '
    Receiver_Permission: chatcontrol.removemessages
    Hover:
    - '&cDelete this message'
    Run_Command: /{label} internal remove {message_uuid}
```

As you can see, I use `#cf0e00` (which is a red color) with bold color code...
