### ISSUE TITLE
A question Prefix/Names Problem Paper 1.21

### ISSUE THREAD

**Issue by MisterMakey** [kangarko/ChatControl#2859]
### Are you using MySQL?

No

### Are you using a proxy?

Yes - Velocity

### Question

"We created different ranks and prefixes for our players.

Check the config.

The issue is that the rank named 'SuperHeld' is not working correctly,

<img width="109" alt="Screenshot_513" src="https://github.com/user-attachments/assets/a1b4a43f-3861-4ecc-87fe-e2992e51a3dd">

 while all the others function without any problems. This means that for this rank, neither the prefix nor the name is displayed as it is with the others. What could be causing this?"

<img width="301" alt="Screenshot_514" src="https://github.com/user-attachments/assets/ffe4735f-ae09-4cd0-bdeb-852b201436bd">

<img width="292" alt="Screenshot_512" src="https://github.com/user-attachments/assets/39ef43b8-0443-4436-87a5-e1cdcec78c1c">

```yaml
  SuperHeld-prefix:
    Gradient: '#FA1818 - #FFFFFF'
    Message: '{player_prefix+}'
    Hover:
    - '&7{player_prefix+}{player_name}{player_suffix} '
    - '&7Ping&8: &f{ping}ms'
    - '&7Rang&8: &f{player_group}'
    - '&7Gesendet: &f{timestamp}'
    - ''
    - '&7Klicke hier, um mehr über Ränge zu erfahren.'
    Open_Url: https://twistertwins.craftingstore.net/
    Sender_Condition: '''%luckperms_primary_group_name%'' == ''SuperHeld'''
```
    
    
```yaml    
SuperHeld:
    Message: '{player_name}'
    Gradient: '#FA1818 - #FFFFFF'
    Hover: '&7Klicke, hier um eine Nachricht an {player_name} zu senden.'
    Suggest_Command: '/msg {player_name} '
    Sender_Condition: '''%luckperms_primary_group_name%'' == ''SuperHeld'''
```
