### ISSUE TITLE
Add DiscordSRV Ascension integration

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [kangarko/ChatControl#2869]
### Summary

Adding another option besides discordsrv integration, to support new Ascension DiscordSRV which is currently in beta
I really hope this is not too much work because this new DiscordSRV is really good...

I see plenty of plugins have integration for new DSRV Ascension
https://docs.discordsrv.com/ascension/compatibility/#plugin-integrations-and-compatibility

**Comment by MotikaCraft-TheJoshua** [comment]
something like

```yml
Integration:

  # Integration with DiscordSRV. 
  Discord:
    
    # Enable all integration with DiscordSRV?
    # This is enabled by default because Discord in reality won't work unless you connect it
    # in Channels.List above or use it in operators, so you have one less option to find & enable. 
    Enabled:

      v1: true/false # support for DiscordSRV 1.29.0+

      Ascension: true/false # support for DiscordSRV Ascension

      <...other options...>
```
