### ISSUE TITLE
Paper-1.21.1-131: Autojoin setup

### ISSUE THREAD

**Issue by TheReizi** [kangarko/ChatControl#2890]
### Are you using MySQL?

No

### Are you using a proxy?

No

### Question

**settings.yml** Channels.List:
```
  List:
    standard:
      Format: chat
      Range: 150
    global:
      Format: global-chat
```

For the **default** group, I gave the permission "**chatcontrol.channel.autojoin.standard.write**" in **LuckPerms**, but when a user joins the server, he still gets the message "**[10:47:28] [X] You lack permissions to join any channels.**"
