### ISSUE TITLE
Paper 1.21.1: Am I using MiniMessage Correctly?

### ISSUE THREAD

**Issue by developedbyalex** [kangarko/ChatControl#2891]
### Are you using MySQL?

No

### Are you using a proxy?

No

### Question

Hi, 

I am attempting to create an MOTD with some interactive text using hover and click actions. However, the MiniMessage formatting in my `motd.yml` does not seem to work as expected. Instead of rendering correctly, it either displays raw text or throws errors.

Here is my current `motd.yml`:

```yaml
# -----------------------------------------------------------------------------------------
# The default chat format used as a message of the day.
#
# See chat.yml for documentation on all available options in the "Parts" section.
# -----------------------------------------------------------------------------------------

# If true, each section in Parts will begin on a new line automatically.
# See https://github.com/kangarko/ChatControl-Red/issues/2510
New_Line_Per_Part: true

# The parts of this format.
Parts:
  
  # If you want to use player head here, add the "Image_Head: {player_name}" key. See chat.yml for 
  # full documentation and all options available.
  everything:
    Image_Head: '{player}'
    Message:
      - ""
      - ":wave: Welcome, {player} to The SMP"
      - ""
      - "&fThanks for playing!"
      - ""
      - "Checkout some cool things &8&o(&7&oyou can click them&8&o)"
      - "<hover:show_text:'<green>View Our Store</green>'><green><b><click:open_url:'https://store.minecraftbuddies.com/'>STORE</click></b></green></hover> • <blue><b><click:run_command:'/cosmetics'>COSMETICS</click></b></blue> • <yellow><b><click:run_command:'/hdb'>HEADS</click></b></yellow>"
```

### Steps I've Taken:
1. I configured the MOTD with hover and click actions using MiniMessage-like syntax.
2. Verified the MiniMessage formatting using **MiniMessageViewer** to ensure correctness before applying it to the configuration.
3. Reloaded the plugin using `/chc reload`.
4. Verified the configuration file is error-free using a YAML linter.

### Issue:
- The hover and click actions do not render as expected.
- The MiniMessage syntax (`<green>`, `<click>`, `<hover>`, etc.) does not seem to work or gets displayed as plain text.

### Questions:
1. Does ChatControl Red support MiniMessage syntax in the MOTD (as defined in the `Parts` section)?
2. If not, what is the correct syntax for hover and click actions in ChatControl Red?
3. Are there any additional steps required to enable MiniMessage support or to use these features?

### Images:
![image](https://github.com/user-attachments/assets/5d8fc29d-07b4-45b0-b154-79746e23c455)
![image](https://github.com/user-attachments/assets/592de62c-392a-4e00-91e4-75c553b39583)

I would appreciate any guidance or examples of working MOTD configurations that include hover and click actions. 

Thank you for your help
