### ISSUE TITLE
Variables scripts work incorrectly

### ISSUE THREAD

**Issue by Sakishima** [kangarko/ChatControl#2899]
### Are you using MySQL?

Yes

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

10.28.5

### ZIP of "/chc debug"

On the new version of the plugin, scripts (YML Files from the Variables directory) began to work incorrectly.
For example, this script now always returns a false:
`Value: '''{receiver}'' == ''{player}'' ? ''you'' : ''&7{pl_prefix}{receiver}'''`

All scripts from this directory broke.

### Steps to reproduce

Send a personal message using the following parameters

receiver-or-you.yml variables:
```
Type: format
Key: receiver_or_you
Value: '''{receiver}'' == ''{player}'' ? ''you'' : ''&7{pl_prefix}{receiver}'''
Sender_Condition: ''
Sender_Permission: ''
Receiver_Condition: ''
Receiver_Permission: ''
```

Use formatting for personal messages
```
Parts:
  everything:
    Sender_Permission: chatcontrol.user.default
    Message: '&c✉ &8[&f{sender} &7-> &f{receiver_or_you}&8] &c> &a{message}'
    Suggest_Command: '/tell {sender} '
```
