### ISSUE TITLE
1.21.1: MOTD Bold isn't working correctly + converted hex colors neither

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2908]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

11.0.0-BETA

### Steps to reproduce

Hello, there are currently two bugs:
```yml
Parts:
  
  # If you want to use player head here, add the "Image_Head: {player_name}" key. See chat.yml for 
  # full documentation and all options available.
  everything:
    Message:
    - '<#ff0000><bold>|</bold>'
  part2:
    Message:
    - '<reset>asds'
```
When you use two parts and one has bold, the second one is bold as well and looks like that <reset> even doesn't work in this case
Even when I add bold & /bold again to the part2 it doesn't fix it 
![image](https://github.com/user-attachments/assets/7d26f5e6-e1dc-4fe4-95dd-ee3f8845f5f2)

2. The defaultly converted HEX colors with the format {<#HEX>} didn¨t work, I had to remove surrounding {} and I'm confused what's correct format then
