### ISSUE TITLE
Packet rules are not working for me

### ISSUE THREAD

**Issue by DeusNinja** [kangarko/ChatControl#291]
Only one I have in the packets.txt right now is

```
# Hide unknown command message.
match ^Unknown command.*
then rewrite &l&fDerp.
```
and in my settings.yml I have 

```
Rules:
  Verbose: true
  Bungee: false
  Chat: true
  Commands: true
  Packets: true
  Signs:
    Check: true
    Block: true
    Drop: true
  Books:
    Check: true
    Replace: true
  Anvil:
    Check: true
    Replace: true
  Chat_Ignorer:
    Enabled: false
    Sets:
      swear:
        Ignored_By_Default: false[/code][/spoiler]
Regex_Strip_Colors: true. 
```

using ProtocolLib-4.4.0.jar
