### ISSUE TITLE
1.21.1: Tag has wrong color

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2914]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

11.0.3

### Steps to reproduce

Hello, when I have this part in my chat.yml formats folder:
```yml
  player-tag:
    Message: '{eternaltags_tag}<reset>'
    Hover:
    - '&7XX'
    Suggest_Command: /tags
    Sender_Condition: '!{sender_is_discord}'
```

And the eternal tags is:
```yml
    tag: '&8&l[<#800080>&lS1&8&l]&r'
```
it's not displaying correctly, like it shows with black color, but when I parse it with PAPI it works.

And it was working in the latest RED version
![image](https://github.com/user-attachments/assets/20a03d2a-6857-4fd0-bf34-65b013c149b4)
I tried to add there SS1 just to see if it changes and yes it changes, but still black

And it seems working on other places so it's really strange, even the format works when I use it in luckperms & put there placeholder from luckperms

even tried Support_Variables_In_Variables to true but not working

In case it can't be fixed, then it could be good to support old method of displaying # as well, because there can be many plugins with unsupported format
