### ISSUE TITLE
Login / Quit messages not displaying player placeholder name for each unique player.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl#293]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: false

Migrating from ChatControl 8 to Red 10.1.9.

Join.rs (in messages folder)
```
# Messages automatically migrated from ChatControl 8 to rules syntax on 17.12.2020 23:30:48
# See https://github.com/kangarko/ChatControl-Red/wiki/Messages for documentation and help.

group default
message: 
- Login
```

Login.yml (in formats folder)
```
# -----------------------------------------------------------------------------------------
# Represents a chat format file that can be used to stylize messages.
# See the chat.yml for a tutorial on how this works.
# -----------------------------------------------------------------------------------------

# The parts of this format.
Parts:
  Default:
    Message: '&8[&2+&8] {player_displayname} &fhas &2joined &fthe server.'
    Hover:
    - '&f&lName:&r {player}'
```

Whenever a player logs in or quits, it displays the person viewing the message's name instead of the actual player joining / leaving. I assume this is because it's reading formatting separately instead of part of the join/quit .js configuration. 

I tried migrating the formatting over to the .js file with something like this, but then hover events are no longer functional. It does however fix the proper display name being shown.
```
message: 
- &8[&2+&8] {player_displayname} &fhas &2joined &fthe server.
hover:
- &f&lName:&r {player}
```

How can I format the login/quit message properly to support hover formatting and not display the player's own name for every login?

**Comment by ElBananaa** [comment]
Hey! What plugin are you using for nicks/displaynames (the player_displayname placeholder)?
If you're using the internal nicks system, just use {player_name}, it'll automatically be replaced with the nick.

**Comment by mibby** [comment]
I'm using EssentialsX for nicknames. Otherwise colors are set by LuckPerms based on the player's primary group prefix. All my placeholders come from PlaceholderAPI and various extensions for it, as I use PAPI placeholders in various other plugins.

This issue is when join.rs is linked to a format, it no longer displays the player name for the person logging in but instead for the person viewing the message. When the exact same placeholder is used directly on join.rs instead of a format, it works fine, but you lose the option to use hover events.

**Comment by kangarko** [comment]
Thanks, will be fixed.

Don't use hover in rs files, it is unsupported there.

**Comment by mibby** [comment]
Figured as much. As long as the placeholder display for connecting/disconnecting users can be fixed in formatted messages linked to join/quit rs files so hover and other special conditions can properly work, all is good.

**Comment by kangarko** [comment]
This will however be completely fixed today.

**Comment by mibby** [comment]
@kangarko This seems only partially fixed with ChatControl Red 10.1.12. Login messages work now when attached to a format. It properly shows the displayname of the target player logging in to others.

What is broken is logout. When players quit, their displayname is now empty. 
![link3](https://i.imgur.com/x7WZzR7.png)

quit.rs
```
group default
message:
- leave
```

leave.yml
```
Parts:
  Default:
    Message: '&8[&4-&8] {player_displayname} &fhas &4left &fthe server.'
    Hover:
    - '&f&lName:&r {player}'
```

I have a feeling it might be related to the fix for https://github.com/kangarko/ChatControl-Red/issues/294 with this;

```
  # If you want to display join, quit and kick messages after other plugins, you can send them
  # a bit later such as 1 tick later than the other messages. Customize this here. 
  # **YOU CANNOT OVERRIDE THIS WITH THE "DELAY" OPERATOR**
  Player_Defer_Sending_By: 1 tick
```

When I changed {player_displayname} to {player}, the username isn't blank anymore. But it no longer displays their displayname and color when they quit.

I believe ChatControl 8 only delayed join messages, not quit and kick. So doing it on quit is causing the defer delay to not find the displayname anymore since the player is already gone? Can the defer be separated?

Latest testing with ChatControl Red 10.1.12
