### ISSUE TITLE
1.21.3: Alonsotags hex colors not working

### ISSUE THREAD

**Issue by Truongvv10** [kangarko/ChatControl#2949]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

11.0.3-BETA

### Steps to reproduce

When talking in to chat, the hex colors that I configured on alonsotags parsed to minecraft default colors. 

This used to work in chatcontrol v10, after upgrading to chatcontrol v11, the colors don't parse normally anymore. 

### This is how I configured it in chatcontrol:
```yml
Parts:
  tags:
    Message: '{alonsotags_tag_chat}&r&8] '
    Hover:
    - ' {alonsotags_recognition_title} '
    - ' <#B7AFA3>Use &f/tags <#B7AFA3>to equip one'
    - ' <#B7AFA3>Rank position &f{luckperms_highest_group_by_weight}<#B7AFA3>. '
    Run_Command: '/tags '
    Sender_Condition: '''{sender_is_discord}'' == ''false'''
 ```
![image](https://github.com/user-attachments/assets/62f111f2-197a-4d32-a964-65fc3ebc9dc3)
### This is how I configured it in alonsotags:
```yml
Tags:
  Lone-Wolf:
    Displayname: "&8 ● #4d9be6&lL#5898e8&lo#6495e9&ln#6f92eb&le{COLOR}⚡#868dee&lW#918af0&lo#9d87f1&ll#a884f3&lf"
    Tag: "#4d9be6&lL#5898e8&lo#6495e9&ln#6f92eb&le{COLOR}⚡#868dee&lW#918af0&lo#9d87f1&ll#a884f3&lf"
    Recognition-title: "&f{COLOR}🍖 #4d9be6S#5499e7o#5b97e8l#6296e9i#6994eat#7092eba#7790ecr#7e8fedy #858deeH#8c8befu#9389f0n#9a88f1t#a186f2e#a884f3r {COLOR}🍖"
    Material: NAME_TAG
    Default-color: "#ffa214"
    Hide-flags: true
    Dyeable: true
    Permission: alonsotags.tag.lonewolf
    Custom-model-data: 0
    Description:
      - "&7Tag for beginners."
    Lore:
      Locked:
        - "&8 &nClick here to select"
        - " "
        - "&8 → #DFDFDFTag: &8[{TAG}&8]"
        - "&8 → #DFDFDFStatus: #e83b3b&nLocked"
        - "&8 → #DFDFDFDyeable: #91db69&n{DYEABLE}"
        - " "
        - "&8 → #DFDFDFRecognition Title: "
        - " {RECOGNITION-TITLE}"
        - " "
        - "{RIGHT-CLICK-TO-PREVIEW-MESSAGE}"
        - " #e83b3bYou don't own this tag"
      Unlocked:
        - "&8 &nClick here to select"
        - " "
        - "&8 → #DFDFDFTag: &8[{TAG}&8]"
        - "&8 → #DFDFDFStatus: #91db69&nUnlocked"
        - "&8 → #DFDFDFDyeable: #91db69&n{DYEABLE}"
        - " "
        - "&8 → #DFDFDFRecognition Title: "
        - " {RECOGNITION-TITLE}"
        - " "
        - "{RIGHT-CLICK-TO-PREVIEW-MESSAGE}"
        - " #91db69Left click to equip tag"
      Selected:
        - "&8 &nClick here to select"
        - " "
        - "&8 → #DFDFDFTag: &8[{TAG}&8]"
        - "&8 → #DFDFDFStatus: #f04f78&nSelected"
        - "&8 → #DFDFDFDyeable: #91db69&n{DYEABLE}"
        - " "
        - "&8 → #DFDFDFRecognition Title: "
        - " {RECOGNITION-TITLE}"
        - " "
        - "{RIGHT-CLICK-TO-PREVIEW-MESSAGE}"
        - " #f04f78Currently selected tag"
    No-permission-message: "&cYou don't have permission to use this tag!"
    Not-enough-money-message: "&cYou don't have enough money to purchase this tag!"
    Purchase-commands: []
    Select-commands:
      Pre: []
      Post: []
    Price: 0
    Cost:
      Type: VAULT
      Material: DIAMOND
    Unbreakable: false
```
![image](https://github.com/user-attachments/assets/1db75867-a745-4b63-b583-f99749db4f7c)
