### ISSUE TITLE
1.21.4: Placeholders aren't replaced in variables

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#2962]
### Are you using MySQL?

No

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

11.0.6

### Steps to reproduce

Hello, just try to use some variable and return it, and then use it in format:
```yml
# -------------------------------------------------------------------------------------------------
# ChatControl supports dynamic, high performance variables you create! They can be used across
# the plugin, for example in formatting your chat or death messages. Currently, the folder
# variables/ stores all custom variables in each separate yml file.
#
# Variables can not only be used to display information, but because you can write your own full
# code in JavaScript to display them, they can also do whatever you would wish for your
# players/server, such as sneaking in code to send sounds or spawn monsters.
#
# Coding this variable requires a little bit of JavaScript knowledge, see the link below.
#
# For documentation and help, please see this link:
# https://github.com/kangarko/ChatControl-Red/wiki/JavaScript-Variables
# -------------------------------------------------------------------------------------------------
#
# Where should this variable be used?
#
# FORMAT = used in your formats with {syntax}, players cannot use it
# MESSAGE = players can use it with [syntax] in their chat messages
Type: format

# The key you can later use in formats. Do not use brackets. 
# Put the variable name here such as my_variable and you'll be able to call it with {my_variable}.
Key: level

# The value the key will be replaced to. This uses JavaScript, you can use 
# "player" to get the player, if available.
Value: |-
  showLevel();

  function showLevel() {
      var level = "{therewards_player_playtime_claimed_count}";
      return level;
  }

# What JavaScript condition must return true for this variable to show?
# You can put variables in here to get replaced.
Sender_Condition: ''

# What permission must the message sender have in order for this variable to display to him?
Sender_Permission: ''

```
  level:
    Message: '{level} <reset>'

and it looks like this 
![image](https://github.com/user-attachments/assets/44a9a904-44f7-466e-8e3c-406a10d0122f)

EDIT: BTW THIS ISN'T REAL USAGE, I USUALLY CHECK IF IT'S NULL AND THEN RETURN EMPTY STRING, OTHERWISE RETURN level + space
