### ISSUE TITLE
Default config inconsistencies.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl#297]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: false

ChatControl Red 10.1.9

Noticed some default config inconsistencies.

Anti_Spam specifies ``0 second`` instead of ``0 seconds`` like everywhere else.
```
Anti_Spam:
  
  # Settings applied to chat:
  Chat:
    
    # How many seconds must the player wait between each message? Set to 0 to disable.
    Delay: 0 second
```

---

``` Sound: ENTITY_CHICKEN_EGG 1F 1.5F``` in **Private_Messages** & **Sound_Notify** sections do not have commas like the sound set in MOTD; ``Sound: ENTITY_FIREWORK_LAUNCH, 1F, 0.1F``.
