### ISSUE TITLE
1.21.3: Duplicate messages

### ISSUE THREAD

**Issue by Truongvv10** [kangarko/ChatControl#2992]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

11.1.0

### Steps to reproduce

This issue is marked as closed but still getting double messages.
https://github.com/kangarko/ChatControl-Red/issues/2966#issue-2771325566

**Comment by kangarko** [comment]
Next time please comment on the closed one. All issues get attention.

**Comment by kangarko** [comment]
@Truongvv10 I need you to 

1. Post me your /chc debug and tell me which channel is getting duplicated
2. Are you using Redis? Can you verify it happens with redis uninstalled, still?
3. See this comment on the closed issue and verify you have linked your server name properly:

`Resolved it, I had set each of the Server_Name's in proxy.yml to their prefixes, not the full name. So for Lobby, I had 'L', rather than 'lobby'. Sorry for the time taken, just an oversight on my part.`

**Comment by Truongvv10** [comment]
All my channels that are proxy seem to be duplicated. I did the proxy.yml like:
```yml
Enabled: true

# The prefix before the message sent to proxy. Set to empty to disable.
Prefix: 'T'

# Set a unique name of this server. Only alphanumeric and underscores are allowed.
#
# **WARNING** If using proxy, this must match the server name you have in velocity.toml or 
#             BungeeControl's config.yml, NOT your server alias in BungeeControl or VelocityControl.
Server_Name: Towny
```
This is what I see in chat

![Image](https://github.com/user-attachments/assets/0dabe1b3-4d1c-4f2c-b466-9cac7c8f3b25)

[debug.zip](https://github.com/user-attachments/files/18444892/debug.zip)
