### ISSUE TITLE
1.21.3: unrecognized keys

### ISSUE THREAD

**Issue by Pantera07** [kangarko/ChatControl#2995]
### Are you using MySQL?

Yes

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

11.1.0

### Steps to reproduce

I added 'global_discord-chat.yml' to the 'formats' folder and set the format for 'Format_from_Discord', but this message is output:
`Warning: Channel Global found unrecognized keys '[Format_from_Discord]', see the # comments in settings.yml in Channels.List for what keys you can use.`

```
  List:
    Global:
      Format: global-chat
      Format_from_Discord: global_discord-chat
      Discord_Channel_Id: 1046134648646941346
```
