### ISSUE TITLE
Custom javascript placeholder added to hover formatting does not register reset color code.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl#300]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: false

ChatControl Red 10.1.9

ChatControl Red does not seem to register the reset color code (&r) when loading custom javascript placeholders. It is causing the entire placeholder variable to be bolded instead of partial bolding, partial normal.

Specifically the middle line.
![link](https://i.imgur.com/DFtX79c.png)

chat.yml prefix hover formatting
```
  prefix:
    Message: '&7{javascript_prefix} '
    Sender_Permission: chatcontrol.groups.default
    Hover:
    - '&f&lName:&r {player}'
    - '{javascript_tag}'
    - '&e{javascript_description}'
```

PlaceholderAPI Custom Javascript (tag.js)
```
var tags = "%deluxetags_tag%";

function hasTag()
{
  if (tags == '')
  {
    return "&b&lRank:&r &8<&7%vault_rank%&8>";
  }
   else {
       return "&b&lTag:&r %deluxetags_tag%";
   }
}

hasTag();
```

This is not an issue with ChatControl Pro (v8). Here is how it looks on v8.
![link2](https://i.imgur.com/63GuJai.png)
