### ISSUE TITLE
1.21.1 InteractiveChat tag

### ISSUE THREAD

**Issue by tygh89071388** [kangarko/ChatControl#3007]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

V11.1.0

### Steps to reproduce

I keep adjusting the plugin's Chat_Listener_Priority,
have also tried changing Filter_Unknown_Mini_Tags: false,
and adjusted EventPriorities in the InteractiveChat plugin.

However, no matter how I adjust these settings, some players are still unable to send [item] or tags in public chat. The console displays the following message:

[ChatControl] Found InteractiveChat tag chat=8ceb2a93-64fc-4e63-a013-69be36540908 in a message. If this causes issues with UUIDs being caught by our rules, try lowering Chat_Listener_Priority in settings.yml to 'LOWEST'. Unfortunately, there is no fix for commands. This message only shows once per 3 hours.

What else can I try?

ChatControl v11.1.0
VelocityControl v2.1.0

edit:
Hex codes also don’t work.
I would like to use #123456 or &#123456, but it still doesn’t work.
I’ve tried the following:

```
FormattingTags:
  # Allow the use of "[color=#123456]" RGB tags (1.16+)
  AllowRGBTags: false
  # Allow the use of "[font=uniform]" Font tags (1.16+)
  AllowFontTags: false
  # Define custom RGB formats using regex
  # Matching group 1-6 should be EACH of the characters in the RGB hex code
  # For example, the regex for "#123456" should be
  # "#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])"
  AdditionalRGBFormats: []
```

I’ve also tried setting Upgrade_Hex_To_Mini_In_Variables to true and false.
Additionally, I’ve tested the following configuration:

```
Colors:
  # Where should we let players use & or MiniMessage tags?
  # Available: anvil, book, chat, me, say, sign, prefix, nick, suffix, private_message
  Apply_On:
  - chat
  - private_message
  - me
```

But none of these worked.
I’ve also tried removing InteractiveChat, but it still didn’t work.
