### ISSUE TITLE
1.21.4: Hover color issue

### ISSUE THREAD

**Issue by Pantera07** [kangarko/ChatControl#3038]
### Are you using MySQL?

Yes

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

11.1.5

### Steps to reproduce

'formats - Hover'
Hex colors are converted to 16 colors.

```
Parts:

  channel:
    Message: "<#00C6ED>Test"
    Hover:
      - "<#00C6ED>Test"
```
