### ISSUE TITLE
Allow custom hover sections for custom world colors

### ISSUE THREAD

**Issue by malonnnn** [kangarko/ChatControl#3070]
### Summary

I use multiverse to manage my worlds. I currently use a custom variable, called `world_nick.yml` in the variables folder. It looks as follows:

```YAML
Type: format
Key: world_nick
Value: |2-

  var worldInfo = {
    hard: "<dark_red>Hard",
    hub: "<yellow>Hub",
    badlands: "<red>BadLands"
  }
  var world = player ? player.getWorld().getName() : "def";
  worldInfo[world];
Sender_Condition: '{sender_is_player}'
Sender_Permission: ''
```

How can I add hover text to my world names?  I tried something like the following and that didnt work 

```YAML
Type: format
Key: world_nick
Value: |2-
  var worldInfo = {
    hard: { name: "<dark_red>Hard", hover: "A very difficult survival world." },
    hub: { name: "<yellow>Hub", hover: "The central hub to all worlds." },
    badlands: { name: "<white>Badlands", hover: "A dangerous desert wasteland." }
  };
  var world = player ? player.getWorld().getName() : "def";
  worldInfo[world] || { name: "<gray>Unknown", hover: "Unknown world" };
Sender_Condition: '{sender_is_player}'
Sender_Permission: ''

```

```YAML
world:
  Message: "{world_nick.name}<green><bold>|<reset>"
  Hover: "{world_nick.hover}"

```

but this did not work. Is there some other way I can do it?

-------------------------------------------------------------------------------------------------------
EDIT
-------------------------------------------------------------------------------------------------------

I was informed this is the proper way to do it

```YAML
Type: format
Key: world_nick

# worldname: "<hover:show_text:'Example<br>Text'><dark_red>Fancy Name</hover>",
Value: |2-

  var worldInfo = {
    hard: "<hover:show_text:'Hard Overworld'><dark_red>H</hover>",
    hub: "<hover:show_text:'Where you first joined the server'><yellow>Hub</hover>",
    badlands: "<hover:show_text:'Where cheaters go'><red>☠</hover>"
  }
  var world = player ? player.getWorld().getName() : "def";
  worldInfo[world];
Sender_Condition: '{sender_is_player}'
Sender_Permission: ''
```
and then the chat formatting would simply be
```YAML
world:
    Message: "{world_nick}<green><bold>|<reset>"
```

Additionally, I found an additional way to achieve what I wanted purely through chat formatting, no variables needed, like so...

```YAML
Parts:
  world-hard:
    Message: "<dark_red>Hard"
    Hover: "<gray>This is a tough survival world!"
    Sender_Condition: 'player.getWorld().getName().equalsIgnoreCase("hard")'

  world-hub:
    Message: "<yellow>Hub"
    Hover: "<gray>The server hub, welcome!"
    Sender_Condition: 'player.getWorld().getName().equalsIgnoreCase("hub")'

  world-badlands:
    Message: "<white>Badlands"
    Hover: "<gray>A dangerous wasteland!"
    Sender_Condition: 'player.getWorld().getName().equalsIgnoreCase("badlands")'

  world-default:
    Message: "<gray>Unknown"
    Hover: "<gray>Unknown world"
    Sender_Condition: '!(player.getWorld().getName().equalsIgnoreCase("hard") || player.getWorld().getName().equalsIgnoreCase("hub") || player.getWorld().getName().equalsIgnoreCase("badlands"))'

```
