### ISSUE TITLE
DiscordSRV & ChatControl

### ISSUE THREAD

**Issue by Deltaria** [kangarko/ChatControl#3084]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### Question

Hello, 

I use ChatControl and DiscordSRV, here's where I'm at: 

````yaml
  List:
    standard:
      Format: chat
      Format_Spy: ‘@noprefix chat’
      Discord_Channel_Id: 1340478319354712064
    staff:
      Format: staff-chat
      Format_Spy: ‘@noprefix chat’
      Discord_Channel_Id: 1340666387063902299
````

And for DiscordSRV :

````yaml
Channels: {‘standard’: ‘1340478319354712064’, ‘staff’: ‘1340666387063902299’}
````

Except that messages from the Staff channel are sent to both channels and messages from the standard channel are sent twice.
