### ISSUE TITLE
VelocityControl 2.2.5 Not Working

### ISSUE THREAD

**Issue by ArifErdoganK** [kangarko/ChatControl#3091]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

ChatControl 11.2.5 VelocityControl 2.2.5

### Optional: Error log

Nothing error

### Steps to reproduce

Due to migrating to ChatControl v11.2.5, I purchased VelocityControl v2.2.5, but despite repeatedly checking the instructions at https://github.com/kangarko/ChatControl/wiki/proxy, messages still don't get sent to other servers. This issue did not exist in VelocityControl-3.11.7-SNAPSHOT.

Velocity **ChatControl settings.yml:**
```
Server_Aliases:
  faction-klan: Merkez
  faction-arsa: Arsa
  faction-arsa2: Arsa2
  faction-arena: Arena
  faction-boss: Boss
  faction-hammadde: Hammadde
  faction-event: Event
  faction-duello: Duello
```

**Velocity.toml:**
```
[servers]
    "faction-arena" = ""
    "faction-duello" = ""
    "faction-arsa" = ""
    "faction-hammadde" = ""
    "faction-event" = ""
    "faction-arsa2" = ""
    "faction-boss" = ""
    "faction-klan" = ""
    "faction-build" = ""
```

Bukkit **ChatControl settings.yml:**
```
  List:
    standard:
      Format: chat
      Format_Spy: '@noprefix chat'
      Format_Console: '[Klan] {pl_prefix}{player}&8: &f{message}'
      Proxy: true
```

Bukkit **ChatControl proxy.yml:**
```
Enabled: true
Prefix: "<dark_gray>[<yellow>{server_name}<dark_gray>] <gray>"
Server_Name: 'faction-klan'
```
