### ISSUE TITLE
1.21.4: Help with Bentobox

### ISSUE THREAD

**Issue by 00Hrtz** [kangarko/ChatControl#3096]
### Are you using MySQL?

No

### Are you using a proxy?

No

### Question

Hi

```yaml
    skysurvival:
      Format: skysurvival-chat
      Format_Spy: '@noprefix chat'
      Party: bentobox-island-coop, bentobox-island-trusted, bentobox-island-member, bentobox-island-subowner, bentobox-island-owner, bentobox-island-mod and bentobox-island-admin      
      Range: '*'
      Range_Worlds:
      - bskyblock_world
      - bskyblock_world_nether
      - bskyblock_world_the_end

```
Is this the correct way, above is my chat channel for bentobox skyblock world, not sure if adding party to it is the correct way or do i need to create another channel for party chat?
