### ISSUE TITLE
Bungee

### ISSUE THREAD

**Issue by ScottGB** [kangarko/ChatControl#311]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

I have set up my bungeecord system exactly as posted on the wiki. Chat is sending from all servers, however, I cannot join other channels, or tab complete others. Channel list also says there are no players. Please see screenshots:

![image](https://user-images.githubusercontent.com/59319698/102679731-c24c7080-41a9-11eb-878e-8dc3d007da09.png)

![image](https://user-images.githubusercontent.com/59319698/102679735-caa4ab80-41a9-11eb-8edb-59a6344cb297.png)

![image](https://user-images.githubusercontent.com/59319698/102679739-dabc8b00-41a9-11eb-8c2a-296cb0f38fa4.png)

Debug.zip is attached to my previously raised issue.

No errors in either consoles and connecting through bungee.

**Comment by ScottGB** [comment]
Can anyone else reproduce?

**Comment by ElBananaa** [comment]
Hey! Since I don't have a bungee setup, I couldn't try it. However, you should take a look at this video, it might help you:
https://www.youtube.com/watch?v=EKziLXSjwhY

**Comment by ScottGB** [comment]
Hey @ElBananaa ,

Thanks for that, I have actually been through that video a couple of times in a desperate hope that I missed something, unfortunately I've followed everything to the letter as far as I'm aware.

Cheers

**Comment by ElBananaa** [comment]
That's weird. Do you have any error in the server/plugin logs?

**Comment by ScottGB** [comment]
@ElBananaa 

Strangely not. I used the "debug" config setting to try self-diagnose too, and still couldn't work it out.

**Comment by ElBananaa** [comment]
> @ElBananaa
> 
> Strangely not. I used the "debug" config setting to try self-diagnose too, and still couldn't work it out.

Hey! I wonder, which version of the plugin are you using? Also, could you provide your config folders (for chatcontrol and bungeecontrol)?

**Comment by ScottGB** [comment]
@ElBananaa

I'm using the latest version (10.1.9 according to mc-market), and I'll be happy to provide. Here's the debug from my other issue:
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5713404/debug.zip)

BungeeControl config:
https://pastebin.com/W7g9n6Mx

**Comment by ElBananaa** [comment]
> @ElBananaa
> 
> I'm using the latest version (10.1.9 according to mc-market), and I'll be happy to provide. Here's the debug from my other issue:
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5713404/debug.zip)
> 
> BungeeControl config:
> https://pastebin.com/W7g9n6Mx

Thanks, I'll take a look at it. Also, are you sure you defined a different name for each server in the server.properties?

**Comment by ScottGB** [comment]
@ElBananaa 

Absolutely certain, triple checked bungee config and server.properties for each

**Comment by ElBananaa** [comment]
> @ElBananaa
> 
> Absolutely certain, triple checked bungee config and server.properties for each

That's really weird, I'm not a pro of the plugin config, but I'll take a look asap.

**Comment by ElBananaa** [comment]
> @ElBananaa
> 
> Absolutely certain, triple checked bungee config and server.properties for each

Are you using BungeeControl or BungeeControl-Red?
Also, could you try placing the aliases inside quotes? Like the example below:
```
# -------------------------------------------------------------------------------------------------
# Server name aliases used when broadcasting messages below
# You can edit the sections and remove old keys below.
# Put the server name (see header) as the key, and its alias as the value.
# -------------------------------------------------------------------------------------------------
Server_Aliases:
  lobby: "hub"
  server1: "mainserver"
  server2: "secondserver"
```
