### ISSUE TITLE
1.21.4: Disabled ProtocolLib?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#3113]
### Are you using MySQL?

No

### Are you using a proxy?

No

### Question

Hello, I tried to disable protocollib in config:
```yml
# ProtocolLib integration.
# -------------------------------------------------------------------------------------------------
ProtocolLib:
  
  # Removes vanished players from tab-completion and allows deleting chat messages.
  # Disable if using ViaVersion or ProtocolSupport and players are getting kicked out.
  #
  # **NOTICE** Since this stores every chat packet for each online player to make the [X] message 
  # feature work, it can potentially take up more RAM on large networks. This, in most cases, won't
  # affect plugin's performance.
  Enabled: false

```

But by the Spark results:

![Image](https://github.com/user-attachments/assets/2c3d8dd0-29f5-4854-9ea0-849903995df2)

![Image](https://github.com/user-attachments/assets/649be389-96c0-4240-bee1-022969928eba)
https://spark.lucko.me/ocSVNJlpdH

Chatcontrol is still used by protocollib

even when I run:
/protocollib:protocol timings

It shows:
```yml
Started: Sun Mar 23 14:23:16 UTC 2025
Stopped: Sun Mar 23 15:02:39 UTC 2025 (after 2362 seconds)

=== PLUGIN ChatControl ===
 TYPE: SYNC_OUTBOUND 
 -------------------------------------------------------------------------------------------------------------------------------------------
 Protocol:      Name:                         Count:       Min (ms):       Max (ms):       Mean (ms):      Std (ms): 
 -------------------------------------------------------------------------------------------------------------------------------------------
 PLAY           WINDOW_ITEMS                  10280        0.002550        29.940220       0.147592        0.449396 
 PLAY           SET_SLOT                      98102        0.000060        15.328252       0.007503        0.060378 
 PLAY           OPEN_WINDOW_MERCHANT          3            0.081790        0.388957        0.264175        0.161482 
 SUM            -                             108385       0.000060        29.940220       0.020798        0.155370 
 => Time on main thread: 2254.142492 ms
 -------------------------------------------------------------------------------------------------------------------------------------------

```

why is it still used & how can I disable it? Why it's checking SET_SLOT or WINDOW_ITEMS when I guess this is not needed by the chat plugin? And when I had disabled protocollib?
