### ISSUE TITLE
Discord sends to, but doesn't read from second channel

### ISSUE THREAD

**Issue by saschahi** [kangarko/ChatControl#312]
Problem:
- The bot sends messages between the global channel without a hitch
- The bot reads messages from ingame and sends them to the second configured channel, but doesn't read messages from this second discord channel
- (might not be a error?) the events like players joining, leaving, advancements etc. also don't show up in this second channel

config snippets:

Channels:
  ... 
  List:
    admin:
      Format: admin-chat
      Format_Console: '[A-chat {player}] {message}'
    global:
      Format: chat
      Format_Spy: '@noprefix chat'
      Discord: true
    german:
      Format: chat-german
      Format_Spy: '@noprefix chat'
      Discord: true
...
Integration:
  ... 
  Discord:
    Connected_Channels:
      547899355609169982: global
      789681107029065770: german

**Comment by broken1arrow** [comment]
> Problem:
> 
> * The bot sends messages between the global channel without a hitch
> * The bot reads messages from ingame and sends them to the second configured channel, but doesn't read messages from this second discord channel
> * (might not be a error?) the events like players joining, leaving, advancements etc. also don't show up in this second channel
> 
> config snippets:
> 
> Channels:
> ...
> List:
> admin:
> Format: admin-chat
> Format_Console: '[A-chat {player}] {message}'
> global:
> Format: chat
> Format_Spy: '@NoPrefix chat'
> Discord: true
> german:
> Format: chat-german
> Format_Spy: '@NoPrefix chat'
> Discord: true
> ...
> Integration:
> ...
> Discord:
> Connected_Channels:
> 547899355609169982: global
> 789681107029065770: german

Has you add this in format?

```
  discord-prefix:
    Message: '&8[&9Discord&8] &f'
    Sender_Condition: '{sender_is_discord}'
    Hover:
    - '&bJoin our Discord at mineacademy.org/discord'
    Open_Url: https://mineacademy.org/discord
```

**Comment by saschahi** [comment]
chat.yml and chat-german.yml both have this
```
  discord-prefix:
    Message: '&8[&9Discord&8] &f'
    Sender_Condition: '{sender_is_discord}'
    Hover:
    - '&bJoin our Discord at discord.gg/BpDyqhNaVM'
    Open_Url: https://discord.gg/BpDyqhNaVM
```
