### ISSUE TITLE
Purpur 1.21.5: Factions Relational placeholder wierd behaviour

### ISSUE THREAD

**Issue by goldenartur** [kangarko/ChatControl#3172]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

11.3.5

### ZIP of "/chc debug"

https://ufile.io/ksl59dqr

### Steps to reproduce

factions relational placeholder {rel_factionsuuid_relation_color} outputs the color but also  adds "color" text and the color doesnt continue after the color text, the color the was before continues.

  prefix:
    Message: '{luckperms_prefix}<yellow>TEST</yellow> '
    Hover:
    - '&r{luckperms_meta_prefix_legacy} {player_name}'
    - ''
    - ':click_action_left: &8> <#9ECCA4>Vajuta poe avamiseks.'
  factionsprefix:
    Message: '{rel_factionsuuid_relation_color}TEST{factionsuuid_player_role}'
    Sender_Condition: '''%factionsuuid_player_role_name%'' != ''None'' && {sender_is_player}'

![Image](https://github.com/user-attachments/assets/6616494c-66d2-47b8-85ff-464636201ff0)

It should output just the color which in my example should be &a and make the icon/text i have after "color" green but it creates color text which is only green and nothing else.

**Comment by MotikaCraft-TheJoshua** [comment]
I confirm this happening too, in my case i tested on softwares:
- Paper 1.8.8
- Carbon (paid fork) 1.8.8

Same CHC version as OP

Test:
![Image](https://github.com/user-attachments/assets/35268653-057a-4284-90e1-91ac65bfa589)

config part:
```
Message: 'e {rel_factionsuuid_relation_color} e {factionsuuid_faction_name}'
```

**Comment by kangarko** [comment]
Hey hey, apologizes for the big delay, I am gonna be getting present with this together with my new colleague @devpedrobarbosa within 24 hours.

**Comment by MotikaCraft-TheJoshua** [comment]
@goldenartur @kangarko this issue should be renamed to generalize issue with relational placeholders, because this issue happens with any relational placeholders being used in chc, not only factions one

**Comment by kangarko** [comment]
Thanks guys and apologize for the wait, I fixed it. Closing!

**Comment by MotikaCraft-TheJoshua** [comment]
> Thanks guys and apologize for the wait, I fixed it. Closing!

Hello, thanks
However i see this happening now, something broke

before updating to commit `ed71d79` (this is version release BBB 11.3.5):
![Image](https://github.com/user-attachments/assets/4bf9b33f-7823-487c-9f94-d4f3c4e90b3b)

after updating to commit `ed71d79`:
![Image](https://github.com/user-attachments/assets/95bfc770-870d-4e13-acbe-c47840affef8)

**Comment by MotikaCraft-TheJoshua** [comment]
I don't want to be bothering or something, i just want to say that it's ok to wait, but would be cool if somehow you missed the notification, to be able to trigger something just to remind you, talking for example about this. As i said, nobody is in a hurry but it's cool to just remind for safety if notification has not been seen or whatever

![Image](https://github.com/user-attachments/assets/d9b3d917-f31d-4328-877e-51ed8566c0fa)

Thanks

**Comment by kangarko** [comment]
Hey! We see all notifications. @devpedrobarbosa please check it out. Pedro did you get the notification too?

**Comment by MotikaCraft-TheJoshua** [comment]
Sorry to bother, any news?

**Comment by devpedrobarbosa** [comment]
Hey there!

Sorry for the delay.
I am currently working on trying to reproduce this issue.

It will be fixed as soon as possible.

Thanks.

**Comment by MotikaCraft-TheJoshua** [comment]
i will send you the format i am using, this is the only part i have on my server

```yml
  chat_message:
    Sender_Condition: '!{sender_is_discord}' # && "{luckperms_primary_group_name}" != "Admin"'
    Receiver_Condition: '"{parseother_{{sender_name}}_{player_has_permission_chat.tranquilized}}" == "no" || "{parseother_{{sender_name}}_{player_has_permission_chat.tranquil.exempt}}" == "yes" || "{player_name}" == "{sender_name}" || ("{player_has_permission_chat.tranquil.see}" == "yes" && "{parseother_{{sender_name}}_{player_has_permission_chat.tranquilized}}" == "no")'
    #Message: '{luckperms_meta_username_color}{player_chat_color}{player_chat_decoration}{message}'
    Message: '{luckperms_meta_chat_color}{luckperms_meta_chat_color_forced}{luckperms_meta_chat_format_forced}{message}'
```

this worked always, never broke, until this release to fix relational placeholder is pushed...

As soon as i remove Receiver_Condition, it works

i'll need to do debugging on this and will get asap to here

**Comment by MotikaCraft-TheJoshua** [comment]
Empty chat when i send messages with config i am sending below in this same github comment
![Image](https://github.com/user-attachments/assets/586495ae-65b6-4019-a8a7-5e0f0f6fdbc5)

```yml
  chat_message:
    Sender_Condition: '!{sender_is_discord}' # && "{luckperms_primary_group_name}" != "Admin"'
    Receiver_Condition: '"{player_name}" == "{sender_name}"'
    #Message: '{luckperms_meta_username_color}{player_chat_color}{player_chat_decoration}{message}'
    Message: '{luckperms_meta_chat_color}{luckperms_meta_chat_color_forced}{luckperms_meta_chat_format_forced}{message}'
```

Is Receiver_Condition broken? because if i remove Receiver_Condition and then i put {player_name} placeholder and {sender_name} placeholder directly into "Message: <here>", it properly shows sender's name, so it should work, because player name is correct to sender name, so i assume it's Receiver Condition that is broken?
