### ISSUE TITLE
Paper 1.21.4: Formatting chats issues

### ISSUE THREAD

**Issue by Xantam-13** [kangarko/ChatControl#3178]
### Are you using MySQL?

No

### Are you using a proxy?

No

### Question

I am trying to make my messages in game as interactive as possible, including utilising the "hover over" aspect and whatnot. 

I have come up with this below, but it's throwing errors out. I will paste those errors too. I have used an online yaml editor/fixer but that makes it even worse, genuinely ... 

I have followed guidance from the below sites, but it just doesn't seem to work? Please advise :) 

Guides followed: 
https://docs.mineacademy.org/chatcontrol/channels.html
https://docs.mineacademy.org/chatcontrol/formats.html
https://imgur.com/SuHB3JS

My code in a chat (trade-chat.yml)
```
# If true, each section in Parts will begin on a new line automatically.
New_Line_Per_Part: false

# The parts of this format.

Parts:
    PlayerName: 
      Message: "{player_name}"
      Hover: "&7Click to Message"
      Suggest_Command: "/tell {player_name}"
 
    Prefix: 
      Message: "{factions_faction}"
      Hover: 
        "&7{player_prefix+}{player_name} {player_suffix}"
        "&7Faction&8: {factions_faction}"
        "&7Custom Role&8: {factions_title}"
        "&7Role&8: {factions_role}"
        "&7Online Members&8: {factions_onlinemembers}"
 
    Message: 
      Message: "<gray>[<gold>{player_channel}<gray>] <gray>[<white>{factions_faction}:{factions_role}<gray>] {player_prefix+}{player_name}<WHITE>)<gray>: <white>{message}"
```
