### ISSUE TITLE
Paper 1.8.8-1.12.2: Hover text acting weird

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [kangarko/ChatControl#3191]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

11.3.6

### Optional: Error log

/

### ZIP of "/chc debug"

I have clean install, only connected mysql to database, and added this formatting part:

```yml
  edition-java:
    Sender_Condition: '!{sender_is_discord}'
    Message: '&8[&a&lJE&r&8] &r'
    Hover:
      - '<gray><italic>Ovaj igrac trenutno pristupa serveru putem</italic></gray> <green><bold>Java Edition</bold></green> <gray><italic>klijenta</italic></gray>'
```

### Steps to reproduce

1. Install ChatControl 11.3.6
2. Apply next formattings (first test one, then test another):

```yml
  edition-java:
    Sender_Condition: '!{sender_is_discord}'
    Message: '&8[&a&lJE&r&8] &r'
    Hover:
      - 'Ovaj igrac trenutno pristupa serveru putem Java Edition klijenta'
```
with this, this should be output:
![Image](https://github.com/user-attachments/assets/54928e0e-d4f1-4aee-8698-565de0500417)

and
```yml
  edition-java:
    Sender_Condition: '!{sender_is_discord}'
    Message: '&8[&a&lJE&r&8] &r'
    Hover:
      - '<gray><italic>Ovaj igrac trenutno pristupa serveru putem</italic></gray> <green><bold>Java Edition</bold></green> <gray><italic>klijenta</italic></gray>'
```
with this, this should be output:
![Image](https://github.com/user-attachments/assets/e95dd125-9b32-4404-89a1-c134a5a1e49e)

---------------

You can see the difference, this was not happening previously

**Comment by MotikaCraft-TheJoshua** [comment]
I apologize for the oversight, this is happening on Paper 1.8.8 - 1.12.2, i have just tested, i thought it was my Paper 1.21.4 test server

**Comment by devpedrobarbosa** [comment]
Hi @MotikaCraft-TheJoshua.

What happens is: **_Legacy Minecraft_** has a limit of `55 characters` per hover line. So, if your line is > 55 chars long, ChatControl will break it down as needed with line breakers (`\n`). Those new lines will have no color attached to them, probably causing weird bugs like the ones you showed and I was able to reproduce here.

So, what I would recommend is to break the lines by yourself, keeping in mind that `55 chars` limit.
Obs: the limit is considered without mini tags (`<>`)

Currently, the default plain gray styling is only applied to the first line of the part. That means if you have this setup:

![Image](https://github.com/user-attachments/assets/a5f843e0-f7b6-4b20-99ba-0aad59bc4237)

It will come up like this:

![Image](https://github.com/user-attachments/assets/79a5615b-4da3-4316-bc66-62d0dd4b72fd)

For now, do this instead:

![Image](https://github.com/user-attachments/assets/9be26838-e51d-42f0-bda3-a0c6325886d0)

This specific part will be patched asap, though.

Thanks for sharing that.

**Comment by MotikaCraft-TheJoshua** [comment]
> Hi [@MotikaCraft-TheJoshua](https://github.com/MotikaCraft-TheJoshua).
> 
> What happens is: **_Legacy Minecraft_** has a limit of `55 characters` per hover line. So, if your line is > 55 chars long, ChatControl will break it down as needed with line breakers (`\n`). Those new lines will have no color attached to them, probably causing weird bugs like the ones you showed and I was able to reproduce here.
> 
> So, what I would recommend is to break the lines by yourself, keeping in mind that `55 chars` limit. Obs: the limit is considered without mini tags (`<>`)
> 
> Currently, the default plain gray styling is only applied to the first line of the part. That means if you have this setup:
> 
> ![Image](https://github.com/user-attachments/assets/a5f843e0-f7b6-4b20-99ba-0aad59bc4237)
> 
> It will come up like this:
> 
> ![Image](https://github.com/user-attachments/assets/79a5615b-4da3-4316-bc66-62d0dd4b72fd)
> 
> For now, do this instead:
> 
> ![Image](https://github.com/user-attachments/assets/9be26838-e51d-42f0-bda3-a0c6325886d0)
> 
> This specific part will be patched asap, though.
> 
> Thanks for sharing that.

Hello, thanks for fast response
i think you did not fully cover my concerns

i hope you see the difference

![Image](https://github.com/user-attachments/assets/3a0b2c8e-af50-495f-ab9b-d3ff61b60dfc)

![Image](https://github.com/user-attachments/assets/23660ab8-7375-4f2c-98d8-2f528b09d6ea)

This is on the SAME server (1.8-1.12), with different formats, same text, i just formatted it differently - i hope you now understand better what i am talking about - same text different coloring 

I am talking more about this
```yml
  edition-java:
    Sender_Condition: '!{sender_is_discord}'
    Message: '&8[&a&lJE&r&8] &r'
    Hover:
      - '<gray><italic>Ovaj igrac trenutno pristupa serveru putem</italic></gray> <green><bold>Java Edition</bold></green> <gray><italic>klijenta</italic></gray>'
```

because this colored and formatted, it is no different text than the first one i showed above and you sent, is it counting all the formatting now? you said 55 chars limit, is it counting even "<" and ">" and "gray" and "italic" etc, for this?

**Comment by devpedrobarbosa** [comment]
@MotikaCraft-TheJoshua 
Take a look at what is going on:

![Image](https://github.com/user-attachments/assets/8fcc3284-5bd1-4d1d-8ad9-8ad6091308df)

So the line which length is used to decide wether wrapping or not is the stripped one. Though, when it comes to actually breaking the line down, it obviously  has to break down the original line with the tags, otherwise styling would be lost.

I am not sure that the logic of breaking down the line is 100%, will verify that.

I tried doing this:

```
  edition-java:
    Sender_Condition: '!{sender_is_discord}'
    Message: '&8[&a&lJE&r&8] &r'
    Hover:
      - '&7&oOvaj igrac trenutno pristupa serveru putem &a&lJava Edition &7&oklijenta'
```

And this happened:

![Image](https://github.com/user-attachments/assets/6c045a6a-1fad-4e5f-8233-3060f6ee57ed)

That is one solution for now: using either legacy color codes or short mini tags.
Also, do the wrapping yourself it auto wrapping is messing it up.

I don't know if theres is a reason for that feature to exist and specially for it not to be configurable.
I will investigate it further and report any changes on that to you.
