### ISSUE TITLE
All: Prevention of players from using ANY mini-tags in messages

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [kangarko/ChatControl#3196]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### Question

This is one example:
![Image](https://github.com/user-attachments/assets/7f9f36db-b737-40a0-a7d9-5889b04abe2a)

This could be more dangerous with clicking commands or even opening URLs, especially if the player base is big and there are no staff online to handle things out 24/7, even though there is that pop-up MC screen when you click a message that could open URL, this is still a bit scary and if the player is young they do not know what they're doing...

I suggest there should be in main config an option to define a list of all minitags that are whitelisted, similar to how you made colors to function in every defined entry in the list

```yml
Colors:
  
  # Where should we let players to use & or MiniMessage tags?
  # Available: anvil, book, chat, me, say, sign, prefix, nick, suffix, private_message
  #
  # [NOTICE] If anvil is enabled, we will always filter colors according to player's permission,
  #          so custom items will lose their colors unless player has permissions to use them.
  Apply_On:
  - chat
```

We could make this like

```Mini_Tags_In_Chat:

  # Whitelist certain minitags to allow them to be used in chat messages sent by player.
  # Only the defined tags will be available for use, others will be ignored if someone type them out
  # You can also define rules to handle this in more detailed way

  Tags:
  - bold
  - b
  - italic
  - i
  - st
  - green # potentially we could just use "all_colors" and this would allow us to use all <color> tags, only that, but of course allow for manually adding each color if for some reason some is not allowed on the server like black....
  - dark_green
```

As you can see on the 3rd comment line, i wrote that, assuming this could also be handled via rules, but i am not sure(???) because these tags are processed by the plugin, like, they are not even seen by the player after sending the message because they've been processed by the plugin, so this suggestion should be taken as assumption too
