### ISSUE TITLE
Gradient in format is broken

### ISSUE THREAD

**Issue by PSYCHEER** [kangarko/ChatControl#3205]
### Are you using MySQL?

Yes

### Are you using a proxy?

Yes - Velocity

### "/version ChatControlRed" - plugin version

11.3.6

### ZIP of "/chc debug"

[debug.zip](https://github.com/user-attachments/files/20909858/debug.zip)

I've removed mysql username and IP as it's not needed for this

### Steps to reproduce

It should look like this

![Image](https://github.com/user-attachments/assets/b1c39f2f-7c07-449c-a8cc-f2b8370de9d9)

But intead I'm getting plain colors

![Image](https://github.com/user-attachments/assets/a3782181-8180-4ce6-87eb-1f531046ef25)

When I've removed ALL of legacy color to use MiniMessage only I've got

![Image](https://github.com/user-attachments/assets/b18522ef-2249-4cfc-882e-8392b0b81394)

Another problem is
`Gradient` doesn't support hex codes but only named colors like GOLD, but not #FFAA00

+ missing TAB sorting

**Comment by devpedrobarbosa** [comment]
Hi @PSYCHEER,

Will be checking this one asap.

Thanks!

**Comment by devpedrobarbosa** [comment]
@PSYCHEER
`Gradient` actually supports HEX colors.

I think I've got the output you were expecting:

![Image](https://github.com/user-attachments/assets/5bf304f6-5d11-433e-ae49-1afbc3c24b26)

And this is how I did it:

```
New_Line_Per_Part: false
Parts:
  one:
    Message: '<bold>PÚTNICI'
    Gradient: '#FFAA00 - #AA0000'
  two:
    Message: '&4&l: %online% &7| '
  three:
    Message: '<bold>ŠĽACHTA'
    Gradient: '#AA0000 - #FFAA00'
  four:
    Message: '&6&l: %staffonline%'
```

Here are some considerations:
1. If you're using the `Gradient` property, don't use legacy colors on `Message`, stick to mini tags.
2. Your setup with `<gradient>` tags is working perfectly fine, the problem is: your text is too short to visualize the gradient. That's the way Adventure works, I guess.

Example:
```
    Message:
       - '<gradient:#FFAA00:#AA0000>&l__________________________________________</gradient>'
```

Output:

![Image](https://github.com/user-attachments/assets/8abe0001-3bdb-41b3-a249-25cad3ba3788)

Please let me know if you managed to work it out!

Thanks.
