### ISSUE TITLE
[Issue] Translation of realname description

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#358]
I translated the description line and performed /chc reload, for the other description lines this works but it doesn't for the new realname command that was added today.

```
Real_Name:
    Usage: '[name/nick]'
    Description: Bekijk de speler zijn/haar minecraft naam via de nickname.
    Success: '''Speler {0} heeft de '' + (hasNick ? ''nick {1}'' : ''geen nick'') + ''&7.'''
```

![image](https://user-images.githubusercontent.com/5664135/103037504-4452e580-456c-11eb-8c40-b913853f0133.png)
