### ISSUE TITLE
World Prefix / Placeholder?

### ISSUE THREAD

**Issue by 00Hrtz** [kangarko/ChatControl#376]
How do i put my World Prefix Placeholder in to a Format file, I've checked the wiki but theres nothing on world prefix, only player prefix.

I know how to add the world placeholder,  i just need to know how to add it before 'Prefix' in the format file. I don't want it placed in the prefix section as that's where my luckperms group prefix is.

**Comment by 00Hrtz** [comment]
Can i have two Prefix sections? example:

  prefix:
    Message: '&7{world}'
    Hover:
    - '&7{world}'
  prefix:
    Message: '&7{pl_prefix+}'
    Hover:
    - '&7{pl_prefix+}'
    - '&7Ping&8: &f{ping}ms'
    - '&7Rank&8: &f{player_group}'
    - '&7Posted: &f{timestamp}'

**Comment by ElBananaa** [comment]
> Can i have two Prefix sections? example:
> 
> prefix:
> Message: '&7{world}'
> Hover:
> - '&7{world}'
> prefix:
> Message: '&7{pl_prefix+}'
> Hover:
> - '&7{pl_prefix+}'
> - '&7Ping&8: &f{ping}ms'
> - '&7Rank&8: &f{player_group}'
> - '&7Posted: &f{timestamp}'

Hey! Merry Christmas!
Of course, you can place it before your prefix section, and you could name the sections as you wish.
Simply place a new section named, as example, world, before your actual prefix section.
It would look like that: 
```
Parts:
  world-prefix:
    Message: '&7{world}'
    Hover:
    - '&7{world}'

  player-prefix:
    Message: '&7{pl_prefix+}'
    Hover:
    - '&7{pl_prefix+}'
    - '&7Ping&8: &f{ping}ms'
    - '&7Rank&8: &f{player_group}'
    - '&7Posted: &f{timestamp}'
```

Let me know if it answered your question, so I can close this issue. :)
