### ISSUE TITLE
1.16.4 cant use more an 2 hover and Suggest_Command, Message work on Third_Part

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl#38]
I post the setup here, (ignore some placeholders has not install more plugin an you recommended). 

```
Parts:

  # See the chat.yml format file for a tutorial on how this works.
  everything:
    Message: '&b[Globalt]&r {luckperms_prefix_element_highest} '
    Hover:
      - '&8*-----* &5{player} &8*-----*'
      - '&7Medelande sänt: &b{timestamp}'
      - '&7Värld&8: &b{world}'
      - '&aKlicka för karta'
    Open_Url: http://Midgardsaga.nu:8365
  Second_Part:
    Message: '&9{player}&7&f'
    Hover:
      - '&7Rank&8: &b{pl_group}'
      - '&7Bor i:&8 {lands_land_name}'
      - '&7Första spel datum&8: &b{player_first_join_date}'
      - '&7Speltid totalt&8: &b{cmi_user_playtime_hoursf} timmar'
      - '&aKlicka för privat medelande'
    Suggest_Command: '/msg {player} '
  Third_Part:
    Message: '&7: &f{message}'
    Hover:
      - '&7Message issued: &b{timestamp}'
      - '&aKlicka för at telepotera till {player}'
    Suggest_Command: /tpa {player}

```

**Comment by kangarko** [comment]
Minecraft only supports 1 suggest_command, 1 run_command and 1 open_url, if that's what you meant. Comment below if you need anything.

**Comment by broken1arrow** [comment]
> Minecraft only supports 1 suggest_command, 1 run_command and 1 open_url, if that's what you meant. Comment below if you need anything.

strange 2 work fine and on version 8 work this with no issue with all three. 

Or is it a limit in 16.4?

**Comment by kangarko** [comment]
Please post me your config from ChatControl 8 where you use multiple of these.

**Comment by broken1arrow** [comment]
````
  Private_Message_Sender:
    Everything:
      Message: '&5✉ &8{sender}'
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - '     &8~ &3Private Message &8~     '
        - '&8&oSent {timestamp}'
        - '&3Sender: &f{sender}'
        - '&3Receiver: &f{receiver}'
        - '&3Body: &f{message}'
        - '&aKlicka för att skriva till &9{player_name}'
      Click_Event:
        Action: SUGGEST_COMMAND
        Value: /msg {player_name}
    Second_Part:
      Message: ' &a☞&6'
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - '     &8~ &3Private Message &8~     '
        - '&aKlicka för att telepotera till &9{player_name}'
      Click_Event:
        Action: SUGGEST_COMMAND
        Value: /tpa {player_name}
    Third_Part:
      Message: ' {receiver}: &d&l{message}'
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - '     &8~ &3Private Message &8~     '
        - '&8&oSent {timestamp}'
        - '&3Sender: &f{sender}'
        - '&3Receiver: &f{receiver}'
        - '&3Body: &f{message}'
        - '&aKlicka för att skriva till &9{player_name}'
      Click_Event:
        Action: SUGGEST_COMMAND
        Value: /msg {player_name}

````
