### ISSUE TITLE
can change what different staff can spy on or not.

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl#402]
the ability to set different permissions for spy, for different staff.

What I mean is, be able to choose which channels and if they are to be able to spy on books and commands.

**Comment by ElBananaa** [comment]
Hey!

Thanks for your suggestion!
It would actually be cool to have more permissions related to spy to make this feature a bit more modular.

Have a nice day! :)

**Comment by kangarko** [comment]
Thanks! However I believe once you give someone spying permissions they must be trusted enough to be able to spy everywhere, if you dont trust them dont let them manage your server. Splitting this into multiple perms is not the direction I want to take the plugin.

**Comment by broken1arrow** [comment]
> Thanks! However I believe once you give someone spying permissions they must be trusted enough to be able to spy everywhere, if you dont trust them dont let them manage your server. Splitting this into multiple perms is not the direction I want to take the plugin.


Is not so much I do not trust them, but so they do not change so they do not spy on certain channels for example (have a little more control over it) and if some players not want get spammed with commands or only some groups shall se this, becus is not necessary all staff have to see this  (not all is soo good on command and know how to change this).

Do not know if it is already possible to do partly with perms that already exist.

Do you know how how vanish works in eg cmi? There you have settings that you can select default and then choose whether players should be able to change the ingame with command or not. 

I can block the command, but is not soo nice solution (so one perm for use spy command). And something similar too this i think of for default spy settings. But if it are to much work, I have to solve this other ways. 

```
  # Defines default states of spy options for players
  # This will not have any effect if player already edited his spy mode with command/gui
  Defaults:
    channels: true
    book: false
    commands: false
    anvil: false

```
