### ISSUE TITLE
1.16.4: Centering messages?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#404]
Hi guys, please, how it's possible to center messages?

Citation from changelog page:
> New | Prefixes , <title>, , and that are optional and work for almost any message that'll send it in new ways or will center it!

I've tried for ex. this in PM_sender format but it doesn't work...
`    - '<title> &8~ &3Soukromá zpráva &8~</title>'`
![image](https://user-images.githubusercontent.com/18662086/103229794-18e94580-4934-11eb-973e-142571e43363.png)

**Comment by ElBananaa** [comment]
> Hi guys, please, how it's possible to center messages?
> 
> Citation from changelog page:
> 
> > New | Prefixes , <title>, , and that are optional and work for almost any message that'll send it in new ways or will center it!
> 
> I've tried for ex. this in PM_sender format but it doesn't work...
> ` - '<title> &8~ &3Soukromá zpráva &8~</title>'`
> ![image](https://user-images.githubusercontent.com/18662086/103229794-18e94580-4934-11eb-973e-142571e43363.png)

Hey!

In order to center messages, take a look at this page: https://github.com/kangarko/ChatControl-Red/wiki/Alternative-Messages

You need to use the `<center>` tag before your message. Also, you don't need to escape this tag at the end of the line.

Have a nice day! :)

**Comment by bobhenl** [comment]
But why is this happening please? @ElBananaa ?
![image](https://user-images.githubusercontent.com/18662086/103230561-0d971980-4936-11eb-8050-ce7ec60f1cf3.png)
This is not center
```
  Second_Part:
    Message: "&f{message}"
    Hover:
    - '<center>&8~ &3Soukromá zpráva &8~'
    - '&7&oOdeslána v &e{localtime_time_k:m:s}'
    - '&3Příjemce: &e{receiver}'
    - ''
    - '&7Klikni pro další zprávu.'
    Suggest_Command: '/r '
```
