### ISSUE TITLE
1.16.4: Placeholders like in chat format in receiver and sender formats

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#405]
Hi, is it possible to transfer these placeholders from chat to sender format? I don't know how to show these placeholders as from sender and as from receiver, may via papi placeholder https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#parseother 
`%parseother_{receiver/sender}_{placeholder_mentioned_down}%`

but isn't there another better way?

I wanna use these from chat format:
```
    - '&8&l▄▄▄ {pl_prefix+} &7{player} &8&l▄▄▄'
    - '&7Tajemný prach &8» &e{gadgetsmenu_mystery_dust}'
    - '&7Tajemné truhly &8» &e{gadgetsmenu_mystery_boxes}'
    - '&7Odehráno &8» &e{statistic_hours_played}&7h'
    - '&7Registrace &8» &e{player_first_join_date}'
```
in PM receiver and sender formats, so implement it here:
```
  First_Part:
    Message: '&c&l✉ ty &e→ {receiver}:'
    Hover:
    - '&8&l▄▄▄ {pl_prefix+} &7{receiver} &8&l▄▄▄'  #prefix won't be probably from receiver
    - '&7Tajemný prach &8» &e{gadgetsmenu_mystery_dust}' #placeholders wont be from receiver
    - '&7Tajemné truhly &8» &e{gadgetsmenu_mystery_boxes}'
    - '&7Odehráno &8» &e{statistic_hours_played}&7h'
    - '&7Registrace &8» &e{player_first_join_date}'
    - ''
    - '&7Odeslat zprávu jinému hráči.'
    Suggest_Command: '/msg '
  Second_Part:
    Message: "&f{message}"
    Hover:
    - '     &8~ &3Soukromá zpráva &8~     '
    - '&7&oOdeslána v &e{localtime_time_k:m:s}'
    - '&3Příjemce: &e{receiver}'
    - ''
    - '&7Klikni pro další zprávu.'
    Suggest_Command: '/r '
```
