### ISSUE TITLE
1.16.4 | spy on channels not work properly

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl#41]
I try range (I have set up) and your chat.yml (I run /spy toggle chat "chatname" and it say i spy on the channel). But not use this part

```
spies-prefix: 
    Message: "&8[&5Spy&8] &f"
    Receiver_Condition: "{receiver_is_spying_{channel}}"
    Hover: "&dClick to stop spying {channel} channel."
    Run_Command: "/{label_spy} toggle chat {channel}"
```

**Comment by kangarko** [comment]
Sorry I cannot reproduce. How to find this bug?

<img width="831" alt="Screenshot 2020-11-12 at 19 57 02" src="https://user-images.githubusercontent.com/1918426/98983580-4499a300-2521-11eb-9045-e3fc0b2cfff9.png">

Here is my config: 
<img width="845" alt="Screenshot 2020-11-12 at 19 57 49" src="https://user-images.githubusercontent.com/1918426/98983639-5c712700-2521-11eb-8c0c-ed2fa485b8aa.png">

How can I find this problem please?

**Comment by kangarko** [comment]
I was spying everything

**Comment by broken1arrow** [comment]
Hm good question, is not the only problem.

**Comment by kangarko** [comment]
Please only report one bug per Issue ticket. So how can I reproduce this problem?

**Comment by broken1arrow** [comment]
Yes sry (remove it) to be honest I do not know how to recreate the problem. Must first know if I set it right and have the right perms.

I have set it up like this (I have look on chat.yml) and I have try chat.yml file if it work (but no it not work).
```  # The parts of this format.
Parts:

  # See the chat.yml format file for a tutorial on how this works.
  spies-prefix:
    Message: "&8[&5Spy&8] &f"
    Receiver_Condition: "{receiver_is_spying_{channel}}"
    Hover: "&dClick to stop spying {channel} channel."
    Run_Command: "/{label_spy} toggle chat {channel}"
  everything:
    Message: '&9Lokalt-{luckperms_prefix_element_highest}'
    Hover:
      - '&8*-----* &5{player} &8*-----*'
      - '&7Medelande sänt: &b{timestamp}'
      - '&7Värld&8: &b{world}'
      - '&aKlicka för karta'
    Open_Url: http://
  Second_Part:
    Message: ' &f{player}&7&f'
    Hover:
      - '&7Rank&8: &b{pl_group}'
      - '&7Bor i:&8 {lands_land_name}'
      - '&7Första spel datum&8: &b{player_first_join_date}'
      - '&7Speltid totalt&8: &b{cmi_user_playtime_hoursf} timmar'
      - '&aKlicka för privat medelande'
    Suggest_Command: '/msg {player} '
  Third_Part:
    Message: '&7: &2{message}'
    Hover:
      - '&7Message issued: &b{timestamp}'
      - '&aKlicka för at telepotera till {player}'
    Suggest_Command: /tpa {player}
```

**Comment by broken1arrow** [comment]
and I have run lp verbose and what i find I have the perms I need, if is not a extra command I need for get spies-prefix part to work.

Spy on commands, anvil, book and sign work but not from channel.

**Comment by broken1arrow** [comment]
> Please only report one bug per Issue ticket. So how can I reproduce this problem?

I find the issue, I have set the account to op for long time ago (and forgot it). Sry if I take up time.

**Comment by broken1arrow** [comment]
but get an other issue to this. 

I know you have settings in settings.yml, I have to test if I change the file if it work (is not easy too set it up).   

After messing around, it only take settings from settings.yml not from format.

I get this. 
When i set up like this in formats. 
```
# The parts of this format.
Parts:

  # See the chat.yml format file for a tutorial on how this works.
  spies-prefix:
    Message: "&8[&5Spy&8] &f"
    Receiver_Condition: "{receiver_is_spying_{channel}}"
    Hover: "&dClick to stop spying {channel} channel."
    Run_Command: "/{label_spy} toggle chat {channel}"
  everything:
    Message: '&9Lokalt-{luckperms_prefix_element_highest}'
    Hover:
      - '&8*-----* &5{player} &8*-----*'
      - '&7Medelande sänt: &b{timestamp}'
      - '&7Värld&8: &b{world}'
      - '&aKlicka för karta'
    Open_Url: http://
  Second_Part:
    Message: ' &f{player}&7&f'
    Hover:
      - '&7Rank&8: &b{pl_group}'
      - '&7Bor i:&8 {lands_land_name}'
      - '&7Första spel datum&8: &b{player_first_join_date}'
      - '&7Speltid totalt&8: &b{cmi_user_playtime_hoursf} timmar'
      - '&aKlicka för privat medelande'
    Suggest_Command: '/msg {player} '
  Third_Part:
    Message: '&7: &2{message}'
    Hover:
      - '&7Message issued: &b{timestamp}'
      - '&aKlicka för at telepotera till {player}'
    Suggest_Command: /tpa {player}
```

![2020-11-12_21 49 46](https://user-images.githubusercontent.com/16368286/98995000-03a98a80-2531-11eb-8a60-a62c5f265acf.png)
