### ISSUE TITLE
1.16.4: Hover + suggest command in join/quit messages?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#410]
Hi, I wanna ask how can I make hover in quit / join messages? I was already looking at page with https://github.com/kangarko/ChatControl-Red/wiki/messages but I can't find there way how to add hover to message. Or use format. Before I used this on player join (8 ver):
```
First_Part:
  Message:  "&8&l[&2&l+&8&l] &7{player}"
  Hover_Event:
    Action: SHOW_TEXT
    Values:
      - '&8&l▄▄▄ {pl_prefix+} &7{player} &8&l▄▄▄'


      - '&7Tajemný prach &8» &e{gadgetsmenu_mystery_dust}'
      - '&7Tajemné truhly &8» &e{gadgetsmenu_mystery_boxes}'

      - '&7Odehráno &8» &e{statistic_hours_played}&7h'
      - '&7Registrace &8» &e{player_first_join_date}'
      - ''
      - '&7Připojen v &e{localtime_time_kk:mm:ss}'
      - '&7Klikni pro odeslání zprávy hráči'
  Click_Event:
    Action: SUGGEST_COMMAND
    Value: "/tell {player_name} "
```

How can I please transfer it now to ChatControl Red?
```
group default
message:
- &8&l[&2&l+&8&l] &7{player}
```
And now?

And btw why is sometimes used {player} and sometimes {player_name}?

And about suggest command, it could be done how?
