### ISSUE TITLE
1.16.4 range work more an range you set

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl#43]
When use Range it send it like global chat. 

```
mc-lokalt:
      Format: '&6[ranged] &7{pl_prefix+}{player}:{pl_suffix} {message}'
      Range: 30
      Worlds:
      - 'Midgardsaga'
      - 'Midgardsaga_nether'
```
