### ISSUE TITLE
1.16.4: Papi parseother placeholder doesn't work in chat format

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#460]
Minecraft Version: 1.64.4
MySQL: true
BungeeCord: true

Hi, I wanna report that placeholder ParseOther (install with /papi ecloud download parseother) doesn't work. I wanted to make it in chat format in pm sender and pm receiver, but I can't get it work.

I tried: `{parseother_{{receiver}}_{vault_prefix}} ` but the output is:
![image](https://user-images.githubusercontent.com/18662086/103445828-27f42e80-4c79-11eb-950b-e46e5ea4cb8c.png)
My whole format for this:
```
  First_Part:
    Message: '&c&l✉ &e→ {receiver}: '
    Hover:
    - '&8&l▄▄▄ {parseother_{{receiver}}_{vault_prefix}} &7{receiver} &8&l▄▄▄'
    - '&7Tajemný prach &8» &e{parseother_{{receiver}}_{gadgetsmenu_mystery_dust}}'
    - '&7Tajemné truhly &8» &e{parseother_{{receiver}}_{gadgetsmenu_mystery_boxes}}'
    - '&7Odehráno &8» &e{parseother_{{receiver}}_{statistic_hours_played}}&7h'
    - '&7Registrace &8» &e{parseother_{{receiver}}_{player_first_join_date}}'
    - '&7CPS &8» &e{parseother_{{receiver}}_{cps_left_place_1_cps-decimal}}'
    - '&7CPS umístění &8» &e{parseother_{{receiver}}_{cps_left_place_1_place}}'
    - '&7Perků &8» &e{parseother_{{receiver}}_{gadgetsmenu_unlocked_total}}&8/&e{parseother_{{receiver}}_{gadgetsmenu_total_size}} &8- &e{parseother_{{receiver}}_{gadgetsmenu_unlocked_total_percentages}}&7%'
    - ''
    - '&7Odeslat zprávu jinému hráči.'
    Suggest_Command: '/msg '

```

As I searched, when you use` /papi parse me %parseother_{player_name}_{vault_prefix}%` it works, so where's the problem? I also searched on spigot https://www.spigotmc.org/threads/placeholderapi.61918/page-125, where's someone giving example.
