### ISSUE TITLE
1.16.4 Log function ignores default chat (everything outside channels)

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl#462]
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

Log function does not log default minecraft / CMI / Essentials chat, unless it's sentence is filtered by any rule.
Other messages like signs, books and commands are logged perfectly.

Reproduce:
```yaml
Channels:
  Enabled: false
Log:
  Apply_On:
  - 'chat'
 - etc
  ```
Chat plugin like essentials or CMI is not required. Even minecraft default chat works to reproduce this issue.
