### ISSUE TITLE
1.16.4: Formatting bug

### ISSUE THREAD

**Issue by freeg-bee** [kangarko/ChatControl#488]
1. &r is not work when set prefix to player
2.
![1](https://user-images.githubusercontent.com/60282242/103667496-11a2e700-4f87-11eb-8de6-d0b0ced262eb.jpg)
![2](https://user-images.githubusercontent.com/60282242/103667500-12d41400-4f87-11eb-851a-bc173efd7ff0.jpg)
![3](https://user-images.githubusercontent.com/60282242/103667503-14054100-4f87-11eb-9cd9-29821339351e.jpg)
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5771192/debug.zip)

Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

**Comment by kangarko** [comment]
Sorry what are you trying to accomplish? You cannot use colors in your permissions as far as ChatControl Red goes.

**Comment by freeg-bee** [comment]
Colors works right. but &r code is not working in CC
![1](https://user-images.githubusercontent.com/60282242/103669196-1b2d4e80-4f89-11eb-91a6-4594a62cf466.png)

**Comment by freeg-bee** [comment]
It also possible trougt color function in CCR. But how can i change color only for prefix?

**Comment by freeg-bee** [comment]
> Sorry what are you trying to accomplish? You cannot use colors in your permissions as far as ChatControl Red goes.

Colors works right. but &r code is not working in CC
![1](https://user-images.githubusercontent.com/60282242/103669196-1b2d4e80-4f89-11eb-91a6-4594a62cf466.png)

It also possible trougt color function in CCR. But how can i change color only for prefix?

**Comment by freeg-bee** [comment]
> Sorry what are you trying to accomplish? You cannot use colors in your permissions as far as ChatControl Red goes.

The same problem in tags.
![4](https://user-images.githubusercontent.com/60282242/103680633-7ebe7880-4f97-11eb-9698-811784a04f49.png)
![5](https://user-images.githubusercontent.com/60282242/103681026-03a99200-4f98-11eb-905b-e3cb42c71896.png)

**Comment by ElBananaa** [comment]
> Sorry what are you trying to accomplish? You cannot use colors in your permissions as far as ChatControl Red goes.

Hey!

@kangarko Alright, so from what I understood, as you can see throught the lp editor, he define the Creator role prefix: `&c&l&nCreator`, so it beans bold underlined light-red text. And as you can see on his screenshots, using the `&r` color code doesn't remove the underlined effect, resulting in a weird issue.

 @freeg-bee Please provide us your actual format file, i'll run some tests on my end, and I'll see if I can find a temp "fix" for your issue.

**Comment by freeg-bee** [comment]
> > Sorry what are you trying to accomplish? You cannot use colors in your permissions as far as ChatControl Red goes.
> 
> Hey!
> 
> @kangarko Alright, so from what I understood, as you can see throught the lp editor, he define the Creator role prefix: `&c&l&nCreator`, so it beans bold underlined light-red text. And as you can see on his screenshots, using the `&r` color code doesn't remove the underlined effect, resulting in a weird issue.
> 
> @freeg-bee Please provide us your actual format file, i'll run some tests on my end, and I'll see if I can find a temp "fix" for your issue.

[debug.zip](https://github.com/kangarko/ChatControl-Red/files/5771789/debug.zip)

**Comment by ElBananaa** [comment]
> > > Sorry what are you trying to accomplish? You cannot use colors in your permissions as far as ChatControl Red goes.
> > 
> > 
> > Hey!
> > @kangarko Alright, so from what I understood, as you can see throught the lp editor, he define the Creator role prefix: `&c&l&nCreator`, so it beans bold underlined light-red text. And as you can see on his screenshots, using the `&r` color code doesn't remove the underlined effect, resulting in a weird issue.
> > @freeg-bee Please provide us your actual format file, i'll run some tests on my end, and I'll see if I can find a temp "fix" for your issue.
> 
> [debug.zip](https://github.com/kangarko/ChatControl-Red/files/5771789/debug.zip)

Thanks!

Alright, firstly, please update to the latest version of the plugin, update ProtocolLib, and update your server software (spigot, paper or whatever it is). Once this is done try to add the following under your `player-prefix:` part in your chat-global format, and let me know if it fixes your issue. Also keep in mind that this should be a temporary fix:
```
  player-prefix-end:
    Message: '&7>&r '
    Sender_Condition: '"{prefix_tag}" == ""'
    Hover:
    - '&fRank: &f{player_group}'
    - '&fClick to open &6donate &fpage'
```
So it should look like that:
```
...
  player-prefix:
    Message: '&7<{player_prefix}'
    Sender_Condition: '"{prefix_tag}" == ""'
    Hover:
    - '&fRank: &f{player_group}'
    - '&fClick to open &6donate &fpage'
  player-prefix-end:
    Message: '&7>&r '
    Sender_Condition: '"{prefix_tag}" == ""'
    Hover:
    - '&fRank: &f{player_group}'
    - '&fClick to open &6donate &fpage'
 ....
```
