### ISSUE TITLE
Players can't do any commands while muted

### ISSUE THREAD

**Issue by Linkbomber** [kangarko/ChatControl#505]
I'm currently having an issue where players can't use any commands while muted, it gives them the message "[x] You cannot perform this command while you are muted."

**Comment by TheIntolerant** [comment]
In ``settings.yml``
What do you have written in this section? In particular what is set for ``Prevent_Commands: ``

```
Mute: 

  # Should we enable this feature?
  Enabled: false

  # The commands that invoke the mute feature.
  # EDIT AS YOU WISH BUT DO NOT REMOVE THE FIRST ALIAS
  Command_Aliases: [mute]
  
  # If the server is muted, which commands should we disable?
  Prevent_Commands: 
    - /tell
    - /w
    - /m
    - /t
    - /pm
    - /message
    - /msg
    - /whisper
    - /mail
    - /reply
    - /r
    - /me

  # Should we deny writing to the books?
  Prevent_Writing_Books: true

  # Should we deny placing signs?
  Prevent_Placing_Signs: true

  # Should we hide join messages?
  Hide_Join_Messages: true

  # Should we hide quit messages?
  Hide_Quit_Messages: true

  # Should we hide death messages?
  Hide_Death_Messages: true
  ```
