### ISSUE TITLE
1.16.4: IgnorePermission and placeholder question

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#524]
**1.** Is there an alternative to "Sender_Permission" and "Receiver_Permission". I want to set it up so people see different messages based on their permission node.

**2.** Im also trying to set up hover so like this:
```yaml
    Hover:
    - '&6Username: &f{player}'
    - '&7&oMarriage: {marriagemaster_partner}'
```
Is it possible to do something like `if "{marriagemaster_partner}" == "not married" return null` (essentially not adding it to the hover message list)?

**Comment by ElBananaa** [comment]
> **1.** Is there an alternative to "Sender_Permission" and "Receiver_Permission". I want to set it up so people see different messages based on their permission node.
> 
> **2.** Im also trying to set up hover so like this:
> 
> ```yaml
>     Hover:
>     - '&6Username: &f{player}'
>     - '&7&oMarriage: {marriagemaster_partner}'
> ```
> 
> Is it possible to do something like `if "{marriagemaster_partner}" == "not married" return null` (essentially not adding it to the hover message list)?

Hey!

This is possible using `Sender_Condition` and `Receiver_Condition`. However, it only chekcs for booleans, so you must create a custom variable inside `ChatControlRed/variables/` that will return either true or false.

You can take a look at the other different variables that can be used in the formats here (https://github.com/kangarko/ChatControl-Red/wiki/Formats)

**Comment by LogGits** [comment]
> This is possible using `Sender_Condition` and `Receiver_Condition`. However, it only chekcs for booleans, so you must create a custom variable inside `ChatControlRed/variables/` that will return either true or false.

Will look into this though im not sure i 100% understand.

> You can take a look at the other different variables that can be used in the formats here (https://github.com/kangarko/ChatControl-Red/wiki/Formats)

I am abit confused about this. How can i make the message deliver the result:
```
if "{marriagemaster_partner}" == "not married" return null
```
and if a line is null or '' does it skip the line?

I want to have multiple stats showing up for player name hover but only if they have the stats. My concern is that despite my efforts it will end up looking like:
```
- ''
- ''
- ''
- ''
```
due to idea returning null. (though im not even sure how to achieve the idea).

**Comment by ElBananaa** [comment]
> > This is possible using `Sender_Condition` and `Receiver_Condition`. However, it only chekcs for booleans, so you must create a custom variable inside `ChatControlRed/variables/` that will return either true or false.
> 
> Will look into this though im not sure i 100% understand.
> 
> > You can take a look at the other different variables that can be used in the formats here (https://github.com/kangarko/ChatControl-Red/wiki/Formats)
> 
> I am abit confused about this. How can i make the message deliver the result:
> 
> ```
> if "{marriagemaster_partner}" == "not married" return null
> ```
> 
> and if a line is null or '' does it skip the line?
> 
> I want to have multiple stats showing up for player name hover but only if they have the stats. My concern is that despite my efforts it will end up looking like:
> 
> ```
> - ''
> - ''
> - ''
> - ''
> ```
> 
> due to idea returning null. (though im not even sure how to achieve the idea).

Hey!
As I said, you can't return null. It must be a boolean, so your placeholder/variable must return either true or false.
What you're trying to do is possible, but you'll have to create multiple parts with different lines each one.
Here's an example of formats from my chat.yml file:
```
  player-nick-admin:
    Message: '{player_nick} '
    Sender_Permission: group.admin
    Hover:
    - '&c&nClick to send a message'
    Suggest_Command: '/tell {player_name} '
    Gradient: red - yellow
  player-nick-no-island:
    Message: '{player_nick} '
    Sender_Condition: '!{player_has_island}'
    Sender_Permission: nick.default
    Hover:
    - '&c&nClick to send a message'
    Suggest_Command: '/tell {player_name} '
  player-nick-island:
    Message: '{player_nick} '
    Sender_Condition: '{player_has_island}'
    Sender_Permission: nick.default
    Hover:
    - 'Level: {island_level}'
    - 'Members: {island_members}'
    - 'leader: {island_leader}'
    - 'worth: {island_worth_eco}'
    - ''
    - '&c&nClick to send a message'
    Suggest_Command: '/tell {player_name} '
```

That's an example, but this should give you a better idea about how things work.
All of this is explained at the top of the chat.yml file and on the wiki tho.
