### ISSUE TITLE
1.16.4: Sign spy issue

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#528]
**Bug explanation:** I am not sure if this is a bug or improvement so I'm just going to list it as a bug. Signspy is sending empty signs to the "[hover me]". E.g. place an empty sign on another account and signspy will see "[hover me]" with 4 empty new lines.

**Solution could be:** only sending the signspy if the sign contains actual content (excluding `[private]` signs). My existing config:
```yaml
# The parts of this format.
Parts:
  
  # See the chat.yml format file for a tutorial on how this works.
  front:
    Message: '&7[{location}] {player} placed a sign: '
  content:
    Message: '[hover me]'
    Hover:
    - '{sign_lines}'
```
Gif of what im talking about: <https://gyazo.com/1b4358bc907abb2b32d82d2de7721c35>

Paper 1.16.4 build 406.
ChatControl Red 10.1.18.
