### ISSUE TITLE
1.16.4: {receiver_or_you} colour code issue

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#530]
```yaml
Parts:
  Everything:
    Message: '&6[&c{sender} &6->&c {receiver_or_you}&6] &f{message}'
    Suggest_Command: '/r '
```
Appears to display white "you" when the player responds to me. It mite be related to a colour code being placed on via the placeholder `{receiver_or_you}`.

See image for more info: <https://gyazo.com/817d2ddb41208ce541f3db16ee0d160d>

Paper 1.16.4 build 406
Chc Red 10.1.18
