### ISSUE TITLE
No URL linking in private messages

### ISSUE THREAD

**Issue by TheoRetisch1** [kangarko/ChatControl#536]
It is no longer possible to click links in msgs. If one clicks on a url, only the hover message of the pm-receiver appears.
![msg](https://user-images.githubusercontent.com/24480321/104808506-081b4980-57e7-11eb-88e6-e9662444a0d2.png)

Minecraft Version: 1.16.4 (git-Tuinity-"8954b61")
ChatControlRed 10.1.19
MySQL: true
BungeeCord: false
**pm-receiver**:
```
Parts:
  everything:
    Message: '&a{sender} &2▶▶ &e&o{message}'
    Hover:
    - ' &2&m        &a&l Private Nachricht &2&m        '
    - ' &8Empfangen: &7{timestamp}&r'
    - ''
    - ' &2&l>> &aKlick für &2/msg {sender}&r'
    Suggest_Command: '/msg {sender} '
```
**pm-sender**:
```
Parts:
  everything:
    Message: '&7{player} &2◀◀ &7&o{message}'
    Hover:
    - ' &2&m        &a&l Private Nachricht &2&m        '
    - ' &8Gesendet: &7{timestamp}&r'
    - ''
    - ' &2&l>> &aKlick für &2/msg {player}&r'
    Suggest_Command: '/msg {player} '
```

**Comment by ElBananaa** [comment]
> It is no longer possible to click links in msgs. If one clicks on a url, only the hover message of the pm-receiver appears.
> ![msg](https://user-images.githubusercontent.com/24480321/104808506-081b4980-57e7-11eb-88e6-e9662444a0d2.png)
> 
> Minecraft Version: 1.16.4 (git-Tuinity-"8954b61")
> ChatControlRed 10.1.19
> MySQL: true
> BungeeCord: false
> **pm-receiver**:
> 
> ```
> Parts:
>   everything:
>     Message: '&a{sender} &2▶▶ &e&o{message}'
>     Hover:
>     - ' &2&m        &a&l Private Nachricht &2&m        '
>     - ' &8Empfangen: &7{timestamp}&r'
>     - ''
>     - ' &2&l>> &aKlick für &2/msg {sender}&r'
>     Suggest_Command: '/msg {sender} '
> ```
> 
> **pm-sender**:
> 
> ```
> Parts:
>   everything:
>     Message: '&7{player} &2◀◀ &7&o{message}'
>     Hover:
>     - ' &2&m        &a&l Private Nachricht &2&m        '
>     - ' &8Gesendet: &7{timestamp}&r'
>     - ''
>     - ' &2&l>> &aKlick für &2/msg {player}&r'
>     Suggest_Command: '/msg {player} '
> ```

Hey! Thanks for reporting this.
I tried on my own server, and I could actually reproduce it.
However, I don't know if this is a real issue. Actually, you defined a click action which is `Suggest_Command: '/msg {player} '`, so it's seems normal that the url linking doesn't work. I don't know if Kangarko could do anything about it.
You should consider splitting the private message format, so you would have a part with the message only.
Try this for the pm-sender and just do the same for the pm receiver, it should fix your "issue".
```
Parts:
  firstPart:
    Message: '&7{player} &2◀◀  '
    Hover:
    - ' &2&m        &a&l Private Nachricht &2&m        '
    - ' &8Gesendet: &7{timestamp}&r'
    - ''
    - ' &2&l>> &aKlick für &2/msg {player}&r'
    Suggest_Command: '/msg {player} '
  secondPart:
    Message: '&7&o{message} '
    Hover:
    - ' &2&m        &a&l Private Nachricht &2&m        '
    - ' &8Gesendet: &7{timestamp}&r'
```
