### ISSUE TITLE
1.16.5: Disabling DIscord formatting of one chat

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#567]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, I have question. If I don't wanna format my Discord chat in one channel, cause I wanna use their option to send messages as webhooks (with skin and names), how can I do it?

I've tried setting none here, but didn't help.
```
  # The default Discord format unless overriden below. Does not support formats.
  # We automatically send messages to Discord channels that you have linked in the "Integration"
  # section below. To disable this per-channel, set Format_Discord to "none" for that channel.
  Format_Discord: '{player}: {message}'
```

I wanted to set standard chat on false to allow sending messages as webhook with player names and skins, and then admin channels and helpop normally via chatcontrol  Discord:
  .
```
    standard:
      Format: chat
      Format_Spy: '@noprefix chat'
      Bungee: false
      Discord: false
    admin:
      Format: admin-chat
      Format_Console: default
      Bungee: true
      Discord: true
    global:
      Format: global-chat
      Bungee: false
      Discord: false
    helpop:
      Format: helpop
      Bungee: false
      Discord: true
```
Tried also join:standard
```
  Prefix:
  
  # Broadcast messages automatically to your Discord.
  # Put the types from Apply_On above to the left, and the Discord channel to the right. Your
  # Discord channel must first be connected in the Integration section below!
  #
  # Example:
  # Discord:
  #   join: standard
  Discord:
```

ANd finally here, I've tried set connected_channels to 0:minecraft, previously it was normally my channel (      `802288561244209202: standard`). The only way that helps me is disable integration with DiscordSRV entirely. But I don't wanna do it... I still wanna use integration but just not in the main channel standard, there I wanna use webhooks with player names and skins. Any idea how to do it?
```
  Discord:
    
    # Enable all integration with DiscordSRV?
    Enabled: true
    
    # Discord does not let us edit messages, so we must remove the original message and resend
    # it as the bot. You will see your message disappear and reappear in a second or less. 
    # true = messages are sent as bot (username icons not visible)
    # false = we do not edit your discord messages (warning: this breaks antispam, rules and 
    #         removing messages on discord)
    Send_Messages_As_Bot: false
  
    # What chat channels should we map when sending/receiving a message to/from Discord?
    # Write <channel id>: <channel name> (the channel name must equal your ChatControl channel
    #                                     name, but not necessarily the one on Discord)
    Connected_Channels:
      0: minecraft
```

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> Hi, I have question. If I don't wanna format my Discord chat in one channel, cause I wanna use their option to send messages as webhooks (with skin and names), how can I do it?
> 
> I've tried setting none here, but didn't help.
> 
> ```
>   # The default Discord format unless overriden below. Does not support formats.
>   # We automatically send messages to Discord channels that you have linked in the "Integration"
>   # section below. To disable this per-channel, set Format_Discord to "none" for that channel.
>   Format_Discord: '{player}: {message}'
> ```
> 
> I wanted to set standard chat on false to allow sending messages as webhook with player names and skins, and then admin channels and helpop normally via chatcontrol Discord:
> .
> 
> ```
>     standard:
>       Format: chat
>       Format_Spy: '@noprefix chat'
>       Bungee: false
>       Discord: false
>     admin:
>       Format: admin-chat
>       Format_Console: default
>       Bungee: true
>       Discord: true
>     global:
>       Format: global-chat
>       Bungee: false
>       Discord: false
>     helpop:
>       Format: helpop
>       Bungee: false
>       Discord: true
> ```
> 
> Tried also join:standard
> 
> ```
>   Prefix:
>   
>   # Broadcast messages automatically to your Discord.
>   # Put the types from Apply_On above to the left, and the Discord channel to the right. Your
>   # Discord channel must first be connected in the Integration section below!
>   #
>   # Example:
>   # Discord:
>   #   join: standard
>   Discord:
> ```
> 
> ANd finally here, I've tried set connected_channels to 0:minecraft, previously it was normally my channel ( `802288561244209202: standard`). The only way that helps me is disable integration with DiscordSRV entirely. But I don't wanna do it... I still wanna use integration but just not in the main channel standard, there I wanna use webhooks with player names and skins. Any idea how to do it?
> 
> ```
>   Discord:
>     
>     # Enable all integration with DiscordSRV?
>     Enabled: true
>     
>     # Discord does not let us edit messages, so we must remove the original message and resend
>     # it as the bot. You will see your message disappear and reappear in a second or less. 
>     # true = messages are sent as bot (username icons not visible)
>     # false = we do not edit your discord messages (warning: this breaks antispam, rules and 
>     #         removing messages on discord)
>     Send_Messages_As_Bot: false
>   
>     # What chat channels should we map when sending/receiving a message to/from Discord?
>     # Write <channel id>: <channel name> (the channel name must equal your ChatControl channel
>     #                                     name, but not necessarily the one on Discord)
>     Connected_Channels:
>       0: minecraft
> ```

Hey!
I don't think this is actually possible with the plugin.
You can completely disable the plugin discord chat formatting feature, but you cannot disable it per channel yet, if i'm not wrong.
Please wait for Kangarko to make sure about it. :)

**Comment by bobhenl** [comment]
Then this feature doesn't work, if we can't disable it per channel.
```
    standard:
      Format: chat
      Format_Spy: '@noprefix chat'
      Bungee: false
      Discord: false
    admin:
      Format: admin-chat
      Format_Console: default
      Bungee: true
      Discord: true
    global:
      Format: global-chat
      Bungee: false
      Discord: false
    helpop:
      Format: helpop
      Bungee: false
      Discord: true
```
Why then this exists if when we set false then it doesn't work?
