### ISSUE TITLE
Need information

### ISSUE THREAD

**Issue by srrawr11** [kangarko/ChatControl#572]
Minecraft Version: 1.8 - 1.16
MySQL: false
BungeeCord: true

Hi, basically I asked a month ago, that if this is possible to block with CCPro and you said with CCRed its possible..
So could you show me how or where is the section to block it? Thanks :D

https://imgur.com/JDKACoh

This option is in the CCFree version.

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.8 - 1.16
> MySQL: false
> BungeeCord: true
> 
> Hi, basically I asked a month ago, that if this is possible to block with CCPro and you said with CCRed its possible..
> So could you show me how or where is the section to block it? Thanks :D
> 
> https://imgur.com/JDKACoh
> 
> This option is in the CCFree version.

Hey!
Everything that could be done with the Tab_Complete feature can be found in the settings file:
```
Tab_Complete:
  
  # Enable this feature?
  Enabled: false
  
  # Prevent completions for words shorter that the given amount of letters.
  # **On Minecraft older than 1.13 this only works properly on the first command argument.**
  Prevent_If_Below_Length: 0
  
  # What commands should we prevent from being tab-completed? Uses regular expressions.
  # [TIP] This is turned into blacklist by default, see header of this configuration.
  Whitelist:
  - '@blacklist'
  - '(/ver|/version)\b'
  - '(/pl|/plugins)\b'
  - '/hiddenCommand'
```
