### ISSUE TITLE
1.16.5 <center> reads placeholder length not value length

### ISSUE THREAD

**Issue by james090500** [kangarko/ChatControl#577]
As title suggest, `<center>` reads the length of the placeholder name rather than the value causing things not to center.

```
Parts:
  # See the chat.yml format file for a tutorial on how this works.
  first:
    Message:
    - '&8&m&l===============&r &8&l» &c&lCapeCraft&r &8&l« &m=================&r'
    - '&r'
    - '<center>Welcome back {chatcontrolred_nick}&r'
    - ''
    - '&r<center>&6There are {bungee_total}/60 players online&r'
    - ''
    - '&r<center>Join our discord: &6https://CapeCraft.net/discord'
    - '&r<center>Donate for perks: &6https://CapeCraft.net/donate'
  book:
    Message: "&r<center>Read our rules: &r[&6Click Here&r]"
    Run_Command: "/chc book open rules"
  end:
    Message:    
    - ''
    - ''    
    - '&8&m&l============================================='
```

https://ufile.io/4bye5acc

![image](https://user-images.githubusercontent.com/20372645/105644465-9baae500-5e8d-11eb-924a-869618f514a8.png)

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true
