### ISSUE TITLE
1.16.5: Gradient in nicknames?

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl#587]
Is it somehow possible to use gradient within nicknames? If so, is it permission based?

**Comment by ElBananaa** [comment]
> Is it somehow possible to use gradient within nicknames? If so, is it permission based?

Hey!
Gradients can only be used in formats afaik, there are examples in the chat format file.
`#   - Gradient: <from> - <to> (such as RED - GOLD or #123456 - #123456) Gradients for MC 1.16+.`
```
  # Display a typical player name to players with the given permission. change {player_name} 
  # to {player_nick} to show nick instead. We'll revert to show normal name if player has no nick.
  # To display a name in rainbow colors, uncomment "Gradient". This requires MC 1.16+
  player-name: 
    Message: "{player_nick}"
    #Message: "{player_name}"
    #Gradient: RED - YELLOW
    Hover: "&7Click to message."
    Suggest_Command: "/tell {player_name} "
```
I don't know if that's what you're asking for, if so, don't forget to close the ticket, if not, feel free to leave it open and wait for Kangarko :)
