### ISSUE TITLE
1.16.5: Timed.rs bug (incl. json messages)

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl#590]
Some of the people on the CHC#testing discord told me this is a bug so I'm reporting it here.

Summary: I am unable to get timed.rs to work (send messages) at all.

Details
--

**timed.rs**:
(i've been told 'prefix [test]' is a bug via discord users but that's not 100% my issue)
```rs
group default
prefix [test] 
delay 1 seconds
messages:
- test1
- test2
```
**settings.yml**:
```yaml
Messages:
 
  # What aspects of messages should be enabled?
  # Options: join, quit, kick, death, timed
  #
  # If you have another plugin handling join/quit etc. messages, remove them from list below.
  # If you want to hide those messages, leave them in Apply_On and empty your messages/ .rs files.
  Apply_On:
  - 'timed'
  - 'death'
  - 'quit'
  - 'join'
```
**Explanation**:
I've been trying to get `prefix [JSON]` timed messages to appear like they did on chc8. I migrated the system added in a delay and it appears not to work. I have looked at all the settings and made sure everything is setup as intended. I am unsure what could be the cause of this. In addition, it appears as though i cant even enable `timed.rs` via `/chc message toggle timed default` (see #583). Idk if this is related to that and it's just perm disabled via some database thing or if this is actually a bug. @kangarko I can provide you with a debug.zip via discord dm's if required. Keep me updated :)

***SIDE NOTE: i've tested without json and without a prefix shown in the aforementioned timed.js and it still doesn't display.***

Environment
--
```
chc red 10.1.21
Minecraft Version: 1.16.5 paper 444
MySQL: false
BungeeCord: false
```
