### ISSUE TITLE
1.16.5 - Discord message server do not show

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#612]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Send message to Discrod Channel, but server do not show

In formats.yml:
global-chat
```
Parts:
  Discord:
    Message: '&8&l[&bD&8&l] &r{message}'
    Sender_Condition: '{sender_is_discord}'
    Hover:
    - '&b加入官方Discord &8> &3https://discord.gg/Fq6gmP4'
    Open_Url: https://discord.gg/Fq6gmP4
  Delete-Chat:
    Message: '&8&l[&4X&8&l] &f'
    Receiver_Permission: chatcontrol.removemessages
    Hover:
    - '&c刪除這串訊息'
    Run_Command: /{label} internal remove {message_uuid}
  Server-name:
    Message: '&8&l[&21S&8&l]&r '
    Hover:
    - '&7玩家 &2{player_name} &7目前位於 &a第一分流'
    - '&7可以使用 &6伺服器選單 &7切換分流'
  Channel-name:
    Message: '&8&l[&a閒聊頻道&8&l]&r '
  Player-Name:
    Message: '{player_name}'
    Hover:
    - '&7點擊發送密語給此玩家'
    Suggest_Command: '/msg {player_name} '
  Message:
    Message: '%luckperms_suffix%&r : &f{message}'
```
In settings.yml
```
global:
Format: global-chat
Discord: true
Format_Discord: '{player_name}: {message}'
```
      
Thanks for helping
