### ISSUE TITLE
Chat is not passed to dynmap

### ISSUE THREAD

**Issue by snhnry** [kangarko/ChatControl#66]
ChatControl: Latest, using bungee
Spigot: Latest

Currently, no chat is being passed to the web server of Dynmap. I'm coming from HeroChat, which required a helper plugin that was developed by the dynmap developer to get chat passed through. Is this an issue that could be solved by changing priorities in the settings? If not, can it be resolved by an update to ChatControl or would it have to come from the developer of dynmap?

**Comment by kangarko** [comment]
Are you using premium or the free version? It should work with the free version and static chat in the pro one.

**Comment by snhnry** [comment]
This is the premium version. Does that mean that using chat channels will prevent chat from going to dynmap?

**Comment by kangarko** [comment]
Channels are unsupported natively in Bukkit, so it is not easy to make a system with logic that will both render in console and complain with the chat event.
Currently, the chat event is cancelled and the message is printed separately. I can try to remove all receivers to see if it helps.

**Comment by kangarko** [comment]
@snhnry can you try the latest version?

**Comment by snhnry** [comment]
No change that I can see. Disabling channels still fixes the issue and re-enabling them removes all chat from Dynmap.

**Comment by kangarko** [comment]
Please ensure you don't have **Log_Format **specified in chat.yml and **Chat.Channels.Cancel_Event **to false in settings.yml

**Comment by snhnry** [comment]
Still not having any luck. Here's my default channel in chat.yml:
http://pastebin.com/bTGVa0E6

I've double checked that Cancel_Event is false.

**Comment by kangarko** [comment]
Debug has been removed, but I cannot unfortunately test with dynmap. I will try to find another way.

**Comment by kangarko** [comment]
Hey, I just tested following configuration:

* Latest version of Dynmap as of 20.03.2016 running on Java 8 Spigot 1.9 server compiled 20.03.2016.
* ChatControl 6.8.1
* Chat Formatter disabled and Chat Channels enabled.
* Following effective part of chat.yml:

```
Formats:
  Example_Format:
    Parts:
      Prefix:
        Message: "{pl_prefix}"       
        Hover_Event:
          Action: SHOW_TEXT
          Values:
            - "&8*-----* &f{player} &8*-----*"
            - "&7Prefix&8: &7{pl_prefix}"
            - "&7Ping&8: &b{ping}"
            - "&7Tps: &e{tps}"
      
      Player:
        Message: "{player}:"                 
        Hover_Event:
          Action: SHOW_TEXT
          Values:
            - "&7Message issued: &b{timestamp}"
            - "&7Click to send a PM"
        Click_Event:
          Action: SUGGEST_COMMAND
          Value: "/tell {player} "            
      Suffix:
        Message: "{pl_suffix} "        
      Message:
        Message: "{message}"

Channels:
  standard:
    Format: Example_Format
```

The chat has been displayed normally in the dynmap, and vice versa. I can only see the issue if you have Log_Format specified in chat.yml (then remove it) or Chat.Channels.Cancel_Event to true in settings.yml (set to false).
