### ISSUE TITLE
1.16.5: How to get Discord roles into Chat

### ISSUE THREAD

**Issue by FETXU** [kangarko/ChatControl#682]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi there, I am trying to get Discord roles passed into Minecraft chat, but feel like CHC is overwriting any attempts to format in DiscordSRV.

Is there a special placeholder, or a wiki entry that might help me here?

For example, I would like the Discord toprole shown in MC

Additionally, is it possible to have the discord join/quit messages in the messages section for the settings being sent only on _NETWORK_ join? As in a configuration for the bungee part of CHC?

Cheers

**Comment by ElBananaa** [comment]
Hey!
I don't know if this is possible with the plugin. However, you can disable ChatControl discord formatting and use DiscordSRV system instead.

Regarding your second question, I have no idea, you'll have to wait for Kangarko about that. ^^

**Comment by FETXU** [comment]
```
Messages:
  
  # Broadcast messages when player joins/quits the network or switches servers?
  Enabled: true
  
  # List of server names (see the header) that we ignore from broadcasting
  Ignored_Servers:
  - 'silent_server'
  
  # Send messages below to the player that triggered them?
  Send_To_Target: true
  
  # Sent to all players on the network.
  # Player with 'chatcontrol.silence.join' won't have a join message.
  Join_Message: '&8[&a+&8] &e{player} &fjoined the network'
  
  # Only sent to the server to which player joined.
  Join_Target: none
  
  # Sent to all players on the network.
  # Player with 'chatcontrol.silence.leave' won't have a leave message.
  Leave_Message: '&8[&c-&8] &e{player} &fleft the network'
```


Would be amazing if we could send the network joins/quits that are in the BUNGEE CONFIG, as this is the actual number of players in the game.
