### ISSUE TITLE
Minecraft Version: Radius channel

### ISSUE THREAD

**Issue by itsme-to** [kangarko/ChatControl#688]
I have a practice server and i would like to add a radius chat in arene map, for game chat. How can do that

Minecraft Version: 1.8
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
Hey!

Please refer to this part of the wiki in order to do that: https://github.com/kangarko/ChatControl-Red/wiki/Channels#range

So basically, under your `List:` part in your `settings.yml`, add to the specific channel the following option:
```
  List:
    default:
      Format: chat
    adminchat:
      Format: admin-chat
      Format_Console: '&7『&4aChat&7』 &r{player} &8&l» &r{message}'
      Range: 100 # <-- When using the adminchat, only players within 100 blocs to the sender or with the permission `chatcontrol.bypass.rang` will see the message. You can use: "Range: '*'" so every player in the same world using the adminchat will see the message.
```
