### ISSUE TITLE
1.16.5: center affects new line

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#699]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi my problem is related to <center> tag that affects new line.
```
Parts:
  
  # See the chat.yml format file for a tutorial on how this works.
  part1:
    Message:
    - '&a&m<-=-------------&r &b&lTrinity&e&lMC &fSvanilla &b&m-------------=->'
    - '&7Můžeš hrát: &eSurvival, Vanillu, SkyBlock, AcidIsland, a navíc'
    - '&eSkyGrid, Creative či dobrodružné mapy! &c&l/svety &7(klik)'
    - '&r'
    - '<center>&9&lLednová aktualizace – Roll it again&r'
    Open_Url: https://trinitymc.eu/semi-vanilla/
  part2:
    Message:
    - '&e - &7Využij &f25% &7slevy na &c/store &7(klik) a mrkni do &c/souteze'
    Open_Url: https://store.trinitymc.eu/
  part3:
    Message:
    - ''
    - '&e - &7Sleduj novinky a web – &c/changelog &7(klik)'
    Open_Url: https://trinitymc.eu/
  part4:
    Message:
    - ''
    - '&e - &7Hlasuj přes &c/vote &7a využij &c/denniodmena &7(klik)'
    Open_Url: https://trinitymc.eu/vote/
  part5:
    Message:
    - ''
    - '&e - &7Propoj si účet s Dis, webem a mailem! &c/discord &7a &c/setemail'
    - '&a&m---------------------------------------------------'
    Open_Url: https://discord.mcreunion.eu

```

![image](https://user-images.githubusercontent.com/18662086/108438723-27771d80-7250-11eb-9fb6-cb8dfddcdaec.png)

As you can see in this image, there's small space after center tag on new line... when I removed &r it was absolutely broken.

And btw about empty '', I had to use them to make messages on the new lines.
