### ISSUE TITLE
1.16.5: Bungee is sending messages even when it's disabled per channel & how to disable private SPY in bungee?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#717]
Minecraft Version: 1.X.Z
MySQL: true/false
BungeeCord: true/false

Hi, so for the first thing, I have set this on both servers, there's bungee false on standard channel:
```
    standard:
      Format: chat
      Format_Spy: '@noprefix chat'
      Bungee: false
      Discord: false
```

And when are players writing messages on these servers we still see it
![image](https://user-images.githubusercontent.com/18662086/108637944-31399480-748d-11eb-861d-e145d452b35c.png)

And also... how to stop spying messages through bungee instance? Is it possible somehow?
![image](https://user-images.githubusercontent.com/18662086/108637954-3b5b9300-748d-11eb-92bf-466ca1fa6461.png)
