### ISSUE TITLE
1.16.5: Anti-Caps is still checking commands despite being disabled.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl#718]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

ChatControlRed v10.2.5

ChatControl's anti-caps feature is still checking commands despite the feature being disabled.

```
# -------------------------------------------------------------------------------------------------
# Prevent messages written in BIG LETTERS.
# -------------------------------------------------------------------------------------------------
Anti_Caps:

  # Should we enable this feature?
  Enabled: false
  
  # List of commands checked for capitalization.
  # [TIP] To enable anti-caps everywhere, set the list to ["*"]
  Enabled_In_Commands:
  - '/tell'
  - '/w'
  - '/m'
  - '/t'
  - '/pm'
  - '/message'
  - '/msg'
  - '/whisper'
  - '/mail'
  - '/reply'
  - '/r'
  - '/me'

  # How many letters must the message contain to trigger this check?
  Min_Message_Length: 5

  # How much percent of the message must be CAPITALIZED to trigger this check?
  Min_Caps_Percentage: 50

  # How many capitalized letters must appear after each other to trigger this check?
  # This is IRRESPECTIVE of the caps percentage setting above. Those two settings are
  # evaluated "this, or that" so if one of the two conditions are true, the anti-caps fires.
  Min_Caps_In_A_Row: 5

  # Allow the following words to be capitalized.
  Whitelist:
  - 'OMG'
  - 'LOL'
  - 'WTF'
  - 'WOW'
  - 'ROFL'
```
