### ISSUE TITLE
Issue with doman whitelist

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [kangarko/ChatControl#74]
I can't get the domain filter to work, this is my config:
```
  Whitelisted:
    IP:
    - 0.0.0.0
    Domains:
    - youtube.com
    - google.com
    - mcsimplegaming.com
    - www.mcsimplegaming.com
    - mojang.com
    - minecraft.net
    - bit.ly
    - prntscr.com
    - gyazo.com
```
tested with a player writing minecraft.net, it blocked it
