### ISSUE TITLE
1.16.4 - Changing/resetting color wont remove bold formatting

### ISSUE THREAD

**Issue by Qw4rtz** [kangarko/ChatControl#75]
I think the title say it all
![fyUyFKg7K3](https://user-images.githubusercontent.com/6247479/99186706-7a719e00-2752-11eb-8837-022c1e51d489.png)

Here's the formatting for my "AntiCheat" channel:
```YAML
Parts: 
  prefix: 
    Message: "&8[&c&lA&cnti &c&lC&cheat&8] "
    Hover: 
      - 'Anti cheat notification'
      - '&7Server: &a{server_name}'
  message: 
    Message: "{message}"
```

It should remove bold formatting when changing color or resetting with &r
