### ISSUE TITLE
1.16.5: Can we please get {item_type_capitalized} variable for spy-anvil.yml?

### ISSUE THREAD

**Issue by c0wg0d** [kangarko/ChatControl#751]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

I would really like to have an {item_type_capitalized} variable for use in spy-anvil.yml that would return "Golden Carrot" instead of "golden carrot".

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: true
> 
> I would really like to have an {item_type_capitalized} variable for use in spy-anvil.yml that would return "Golden Carrot" instead of "golden carrot".

Hey!
Create a variable `item-type-capitalized.yml` in the plugin variable folder, and paste the following inside: 
```yaml
Type: format

Key: item_type_capitalized

Value: |-
    capitalizedType();
    
    function capitalizedType() {
      var wordUtils = Java.type("org.apache.commons.lang.WordUtils");
      var item = '{item_type}';
  
      return wordUtils.capitalize(item);
    }

Sender_Condition: ''

Sender_Permission: ''

Receiver_Condition: ''

Receiver_Permission: ''

Hover: []

Hover_Item: []

Open_Url: ''

Suggest_Command: ''

Run_Command: ''
```

Once this is done, try using `{item_type_capitalized}`.
