### ISSUE TITLE
1.16.5: Something wrong with centering?

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#764]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

![image](https://user-images.githubusercontent.com/18662086/109701834-c6c2db80-7b93-11eb-9479-5079c0505f15.png)
```
# -----------------------------------------------------------------------------------------
# The default chat format used as a message of the day.
# -----------------------------------------------------------------------------------------

# The parts of this format.
Parts:
  part1:
    Message:
    - ''
    - '<center>&b&lTrinity&e&lMC'
    - '<center>&7&lDoporučená verze je &c&l1.16.5'
    - ''
    - '<center>&eSurvival, Vanilla, SkyBlock, AcidIsland&7.'
    Open_Url: https://trinitymc.eu/
  part2:
    Message:
    - '<center>&c/survival &7- světy s doplňky (Slimefun, magie...).'
    Open_Url: https://trinitymc.eu/survival/
  part3:
    Message:
    - '<center>&c/svanilla &7- bez doplňků, SkyGrid, Creative.'
    Open_Url: https://trinitymc.eu/semi-vanilla/
  part4:
    Message:
    - ''
    - '<center>&7Zde můžeš zkusit &c/pg&7, &c/gadgets&7, &c/parkour&7.'
    Open_Url: https://trinitymc.eu/
  part5:
    Message:
    - ''
    - '<center>&7Mrkni na &c/web&7, &c/discord&7, &c/facebook&7, &c/instagram &7aj.'
    Open_Url: https://discord.com/invite/bdynagG
    #- "&7The chat is NOT monitored and we respect your privacy rights. Just kidding."

```

TrinityMC - server name is somehow wrongly centered...

And when using just this in the first part,
```
    - '<center>&b&lTrinity&e&lMC'
    - '<center>&7&lDoporučená verze je &c&l1.16.5'
```
it doesn't center neither.
![image](https://user-images.githubusercontent.com/18662086/109701998-f671e380-7b93-11eb-975d-bc541658e69b.png)
