### ISSUE TITLE
1.16.5: Possible implications of changing a command aliases?

### ISSUE THREAD

**Issue by TheIntolerant** [kangarko/ChatControl#767]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hello,
I've noticed a few people change such aliases (as shown below) and completely remove the ``- 'mute'`` for a different command and was wondering if it would be safe for me to change the example below, so the only command is ``/muteall`` or will this have negative implications? I know how to work around this with command.yml and chatcontrol rules etc but was just curious. Thanks.
```
Mute:

  # Should we enable this feature?
  Enabled: true

  # The commands that invoke the mute feature.
  # EDIT AS YOU WISH BUT DO NOT REMOVE THE FIRST ALIAS
  Command_Aliases:
  - 'mute'
```
