### ISSUE TITLE
1.16.5: Performance...

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#782]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi I reported today and yesterday few timings to **several devs** and they told me that **ChatControlRed** is one of the worst plugin by the timings.  Also mainly by the spark.

https://spark.lucko.me/#CSNSYiDThY
https://spark.lucko.me/#MuzREldpav -> 5 minutes one
https://timings.aikar.co/?id=d7d5325a26f14d348f0559dc45bfe2ca

### I will quote the author of Slimefun (BusyBiscuit):

> On your main thread "ChatControl" has the highest impact, followed by SensibleToolbox (which is to be expected since it is in beta and performance won't matter for that one for a while)
> Absolutely not. For a chat plugin, this is really a bad sign.
> Anyway...
> You should send the author of ChatControl your timings report.
> CHC is doing a LOT of serialization on text which does not necessarily seem... well... necessary...

> Also just to illustrate it...
> This is what happens on the main thread... in a task from ChatControl. It is a bit ridiculous, not sure why...

![image](https://user-images.githubusercontent.com/18662086/110261428-780cab80-7fb0-11eb-95c7-a4c05c56ddd1.png)

> He seems to be using a text library called "Remain"
> And that on the protocol level... using ProtocolLib
> It is a big rabbit hole from there
> I mean... he is right about the timings part.
> But the spark profile is detailed enough...

### Related to boss plugin https://github.com/kangarko/Boss/issues/815:

> About the Boss plugin, the lag is coming from very frequent Metadata access when checking for Boss-spawning conditions.
> Brushing it off as "it is not smart enough and doesn't show what is behind" sounds more like an excuse for not really looking into it.
> Not trying to discredit him here but Spark shows exactly what's behind these timings.
> Normal timings, yes, those are mostly useless for tracking down sources of lag.
> But that's what Spark is specifically designed for. And it very clearly shows what's behind that lag.
> I'll just give him the benefit of doubt and assume he simply overlooked the spark report there and only saw the standard timings.
> Or perhaps didn't know how to interpret it, in which case there are more than enough resources online and also a Spark discord.

### 7.3. trimings and respond from Yatopia devs:
https://spark.lucko.me/#IY75irs2fz
https://timings.aikar.co/?id=ba1a3234fbb14c2fb6d19af079e2aa7b

> Maybe stopping using this would help
![image](https://user-images.githubusercontent.com/18662086/110261555-fb2e0180-7fb0-11eb-9b87-cd8bccb23596.png)
![image](https://user-images.githubusercontent.com/18662086/110261557-fc5f2e80-7fb0-11eb-8cf3-89bc4dfaada1.png)
![image](https://user-images.githubusercontent.com/18662086/110261571-041ed300-7fb1-11eb-8275-2f8c73b53037.png)

**Comment by kangarko** [comment]
Thanks, it's true that we use a ton of component serialization to support the various features of the chat such as interactive hover events or showing different things for the sender/receiver.

I will investigate this and try to reduce the impact for executing commands.

**Comment by bobhenl** [comment]
Here are new timings
https://timings.aikar.co/?id=a39b5c7f77ba4023bd74d72130d5f5a2
https://spark.lucko.me/#9Bd5VsrSdh

And here is my Lobby server, this happened when players joined at once there:
![image](https://user-images.githubusercontent.com/18662086/110837130-278f9980-82a1-11eb-9669-18b365d3381d.png)
https://timings.aikar.co/?id=1560997b1a2d4abf8e83420d6a0a0d1e

**Comment by kangarko** [comment]
Thanks, this is a long-term thing since I will be rewriting some parts of the plugin, cannot be fixed in a day, so I am just leaving this open and will keep on communicating if needed thanks for your patience

**Comment by bobhenl** [comment]
https://spark.lucko.me/60I0727oXJ?hl=9949,14865,42,23,37697
![image](https://user-images.githubusercontent.com/18662086/111089537-a51b0a00-852c-11eb-8844-6860604beacb.png)
This is maybe quite big. Luck from LuckPerms highlighted me it.

**Comment by kangarko** [comment]
Please update to me your debug.log file just in case.

**Comment by bobhenl** [comment]
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6140746/debug.zip)
And btw forget to mention "cut log" https://pastebin.com/82m88YP8 so you can try to see chc problems there (like regex one, or maybe some quit/join). I can send whole one with spark tickmonitoring enabled for one day, here it is.

[2021-03-14-6.log.gz](https://github.com/kangarko/ChatControl-Red/files/6140751/2021-03-14-6.log.gz)

**Comment by kangarko** [comment]
Thanks, let me know how the next version performs without the formerly thrown errors

**Comment by bobhenl** [comment]
https://timings.aikar.co/?id=7e03f6888cfa4ef29ed39f98808c358b#plugins
![image](https://user-images.githubusercontent.com/18662086/111186176-0eddf700-85b3-11eb-9845-1de3349f25d0.png)

Mhm, I'm not really sure...


![image](https://user-images.githubusercontent.com/18662086/111912217-fcf3cc80-8a68-11eb-9264-dfa7f49b43a1.png)
https://spark.lucko.me/kazp6bsOUQ


Here are logs when I sent all players on Lobby:
![image](https://user-images.githubusercontent.com/18662086/112181131-6e17b900-8bfc-11eb-83a0-6d02c33990f5.png)
https://spark.lucko.me/w1fzyTeXtU
https://timings.aikar.co/?id=a2fb6016176d44c5ae7d60e721eed22b#plugins

**Comment by kangarko** [comment]
For now I've added an experimental async toggle to Messages.Async in settings. Whether this is safe really depends on your variables, javascripts and operators, those that work with data, chunks, worlds etc. or save data are unsafe. I recommend you clone your server setup to localhost and test it with that option on true and if there's no errors/issues then port this to production. 

This will come in the next version.

**Comment by bobhenl** [comment]
Mhm, just quit message is a little bit broken:
![image](https://user-images.githubusercontent.com/18662086/112726292-e2b06780-8f1c-11eb-8e98-ef86cffd3e0f.png)
![image](https://user-images.githubusercontent.com/18662086/112726293-e3e19480-8f1c-11eb-9e7c-ced65cb08e36.png)
![image](https://user-images.githubusercontent.com/18662086/112726294-e47a2b00-8f1c-11eb-815d-d203bc1673dd.png)


```
# -----------------------------------------------------------------------------------------
# Represents a chat format file that can be used to stylize messages.
# See the chat.yml for a tutorial on how this works.
# -----------------------------------------------------------------------------------------

# The parts of this format.
Parts:
  First_Part:
    Message: '&8&l[&4&l-&8&l] &7{cmi_user_display_name}'
    Hover:
    - '&8&l▄▄▄ {pl_prefix+} &7{player} &8&l▄▄▄'
    - '&7Peníze&8 &8» &e{vault_eco_balance_fixed}&7€'
    - '&7Odehráno &8» &e{statistic_hours_played}&7h'
    - '&7Hlasů &8» &e{votingplugin_total}'
    - ''
    - '&7Odpojen v &e{localtime_time_kk:mm:ss}'
    - '&7Klikni pro odeslání mailu hráči.'
    Suggest_Command: '/mail send {player_name} '

```

Quit message, without async it works
