### ISSUE TITLE
What's this? In my MOTD

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#795]
Hi, what's the yellow - at the end of Únorový .... line? I don't have anything like this in code
![image](https://user-images.githubusercontent.com/18662086/111053636-adf4d880-8465-11eb-8c0d-0de5360c4f0a.png)

```
# The parts of this format.
Parts:
  part1:
    Message:
    - '&a&m<-=-------------&r &b&lTrinity&e&lMC &fSvanilla &a&m-------------=->'
    - '&7Můžeš hrát: &eSurvival, Vanillu, SkyBlock, AcidIsland, a navíc'
    - '&eSkyGrid, Creative či dobrodružné mapy! &c&l/svety &7(klik)'
    - '&r'
    Open_Url: https://trinitymc.eu/semi-vanilla/
  part2:
    Message:
    - '<center>&b&lÚnorový QoL update 2021'
    Open_Url: https://trinitymc.eu/forum/topic/65-norov-qol-update-2021/
  part3:
    Message:
    - '&e - &7Využij &f25% &7slevy na &c/store &7(klik) a mrkni do &c/souteze'
    Open_Url: https://store.trinitymc.eu/
  part4:
    Message:
    - ''
    - '&e - &7Sleduj novinky a prozkoumej web – &c/changelog &7(klik)'
    Open_Url: https://trinitymc.eu/
  part5:
    Message:
    - ''
    - '&e - &7Hlasuj přes &c/vote &7a využij &c/denniodmena &7i &c/invite &7(klik)'
    Open_Url: https://trinitymc.eu/vote/
  part6:
    Message:
    - ''
    - '&e - &7Propoj si účet s Dis a mailem! &c/discord &7a &c/setemail &7(klik)'
    - '&a&m---------------------------------------------------'
    Open_Url: https://discord.com/invite/bdynagG
    #- "&7The chat is NOT monitored and we respect your privacy rights. Just kidding."
```
