### ISSUE TITLE
1.16.5: Center on Bedrock (via Geyser)

### ISSUE THREAD

**Issue by bobhenl** [kangarko/ChatControl#797]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true

Hi, I wanna ask if it could be possible by you to somehow improve center tag when user is from Bedrock and open whole chat?
But I'm not really sure if you can do it.
![image](https://user-images.githubusercontent.com/18662086/111167409-63787680-85a1-11eb-917c-eb18ddf8f6e4.png)

```
Parts:
  part1:
    Message:
    - ''
    - '<center>&b&lTrinity&e&lMC'
    - '<center>&7&lDoporučená verze je &c&l1.16.5'
    - ''
    - '<center>&eSurvival, Vanilla, SkyBlock, AcidIsland&7.'
    Open_Url: https://trinitymc.eu/
  part2:
    Message:
    - '<center>&c/survival &7- světy s doplňky (Slimefun, magie...).'
    Open_Url: https://trinitymc.eu/survival/
  part3:
    Message:
    - '<center>&c/svanilla &7- bez doplňků, SkyGrid, Creative.'
    Open_Url: https://trinitymc.eu/semi-vanilla/
  part4:
    Message:
    - ''
    - '<center>&7Zde můžeš zkusit &c/pg&7, &c/gadgets&7, &c/parkour&7.'
    Open_Url: https://trinitymc.eu/
  part5:
    Message:
    - ''
    - '<center>&7Mrkni na &c/web&7, &c/discord&7, &c/facebook&7, &c/instagram &7aj.'
    Open_Url: https://discord.com/invite/bdynagG

```
