### ISSUE TITLE
1.12.2 Where do I specify the {player_prefix+}?

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#802]
I can't find where I customize the variable.

**Comment by TheIntolerant** [comment]
When asking for help, it is important to be as specific as possible so assumptions do not need to be made, such as what you are trying to do, etc.

Assuming this is in regards to the format of chat?
In your settings.yml file, under ``Channels:`` -> ``List:``
You should see something like (unless edited)
```
  List: 
    standard: 
      Format: chat
      Format_Spy: "@noprefix chat"
    admin: 
      Format: admin-chat
      Format_Console: '[A-chat {player}] {message}'
    global: 
      Format: global-chat
    ranged: 
      Format: "&6[ranged] &7{pl_prefix+}{player}:{pl_suffix} {message}" 
      Range: 100 
      Bungee: false
    towny: 
      Format: chat 
      Party: towny-town
    helpop:
      Format: helpop
```

If I want to use ``{player_prefix+}`` in the ``standard`` channel, I can see the "format" for the standard channel is called ``chat``. To edit this format, I need to find the file ``chat.yml`` which is located ``Home\Plugins\ChatControl-Red\formats\``

**Comment by TheIntolerant** [comment]
I have made the formats for main chat on my server super simple but feel free to read [Wiki - Formats](https://github.com/kangarko/ChatControl-Red/wiki/Formats) for more info about how formats work.

Just as an example, my main chat format file looks like this.
```
Parts:
  everything:
    Message: '&r{pl_prefix}&7{display_name}{pl_suffix+}&8: &r{message}'
```
It doesn't need to be that simple, also I highly recommend checking out the wiki that I have linked above, as this could save you time.
Hope this helps! :)

**Comment by nikitushu2** [comment]
Thank you for the explanation. I wanted to configure the value of the {pl_prefix} variable itself. I know how to use it. But, for example, how do I put a list of prefix names ("admin", "builder", etc) into the variable itself, so that it automatically shows the name based on permission a player has?

**Comment by ElBananaa** [comment]
> Thank you for the explanation. I wanted to configure the value of the {pl_prefix} variable itself. I know how to use it. But, for example, how do I put a list of prefix names ("admin", "builder", etc) into the variable itself, so that it automatically shows the name based on permission a player has?

Hey!

@gone-incognito Thanks for you help!

@nikitushu2 Actually, there's no way to configure the {pl_prefix} variabled as you want. As stated on the wiki (C.f. https://github.com/kangarko/ChatControl-Red/wiki/Variables), the `{pl_prefix}` placeholder comes from Vault, the plugin doesn't change anything to it.
![image](https://user-images.githubusercontent.com/53318613/111502723-682a5f80-8746-11eb-9280-df96532afb2e.png)

**Comment by TheIntolerant** [comment]
Just to add to what was said above, in the format file for the channel, you can use something like what I have provided below, in order to show a prefix based on the permissions the user has, so to remove a prefix, you need to negate the permission node you've set under ``Sender_Permission:``.
```
Parts: 
  admin-prefix: 
    Message: "&c[Admin] &r"
    Sender_Permission: chatcontrol.group.admin
  builder-prefix: 
    Message: "&6[Builder] &r"
    Sender_Permission: chatcontrol.group.builder
  vip-prefix: 
    Message: "&a[VIP] &r"
    Sender_Permission: chatcontrol.group.vip
  player-name: 
    Message: "{display_name}"
  message: 
    Message: "{player_suffix}&7: &f{message}"
 ```
 
 Also, the "sender_permission" can be whatever you want.
 
 **NOTE**
 These prefixes cannot be seen by other plugins unless they are also stored in a permissions plugin etc such as luckperms etc.
