### ISSUE TITLE
/nick colours

### ISSUE THREAD

**Issue by BlueFyreMatt** [kangarko/ChatControl#804]
I think there's a compatability issue between essentials and this plugin, in that when trying to use colour codes or formatting codes with the /nick command, if essentials is installed on the server, the colour codes and formatting codes don't seem to work, leaving your nickname as the configs default format.

The nickname itself is applied successfully (I.E adding the nickname Matt), just without the formatting or colours you've specified when running the command

**Comment by ElBananaa** [comment]
> I think there's a compatability issue between essentials and this plugin, in that when trying to use colour codes or formatting codes with the /nick command, if essentials is installed on the server, the colour codes and formatting codes don't seem to work, leaving your nickname as the configs default format.
> 
> The nickname itself is applied successfully (I.E adding the nickname Matt), just without the formatting or colours you've specified when running the command

Hey!
Please follow the bug-report format. We can't provide proper help if we dont have the infos required about your environment.

**Comment by ElBananaa** [comment]
Also, In order to use another plugin nick system, in your chatcontrol-red settings file, your `Apply_On` part must look like the example below. (Make sure to read the comments too)

```yaml
Tag:
  
  # Where should we enable this feature?
  # Available options: prefix, nick, suffix
  # Leave empty to completely disable custom prefixes, nicks and suffixesa.
  #
  # **IMPORTANT** Remove "nick" there if you use another nicks plugin such as Nicky or CMI.
  # However, we only offer limited support for these plugins now using the {nick} variable.
  Apply_On:
  - 'prefix'
  - 'suffix'
```

As you can see on this screenshot, it works perfectly on my side following the steps listed in the file, on a completely fresh setup with updated plugins.
![image](https://user-images.githubusercontent.com/53318613/111501853-9bb8ba00-8745-11eb-9276-c9b5a755fd65.png)
