### ISSUE TITLE
1.16.5. How to log commands?

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#848]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: true

I know that chat logs are being kept in log.csv. It does not record commands that were typed by players though.

**Comment by ElBananaa** [comment]
Hey!

In your settings.yml, look for this part:
```yaml
Log:
  
  # What player actions should be logged?
  # Options: chat, command, private_message, mail, sign, book, anvil
  Apply_On:
  - 'chat'
  - 'command' # <-- ADD THIS LINE
  - 'private_message'
```
