### ISSUE TITLE
1.16.5 Log.csv does not update even after 24 hours

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#849]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: true

What could be wrong?

Here some information that might help:
1. Debug: [https://ufile.io/uif5q61a](https://ufile.io/uif5q61a)
2. Log section in settings.yml:
```
Log:
  
  # What player actions should be logged?
  # Options: chat, command, private_message, mail, sign, book, anvil
  Apply_On:
  - 'chat'
  - 'command'
  - 'private_message'
  - 'mail'
  - 'sign'
  - 'book'
  - 'anvil'
  
  # The threshold after which we should clean the logs
  Clean_After: 90 days
  
  # Commands that will be saved along with the chat messages. To log all, set it to ["*"]
  # The Apply_On list must contain "command" for any commands below to be logged.
  Command_List:
  - '/tell'
  - '/w'
  - '/m'
  - '/t'
  - '/pm'
  - '/message'
  - '/msg'
  - '/whisper'
  - '/mail'
  - '/reply'
  - '/r'
  - '/me'
  - '/tag'
  - '/nick'

# -------------------------------------------------------------------------------------------------
# Remove unwanted messages from the console.
# -------------------------------------------------------------------------------------------------
Console_Filter:
  
  # Should we enable this feature? *DOES NOT SUPPORT RELOAD* *MAY BREAK YOUR MULTICRAFT PANEL*
  Enabled: true
  
  # Remove these messages from console using the "contains" method.
  # Does not need to be whole message, just a part of the message you want to block.
  #
  # [NOTICE] If you have Multicraft, DO NOT place the following messages there else 
  #          your server will literaly stop working properly. This is a bug in Multicraft.
  # - UUID of player
  # - lost connection
  Messages:
  - 'Reached end of stream for'
  - 'Connection reset'
```
