### ISSUE TITLE
1.16.4 | Only two hover work, not third, is for suggested commands too have not check the rest.

### ISSUE THREAD

**Issue by broken1arrow** [kangarko/ChatControl#87]
I can check rest like Open_Url as same problem. Two examples I use.
```
Parts:

  # See the chat.yml format file for a tutorial on how this works.
  everything:
    Message: '&5✉ &8{sender}'
    Hover:
      - '     &8~ &3Private Message &8~     '
      - '&8&oSent {timestamp}'
      - '&3Sender: &f{sender}'
      - '&3Receiver: &f{receiver}'
      - '&3Body: &f{message}'
      - '&aKlicka för att skriva till &9{player_name}'
    Suggest_Command: /msg {player_name}
  Second_Part:
    Message: ' &a☞&6'
    Hover:
      - '     &8~ &3Private Message &8~     '
      - '&aKlicka för att telepotera till &9{player_name}'
    Suggest_Command: /tpa {player_name}
  Third_Part:
    Message: ' {receiver}: &d&l{message}'
    Hover:
      - '     &8~ &3Private Message &8~     '
      - '&8&oSent {timestamp}'
      - '&3Sender: &f{sender}'
      - '&3Receiver: &f{receiver}'
      - '&3Body: &f{message}'
      - '&aKlicka för att skriva till &9{player_name}'
    Suggest_Command: /msg {player_name}
```
```
Parts:

  # See the chat.yml format file for a tutorial on how this works.
  spies-prefix:
    Message: "&8[&5Spy&8] &f"
    Receiver_Condition: "{receiver_is_spying_{channel}}"
    Hover: "&dClick to stop spying {channel} channel."
    Run_Command: "/{label_spy} toggle chat {channel}"
  everything:
    Message: '&9Lokalt-{luckperms_prefix_element_highest}'
    Hover:
      - '&8*-----* &5{player} &8*-----*'
      - '&7Medelande sänt: &b{timestamp}'
      - '&7Värld&8: &b{world}'
      - '&aKlicka för karta'
    Open_Url: http://Midgardsaga.nu:8365
  Second_Part:
    Message: ' &f{player}&7&f'
    Hover:
      - '&7Rank&8: &b{pl_group}'
      - '&7Bor i:&8 {lands_land_name}'
      - '&7Första spel datum&8: &b{player_first_join_date}'
      - '&7Speltid totalt&8: &b{cmi_user_playtime_hoursf} timmar'
      - '&aKlicka för privat medelande'
    Suggest_Command: '/msg {player} '
  Third_Part:
    Message: '&7: &2{message}'
    Hover:
      - '&7Message issued: &b{timestamp}'
      - '&aKlicka för at telepotera till {player}'
    Suggest_Command: /tpa {player}
```

**Comment by broken1arrow** [comment]
I remove Hover and Suggest_Command in Second_Part: and Third_Part: still not work (seams like only read first two parts when it come to hover and commands).

But it read Sender_Permission: but not Receiver_Permission: 

I can try out rest, if I understand how they work (Sender_Condition: and Receiver_Condition:) :)

**Comment by broken1arrow** [comment]
If hard to get how i mean. I put up examples i try.

this work, but not hover only Sender_Permission: work
```
Parts:

  # See the chat.yml format file for a tutorial on how this works.
  spies-prefix:
    Message: "&8[&5Spy&8] &f"
    Receiver_Condition: "{receiver_is_spying_{channel}}"
    Hover: "&dClick to stop spying {channel} channel."
    Run_Command: "/{label_spy} toggle chat {channel}"
  everything:
    Message: '&9Lokalt-{luckperms_prefix_element_highest}'
    Hover:
      - '&8*-----* &5{player} &8*-----*'
      - '&7Medelande sänt: &b{timestamp}'
      - '&7Värld&8: &b{world}'
      - '&aKlicka för karta'
    Open_Url: http://Midgardsaga.nu:8365
  Second_Part:
    Message: ' &f{player}&7&f'
    Hover:
      - '&7Rank&8: &b{pl_group}'
      - '&7Bor i:&8 {lands_land_name}'
      - '&7Första spel datum&8: &b{player_first_join_date}'
      - '&7Speltid totalt&8: &b{cmi_user_playtime_hoursf} timmar'
      - '&aKlicka för privat medelande'
    Suggest_Command: '/msg {player} '
  Third_Part:
    Message: '&7: &2{message}'
    Hover:
      - '&7Message issued: &b{timestamp}'
      - '&aKlicka för at telepotera till {player}'
    Sender_Permission: : test.pertm
```
this not work and yes I have two accounts when i test and 2 first examples I post not work, the hover and the suggested commands (only messenger part work)
```
Parts:

  # See the chat.yml format file for a tutorial on how this works.
  spies-prefix:
    Message: "&8[&5Spy&8] &f"
    Receiver_Condition: "{receiver_is_spying_{channel}}"
    Hover: "&dClick to stop spying {channel} channel."
    Run_Command: "/{label_spy} toggle chat {channel}"
  everything:
    Message: '&9Lokalt-{luckperms_prefix_element_highest}'
    Hover:
      - '&8*-----* &5{player} &8*-----*'
      - '&7Medelande sänt: &b{timestamp}'
      - '&7Värld&8: &b{world}'
      - '&aKlicka för karta'
    Open_Url: http://Midgardsaga.nu:8365
  Second_Part:
    Message: ' &f{player}&7&f'
    Hover:
      - '&7Rank&8: &b{pl_group}'
      - '&7Bor i:&8 {lands_land_name}'
      - '&7Första spel datum&8: &b{player_first_join_date}'
      - '&7Speltid totalt&8: &b{cmi_user_playtime_hoursf} timmar'
      - '&aKlicka för privat medelande'
    Suggest_Command: '/msg {player} '
  Third_Part:
    Message: '&7: &2{message}'
    Hover:
      - '&7Message issued: &b{timestamp}'
      - '&aKlicka för at telepotera till {player}'
   Receiver_Permission: test.pertm

```
