### ISSUE TITLE
1.16.5 : Can I have two ranged channel?

### ISSUE THREAD

**Issue by enkacang** [kangarko/ChatControl#870]
Is it possible to have two ranged channel?

If it's possible, how can I obtain it?

**Comment by enkacang** [comment]
and how if it's possible to set delay per channel.

**Comment by ElBananaa** [comment]
> Is it possible to have two ranged channel?
> 
> If it's possible, how can I obtain it?

Hey!
Yes, you can make multiple ranges channels. To do so simply configure your `List:` part in the settings file like that :
```
  List:
    local1:
      Format: general-chat
      Range: 100
      Message_Delay: 1 second
    local2:
      Format: staff-chat
      Range: *
      Range_Worlds: spawn
      Message_Delay: 20 seconds
```
Basically, in the first channel, local1, players in the same world will only see the message if there's a distance of 100 blocs or less between them and the sender.
In the 2nd channel, local2, we defined `Range: *` which basically means that the whole world will see the message. Then, under we defined `Range_Worlds: spawn` which means that this only applies to the world named `spawn`.

Regarding the delay, simply add the `Message_Delay:` part under each channel. Don't forget to specify the duration. So if you want a delay of 5 minutes, add `Message_Delay: 5 minutes`.
