### ISSUE TITLE
Lag notice

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl#88]
Sometimes I get notices that it too quite a while to parse a rule.
How and why does this happen?
CHC 5.2.8 (I have the pro version still in my dev environment ;))

```
[12:34:17 INFO]: aPlayer issued server command: /r na.eu/city oder so
[12:34:17 INFO]: *--------- ChatControl rule match on aPlayer --------- ID 2
[12:34:17 INFO]: MATCH: [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(me|de|at|ch|com|org|net|cz|co|uk|sk|biz|mobi|xxx|eu|to|li|tk|tv)\b
[12:34:17 INFO]: CATCH: /r na.eu/city oder so
[12:34:17 INFO]: [ChatControl] aPlayer violated rule ID 2, triggered advertisement filter with: /r na.eu/city oder so
[12:34:17 INFO]: [ChatControl] [Lag] Rule parse: global took 136.585 ms
[12:34:17 INFO]: Original message cancelled.
[12:34:17 INFO]: [ChatControl] [Lag] Rule parse took 136.883 ms
[12:34:17 INFO]: [ChatControl] [Lag] Command event took 136.996 ms
```

**Comment by kangarko** [comment]
If the regular expression's processing takes more time then specified in the settings.yml (Log_Lag_Over_Milis), a warning message is printed. This is nothing severe and as long as it don't happen a lot, you shouldn't be worried about it. I see you are running a german server, and the regexes are especially sensitive to non-english characters (ä.ö, etc) and takes a bit longer to process.

It can also be that there is something in that rule (ID 2), that makes it longer to process. Can you post me the effective part from handlers.yml and also the rule itself - if you have modified it?

**Comment by EvilOlaf** [comment]
I am on vacation right now, so I have limited access only.
I'll catch up in a few days.

**Comment by EvilOlaf** [comment]
```
advertisement:
  Bypass_With_Permission: "chatcontrol.bypass.ad"
  Ignored_In_Commands:
    - // # WorldEdit
    - /auction
    - /register
    - /reg
    - /login
    - /l

  Player_Warn_Message: "&7Werbung/URLs/IPs ist nicht erlaubt. Tippfehler?"
  #Broadcast_Message: "&c%player might have advertised, alert admins!"
  Console_Message: "%player violated rule ID %ruleID, triggered %handler filter with: %message"


#  Staff_Alert_Message: "&8[&7Ad/ID %ruleID&8] &7%player: &f%message"
  Staff_Alert_Message: "&4!!! &8[&6Werbung/ID %ruleID&8] &6%player: &c%message"
  Staff_Alert_Permission: chatcontrol.notify.ad

  Block_Message: true
  Write_To_File: logs/advertisements.txt
```

```
match [a-zA-Z0-9\-\.]+\s?(\.|dot|\(dot\)|-|;|:|,)\s?(me|de|at|ch|com|org|net|cz|co|uk|sk|biz|mobi|xxx|eu|to|li|tk|tv)\b
ignore string minecraft.net|youtube.com|imgur.com|teamspeak.de|teamspeak.com|serverliste.org|minecraft-server.eu|na4.eu|i-net|gamepedia.com|youtube.com|youtu.be|google.com|google.de|mojang.com|google.de|bing.com|facebook.com|facebook.de$
id 2
before strip [\(\[\]\)]
handle as advertisement
```
