### ISSUE TITLE
1.16.5: Placeholders in MOTD are very weird

### ISSUE THREAD

**Issue by ghost** [kangarko/ChatControl#884]
For some reason the formatting for placeholders in the MOTD works very inconsistent. The issue is that it only formats the placeholder if there is another placeholder present. 

Example:

```
Parts:
  
  # See the chat.yml format file for a tutorial on how this works.
  everything:
    Message:
    - '&8&m-------------------------------------------------&r'
    - '%tab_replace_server_online%'
    - '               &f◆ %tab_replace_cmi_random_1_3% &8[1.16.5] &f◆          '
    - ''
    - '               &fThere are #f4a2c7%server_online%#ef98ca/#e98ecd1#e484d00#df7ad30 &fplayers online...      '
    - '              &fCommunity, News & Events: #FFC0CB/discord        '
    - ''
    - '&8&m-------------------------------------------------&r'
    #- "&7The chat is NOT monitored and we respect your privacy rights. Just kidding."
```

Now the first placeholder %tab_replace_server_online% will not work but %tab_replace_cmi_random_1_3% will correctly output. But say if i remove the first placeholder everything just magically breaks. Or sometimes none of the placeholders work.

I'm not entirely sure where this issue comes from but could you please test around with using placeholders in the motd format and revise your code?

Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false
