### ISSUE TITLE
1.16.5 Open_Url part does not work

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#909]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

```
# -----------------------------------------------------------------------------------------
# Represents a chat format file that can be used to stylize messages.
# See the chat.yml for a tutorial on how this works.
# -----------------------------------------------------------------------------------------

# The parts of this format.
Parts:
  fifth:
    Message:
    - ' '
    - '#edc951//wand#bbbbbb gives the axe for the worldedit'
    - '#edc951//wesv toggle#bbbbbb switches the selection visualizer'
    - '#edc951//pos1#bbbbbb(#edc951//pos2#bbbbbb) sets position 1(2) to your location'
    - "#edc951//set {block}, {block}, ... #bbbbbb sets all the selection to the block(s)"
    - '#edc951//cut#bbbbbb copies the selection to the clipboard'
    - '#edc951//copy#bbbbbb without cutting'
    - '#edc951//flip {direction}#bbbbbb flips the contents of the clipboard'
    - '#edc951//rotate {y°} {x°} {z°}#bbbbbb rotates the contents of the clipboard'
    - "#edc951//paste#bbbbbb pastes the clipboard's contents"
    - "#edc951//paste -a#bbbbbb skips air blocks"
    - "#edc951//undo#bbbbbb undoes the last action"
    - "#edc951//redo#bbbbbb redoes the last action"
    - '#edc951//sel {shape}#bbbbbb changes a region selector'
    - '#edc951//sel#bbbbbb clears the region selector'
    - '#edc951//count {block} #bbbbbb counts how many blocks in the selection'
    - ' '
    - '#bbbbbb&oTab complete for more commands#bbbbbb&o or check #edc951[&othe official wiki#edc951]&o.'
    Open_Url:
    - "https://wiki.intellectualsites.com/FastAsyncWorldEdit/Commands"
```

Debug: [https://ufile.io/7ryj1gor](https://ufile.io/7ryj1gor)

Issue: Open_Url does not open url upon clicking the message part in the gamechat
