### ISSUE TITLE
1.16.5, DiscordSRV Discord-Minecraft Format?

### ISSUE THREAD

**Issue by xivamnain** [kangarko/ChatControl#911]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true/false

So i have a question and sorry at first if i am using a wrong format or something because i don't really understand it here how this works, i fairly have a simple question/issue, So i have installed ChatControlRed on my hub server and i am want to use it with discord srv and so i have the integrations and etc enabled, i got discord srv "hub" channnel connected to my "chat" channel, but the thing is if anyone say anything in discord in minecraft it shows like "{prefix} discordname {suffix}: message" and yes it shows prefix & suffix with columns, is there anyway that i am missing to define discord to minecraft format? i simply want it to be different than the normal "chat" channel format it uses. thanks

**Comment by xivamnain** [comment]
Its been almost 20h now can i please have some support on this...

**Comment by TheIntolerant** [comment]
Hey, so Idk if this is a bug, since I would of thought {prefix} and {suffix} would return empty if sender is discord.

Anyway, in your chat format you could just try something like this, so messages sent from discord have their own format.
```yml
# The parts of this format.
Parts:

  # Show the [X] button only visible to people having permission on 'Receiver_Permission'
  # that enables you to remove chat messages by clicking on them!
  delete-chat: 
    Message: "&8[&4X&8] &f"
    Hover: "&cRemove this message from chat for all players."
    Run_Command: "/{label} internal remove {message_uuid}"
    Receiver_Permission: chatcontrol.removemessages
  
  # The chat format for users on the minecraft server
  player_sender:
    Message: '&r{pl_prefix}&r{display_name}&r{pl_suffix+}&7:'
    Sender_Condition: '{sender_is_player}'
    Hover:
    - '&7Name&8: &f{display_name}'

  # The chat format for users sending messages from discord
  discord_sender:
    Message: '&9[Discord] &7{display_name}&7:'
    Sender_Condition: '{sender_is_discord}'
    Hover:
    - '&7Sent from discord'

  # The chat format for when a message is sent from the console
  console_sender:
    Message: '&4[CONSOLE]'
    Sender_Condition: '{sender_is_console}'
    Hover:
    - '&7Sent from the console'

  # The actual chat message.
  chat_section:
    Message: '&r {message}'
```

FYI, if you do not want the ``[x]`` feature to delete a chat message, just remove this part
```

  # Show the [X] button only visible to people having permission on 'Receiver_Permission'
  # that enables you to remove chat messages by clicking on them!
  delete-chat: 
    Message: "&8[&4X&8] &f"
    Hover: "&cRemove this message from chat for all players."
    Run_Command: "/{label} internal remove {message_uuid}"
    Receiver_Permission: chatcontrol.removemessages
```
