### ISSUE TITLE
1.16.5 Antispam whitelist delay does not turn into blacklist

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#938]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

The part from the Antispam section:
```
  Commands:
    
    # How many seconds must the player wait between each command? Set to 0 to disable.
    Delay: 10 seconds
    
    # Block repetitive commands if they are similar to the previous one, in percent.
    # Set to 0% to disable.
    Similarity: 0%
    
    # Amount of previous commands to check. Example: Setting this to 2 prevents spam like this:
    # /tell Notch lol
    # /tell Notch t
    # /tell Notch lol
    # /tell Notch t
    # Since this uses the Similarity key above it only works if Similarity is not disabled.
    Similarity_Past_Commands: 2
    
    # The threshold after which we will forgive the player for running the same command.
    Similarity_Time: 10 seconds
    
    # Commands the player can type bypassing the Delay above. We check the command label
    # so if you put "/tell" there, "/tell ANYTHING" will be matched.
    #
    Whitelist_Delay:
       - '@blacklist'
       - '/cleanlight'
       - '/setfloor'
       - '/setmain'
```

I want /cleanlight, etc have a delay of 10 seconds before you can type the command again. With the above configuration, no delay is applied (even if I set similarity to 100%).

What am I doing wrong?

**Comment by TheIntolerant** [comment]
I tested this on a fresh install and it worked for me, have you double checked to see if chatcontrol and all dependencies are updated.

**Comment by kangarko** [comment]
Also cannot reproduce, ensure you don't have any bypass permissions, see our permission section on our Wiki or simply test without any special privileges.

**Comment by nikitushu2** [comment]
I have updated the plugin. No special permissions are given.

The issues still persists.

Attaching the debug output: [https://ufile.io/71hnueh7](https://ufile.io/71hnueh7)

**Comment by kangarko** [comment]
@ElBananaa can you please try reproducing? I'll be back in 1-2 days

**Comment by ElBananaa** [comment]
> I have updated the plugin. No special permissions are given.
> 
> The issues still persists.
> 
> Attaching the debug output: https://ufile.io/71hnueh7

Hey!
I just tried under a completely fresh install, and it seems to work fine! 
![image](https://user-images.githubusercontent.com/53318613/116824138-da38f580-ab88-11eb-8685-b09218141409.png)

If the OP system is enabled on your server, make sure the `chatcontrol.bypass.similarity` and `chatcontrol.bypass.delay` are both set on `false` (If using LuckPerms), or denied with your permission plugin.

**Comment by nikitushu2** [comment]
I have realized the problem. Non-aliased commands work fine, while aliased by other plugins commands are not registered by ChatControlRed.

Any ideas on what to do with aliased commands?

**Comment by TheIntolerant** [comment]
@nikitushu2 are these commands from a specific plugin? And if so what plugin?

Some plugins allow you to create an alias command but do not actually register the command, unless you put a specific setting on for that alias such as "register: true". Those commands that aren't registered often aren't detected by other plugins thus plugins like chatcontrol cannot prevent it from being spammed etc.

**Comment by nikitushu2** [comment]
> 
> 
> @nikitushu2 are these commands from a specific plugin? And if so what plugin?

[https://www.spigotmc.org/resources/commandalias.44362/](https://www.spigotmc.org/resources/commandalias.44362/)

**Comment by TheIntolerant** [comment]
@nikitushu2 it seems that plugin isn't registering the commands, that leaves you with 2 options to fix this issue.

1) find a different plugin that allows you to create aliases that can also registered 

Or

2) use a plugin like [Register Commands](https://github.com/RLNT/spigot-registercommands/releases) along side the plugin you are currently using and add those aliases to the register commands plugin as well.

Note: if you go with option 2, you need to restart the server after adding the aliases in order to register the commands.

That should fix your problem.

**Comment by TheIntolerant** [comment]
Or alternatively you can use the commands.yml file on your server [more info here](https://bukkit.fandom.com/wiki/Commands.yml).

From, what I see on that plugin you should be able to replace the plugin completely with that file (though you will lose some features). Any aliases created in the commands.yml are registered once the server is restarted after they are added to the file and will also fix this issue.

**Comment by ElBananaa** [comment]
Hey!
gone-incognito said everything, thanks!
I'm closing this issue for now since there's probably nothing that can be done on the plugin side regarding this.
Feel free to keep commenting down below if you need further assistance tho :D

**Comment by TheIntolerant** [comment]
@nikitushu2 FYI, Chatcontrol can actually replace this plugin used to create aliases, using rules in the ``command.rs`` file.

For example, to create a ``/gamemode survival`` aliases, I would add this in the command.rs file in ``/plugins/ChatControl-red/rules``

```
match \/(gms)
require perm chatcontrol.aliases.gamemodesurvival {error_prefix} &cYou lack ‘{permission}’ permission to use this command.
then command gamemode survival
then deny
dont verbose
```
the perm ``chatcontrol.aliases.gamemodesurvival`` used in this example can be whatever you want.

Refer to [wiki-rules](https://github.com/kangarko/ChatControl-Red/wiki/rules) to learn more about using chatcontrol rules.

**Comment by nikitushu2** [comment]
> chatcontrol.aliases.gamemodesurvival

Very interesting solution! Unfortunately, the alias is not registered by tab completer plugins neither

**Comment by nikitushu2** [comment]
> 
> 
> Or alternatively you can use the commands.yml file on your server [more info here](https://bukkit.fandom.com/wiki/Commands.yml).
> 
> From, what I see on that plugin you should be able to replace the plugin completely with that file (though you will lose some features). Any aliases created in the commands.yml are registered once the server is restarted after they are added to the file and will also fix this issue.

Good solution. Unfortunately, commands.yml can't deal with aliases made from several words.

**Comment by nikitushu2** [comment]
> 
> 
> @nikitushu2 it seems that plugin isn't registering the commands, that leaves you with 2 options to fix this issue.
> 
>     1. find a different plugin that allows you to create aliases that can also registered
> 
> 
> Or
> 
>     1. use a plugin like [Register Commands](https://github.com/RLNT/spigot-registercommands/releases) along side the plugin you are currently using and add those aliases to the register commands plugin as well.
> 
> 
> Note: if you go with option 2, you need to restart the server after adding the aliases in order to register the commands.
> 
> That should fix your problem.

Honestly, I have tried all the possible plugins (even the premium ones). None works properly (they do not register aliases).

RegisterCommands plugin does not support aliases made from several words

**Comment by TheIntolerant** [comment]
> Honestly, I have tried all the possible plugins (even the premium ones). None works properly (they do not register aliases).
> 
> 
> 
> RegisterCommands plugin does not support aliases made from several words

I think you have misunderstood me, basically you use the register command plugin to "register the command" but you would still you to use [https://www.spigotmc.org/resources/commandalias.44362/](https://www.spigotmc.org/resources/commandalias.44362/) or another plugin to create the aliases such as Chatcontrol, in order to actually give the alias command some sort of function.

**Comment by nikitushu2** [comment]
> 
> 
> > Honestly, I have tried all the possible plugins (even the premium ones). None works properly (they do not register aliases).
> > RegisterCommands plugin does not support aliases made from several words
> 
> I think you have misunderstood me, basically you use the register command plugin to "register the command" but you would still you to use https://www.spigotmc.org/resources/commandalias.44362/ or another plugin to create the aliases such as Chatcontrol, in order to actually give the alias command some sort of function.

I am sorry, I meant that RegisterCommands does not support multiple word **commands**.

**Comment by TheIntolerant** [comment]
Sorry, I misread what you said, I think you should try this plugin (link in pastein), also make sure to read the wiki for the plugin.

I have provided an example how a potential way of getting support for multiple word commands, I added a ``/do`` and ``/do something`` commands in the example to show how to go about adding support for ``/do something`` if you cannot set ``register: true`` for ``/do something`` 

Just remember you need to restart the server to see if the command is registering correctly. Multiple word commands should work with ``register: true``, since I have not had such issues using the plugin.

Examples in Pastebin
https://pastebin.com/Fe5XNBeP

If that doesn't work I'm not sure I am able to help much more than that.

**Comment by nikitushu2** [comment]
> 
> 
> Sorry, I misread what you said, I think you should try this plugin (link in pastein), also make sure to read the wiki for the plugin.
> 
> I have provided an example how a potential way of getting support for multiple word commands, I added a `/do` and `/do something` commands in the example to show how to go about adding support for `/do something` if you cannot set `register: true` for `/do something`
> 
> Just remember you need to restart the server to see if the command is registering correctly. Multiple word commands should work with `register: true`, since I have not had such issues using the plugin.
> 
> Examples in Pastebin
> https://pastebin.com/Fe5XNBeP
> 
> If that doesn't work I'm not sure I am able to help much more than that.

Thank you, very interesting plugin. Unfortunately, it does not quite work neither.

This config:
```
do something:
  command: /do something
  type: RUN_COMMAND
  runcmd:
  - "/say $player go do something"
  permission-node: customcommand.dosomething
  permission-error: "&cYou do not have permission for this command"
  register: true

do something:
  command: /do anything
  type: RUN_COMMAND
  runcmd:
  - "/say $player go do anything"
  permission-node: customcommand.doanything
  permission-error: "&cYou do not have permission for this command"
  register: true
 
 
# if the above command does not work when
# trying to register, try registering the root command, "/do" 
 
do:
  command: /do
  type: RUN_COMMAND
  runcmd:
  - "/say $player go do something"
  permission-node: customcommand.dosomething
  permission-error: "&cYou do not have permission for this command"
  register: true
```
  
  Makes all tree commands make the console say "go do something". Basically, only the /do command is registered.
