### ISSUE TITLE
1.16.5: Chat Variables

### ISSUE THREAD

**Issue by Rongel92** [kangarko/ChatControl#943]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Hi, I'm trying to make 2 variables for the chat and failing at getting it to work
I need help on how to make them work
one is [inv] to show the players inventory when you hover above.
The second is [tp] once you click u send a teleport request to the player that posted it.

**Comment by TheIntolerant** [comment]
I'm not sure about the ``[inv]``

but this will work for the ``[tp]``
```yml
# Where should this variable be used?
#
# FORMAT = used in your formats with {syntax}, players cannot use it
# MESSAGE = players can use it with [syntax] in their chat messages
Type: MESSAGE

# The key we look for in the chat surrounded by [] brackets, example:
# chat message: "Hello everyone, [tp] and come check out my building"
Key: tp

# The value the key will be replaced to.
# This uses JavaScript and must return a boolean value.
Value: '"{sender_is_player}" == "true" ? "&a[TP]" : ""'

# What JavaScript condition must return true for this variable to show?
# You can put variables in here to get replaced.
Sender_Condition: ''

# What permission must the message sender have in order for this variable to display to him?
Sender_Permission: ''

# See Sender_Condition, except that we evaluate the JavaScript for each chat message receiver
# and only show the message to those receivers for which the condition returns true.
Receiver_Condition: ''

# What permission must the message receiver have in order for this variable to display to them?
Receiver_Permission: ''

Hover: '&fClick here to send tp request'

Run_Command: "/tpa {player}"
```
