### ISSUE TITLE
Discord format - shows Discord msg before Nick in MC

### ISSUE THREAD

**Issue by dwebeklint** [kangarko/ChatControl#944]
Hello, 

I cant figure out whats wrong with my Discord format. 
Then sending text from Discord -> MC its shows the [text]{nick]
![bild](https://user-images.githubusercontent.com/16137427/116804448-336c3f00-ab1f-11eb-9b80-b7aa2506ce1d.png)
![bild](https://user-images.githubusercontent.com/16137427/116804460-44b54b80-ab1f-11eb-92de-b63427352ef5.png)

In chat.yml
  discord-prefix:
    Message: '&8[&6Discord&8] &f:{message}'
    Sender_Condition: '{sender_is_discord}'
    Hover: '&bJoin our Discord at discord.gg/4Yu5q3uBu4'
    Open_Url: https://discord.gg/4Yu5q3uBu4

Minecraft Version: 1.16.5
MySQL: true
BungeeCord: true
[debug.zip](https://github.com/kangarko/ChatControl-Red/files/6410854/debug.zip)

**Comment by TheIntolerant** [comment]
@AngellitoX It is being added due to
```
  player-name:
    Message: '{player_nick}'
    Hover: '&7Click to message.'
    Suggest_Command: '/tell {player_name} '
```
If you only want this part of the format to be applied to people on the server just change so it also has a ``sender_condition`` for example:
```
  player-name:
    Message: '{player_nick}'
    Hover: '&7Click to message.'
    Suggest_Command: '/tell {player_name} '
    Sender_Condition: '{sender_is_player}'
```
