### ISSUE TITLE
1.16.5 How to disable leave msg after the kick msg?

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#945]
Minecraft Version: 1.16.5
MySQL: true
BungeeCord: false

When players get kicked, the message is broadcasted. But at the same time, the message about their leaving is broadcasted as well, which is unnecessary in this case. How to disable the leave message (only after the kick msgs)?

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: true
> BungeeCord: false
> 
> When players get kicked, the message is broadcasted. But at the same time, the message about their leaving is broadcasted as well, which is unnecessary in this case. How to disable the leave message (only after the kick msgs)?

Hey!
Unfortunately, I can't reproduce this issue. Which plugin handles kicks on your server?

In the plugin settings file, under the `Messages.Apply_On` part, try to remove the kick part.
This is how it should look after : 
```yaml
Messages:
 
  # What aspects of messages should be enabled?
  # Options: join, quit, kick, death, timed
  #
  # If you have another plugin handling join/quit etc. messages, remove them from list below.
  # If you want to hide those messages, leave them in Apply_On and empty your messages/ .rs files.
  Apply_On:
  - 'join'
  - 'quit'
  - 'death'
  - 'timed'
```
Let me know if it works. :)
