### ISSUE TITLE
Gradients Syntax

### ISSUE THREAD

**Issue by Parthurax** [kangarko/ChatControl#967]
How can i use gradients ?

i tried this in a lot different variants but i dont get the right one......
"Gradient"
Make the entire part in gradient colors. Requires MC 1.16+.

Syntax: -

Examples: "RED - GOLD" or "#123456 - #123456"

**Comment by ElBananaa** [comment]
> How can i use gradients ?
> 
> i tried this in a lot different variants but i dont get the right one......
> "Gradient"
> Make the entire part in gradient colors. Requires MC 1.16+.
> 
> Syntax: -
> 
> Examples: "RED - GOLD" or "#123456 - #123456"

Hey!
Could you please upload the file in which you are trying to use the gradients here : https://paste.gg/

**Comment by Parthurax** [comment]
Hi,
i tried it in Luckperms directly and also in Formats/chat. Already set everything back to default.
i tried:
"#123456 - #123456"
"#123456 [OWNER] #123456"
"#123456 - #123456" [OWNER]
"#123456-#123456 [OWNER]" 

And so on, with spaces, without, at beginning, at end, with ", with '

dont know whats left :/
I can give you the file but its only the default file now

**Comment by ElBananaa** [comment]
> Hi,
> i tried it in Luckperms directly and also in Formats/chat. Already set everything back to default.
> i tried:
> "#123456 - #123456"
> "#123456 [OWNER] #123456"
> "#123456 - #123456" [OWNER]
> "#123456-#123456 [OWNER]"
> 
> And so on, with spaces, without, at beginning, at end, with ", with '
> 
> dont know whats left :/
> I can give you the file but its only the default file now

It would help to see what you've done exactly before, but if it's a default file, then it's useless yeah.
Here's an example of usage in one of your format file : 
```yaml
  player-nick-admin:
    Message: '{player_nick} '
    Sender_Permission: group.admin
    Hover:
    - '&c&nClick to send a private message'
    Suggest_Command: '/tell {player_name} '
    Gradient: red - yellow
```
Your can also use `Gradient: "#FF5733 - #3371FF"` instead of `Gradient: red - yellow`.
Regarding hex colors in luckperms, here's an example of how it looks for my moderator prefix : `prefix.80.&7[#00cf9eMod&7]&e `
Let me know if it works like that. :)
