### ISSUE TITLE
Display user's rank on messages from discord

### ISSUE THREAD

**Issue by Korinocho** [kangarko/ChatControl#968]
Hi! I would like to add the rank of the user to messages that are sent from Discord. Its possible? I had it like that without chc, but now i cant add any placeholder (internal, luckperms, etc)

This is my format config:
```yaml
Parts:
  delete-chat:
    Message: '&8[&4X&8] &f'
    Hover: '&cElimina este mensaje para todos.'
    Run_Command: /{label} internal remove {message_uuid}
    Receiver_Permission: chatcontrol.removemessages
  discord-prefix:
    Message: '&8[&9Discord&8]'
    Sender_Condition: '{sender_is_discord}'
    Hover: '&bHaz click para unirte a nuestro Discord!'
    Open_Url: https://discord.gg/e8JvNAJ
  discord-msg:
    Message: ' {player_prefix}&f{player}'
    Sender_Condition: '{sender_is_discord}'
    Hover: '&bHaz click para unirte a nuestro Discord!'
    Open_Url: https://discord.gg/e8JvNAJ
  spies-prefix:
    Message: '&8[&5Spy&8] &f'
    Receiver_Condition: '{player_is_spying_{channel}}'
    Hover: '&dClick to stop spying {channel} channel.'
    Run_Command: /{label_spy} toggle chat {channel}
  prefix:
    Sender_Condition: '{sender_is_player}'
    Message: '{luckperms_suffix}{luckperms_prefix}'
    Hover:
    - '&7{player_prefix}{player_name} {player_suffix}'
    - '&7Ping&8: &f{ping}ms'
    - '&7Rank&8: &f{player_group}'
    - '&7Posted: &f{timestamp}'
    - ''
    - '&7Click to learn more about ranks.'
    Open_Url: https://mineacademy.org/project-orion
  player-name:
    Sender_Condition: '{sender_is_player}'
    Message: '{cmi_user_display_name}'
    Hover: '&7Click para enviarle un mensaje.'
    Suggest_Command: '/tell {player_name} '
  message:
    Message: ': &f{message}'
```
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: true

**Comment by ElBananaa** [comment]
> Hi! I would like to add the rank of the user to messages that are sent from Discord. Its possible? I had it like that without chc, but now i cant add any placeholder (internal, luckperms, etc)
> 
> This is my format config:
> 
> ```yaml
> Parts:
>   delete-chat:
>     Message: '&8[&4X&8] &f'
>     Hover: '&cElimina este mensaje para todos.'
>     Run_Command: /{label} internal remove {message_uuid}
>     Receiver_Permission: chatcontrol.removemessages
>   discord-prefix:
>     Message: '&8[&9Discord&8]'
>     Sender_Condition: '{sender_is_discord}'
>     Hover: '&bHaz click para unirte a nuestro Discord!'
>     Open_Url: https://discord.gg/e8JvNAJ
>   discord-msg:
>     Message: ' {player_prefix}&f{player}'
>     Sender_Condition: '{sender_is_discord}'
>     Hover: '&bHaz click para unirte a nuestro Discord!'
>     Open_Url: https://discord.gg/e8JvNAJ
>   spies-prefix:
>     Message: '&8[&5Spy&8] &f'
>     Receiver_Condition: '{player_is_spying_{channel}}'
>     Hover: '&dClick to stop spying {channel} channel.'
>     Run_Command: /{label_spy} toggle chat {channel}
>   prefix:
>     Sender_Condition: '{sender_is_player}'
>     Message: '{luckperms_suffix}{luckperms_prefix}'
>     Hover:
>     - '&7{player_prefix}{player_name} {player_suffix}'
>     - '&7Ping&8: &f{ping}ms'
>     - '&7Rank&8: &f{player_group}'
>     - '&7Posted: &f{timestamp}'
>     - ''
>     - '&7Click to learn more about ranks.'
>     Open_Url: https://mineacademy.org/project-orion
>   player-name:
>     Sender_Condition: '{sender_is_player}'
>     Message: '{cmi_user_display_name}'
>     Hover: '&7Click para enviarle un mensaje.'
>     Suggest_Command: '/tell {player_name} '
>   message:
>     Message: ': &f{message}'
> ```
> 
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: true

Hey!
If you have DiscordSRV and PlaceholderAPI installed, you can try adding `{discordsrv_user_top_role_name}` in your formats.
I think this should work : 
```yaml
  discord-prefix:
    Message: '&8[&9Discord&8] {discordsrv_user_top_role_name}'
    Sender_Condition: '{sender_is_discord}'
    Hover: '&bHaz click para unirte a nuestro Discord!'
    Open_Url: https://discord.gg/e8JvNAJ
```
