### ISSUE TITLE
1.16.5. Antispam of commands is disabled in settings.yml but not really

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#989]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

This is my antispam section:
```
Anti_Spam:
  
  # true = Similarity checks below used in chat and commands will compare two messages with their
  # diacritical marks removed (such as á is turned into a) - THIS MAY BREAK RUSSIAN and other
  # languages but prevents bypassing similarity filter for English and European servers
  Similarity_Ignore_Accents: true
  
  # Settings applied to chat:
  Chat:
    
    # How many seconds must the player wait between each message? Set to 0 to disable.
    Delay: 0 seconds
    
    # Block repetitive messages if they are similar to the previous one, in percent.
    # Set to 0% to disable.
    Similarity: 95%
    
    # The amount of previous messages to check. Prevents spam like this:
    # <player> t
    # <player> lol
    # <player> t
    # <player> lol
    # Since this uses the Similarity key above it only works if Similarity is not disabled.
    Similarity_Past_Messages: 2
    
    # The threshold after which we will forgive the player for writing the same message.
    Similarity_Time: 5 seconds
    
    # Regular expressions that, if match the message, will prevent delay check from applying.
    Whitelist_Delay: []
    
    # Regular expressions that, if match the message, will prevent similarity check from applying.
    Whitelist_Similarity:
    - '^hello \w+$'
    - '^hey \w+$'
    - '^hi \w+$'
    
    # Limit how many messages the player can send in the given period,
    # for example you can restrict sending maximum 5 messages in the last 10 seconds.
    # This works differently then the delay check above because players
    # can type their messages rapidly after each other as long as the total number
    # of messages within the period is lower than the limit.
    Limit:
      
      # The period to check. Set to 0 to disable.
      Period: 10 seconds
      
      # How many messages can players send maximum in the period above?
      Max_Messages: 5
  
  # Settings applied to commands:
  Commands:
    
    # How many seconds must the player wait between each command? Set to 0 to disable.
    Delay: 10 seconds
    
    # Block repetitive commands if they are similar to the previous one, in percent.
    # Set to 0% to disable.
    Similarity: 0%
    
    # Amount of previous commands to check. Example: Setting this to 2 prevents spam like this:
    # /tell Notch lol
    # /tell Notch t
    # /tell Notch lol
    # /tell Notch t
    # Since this uses the Similarity key above it only works if Similarity is not disabled.
    Similarity_Past_Commands: 2
    
    # The threshold after which we will forgive the player for running the same command.
    Similarity_Time: 10 seconds
    
    # Commands the player can type bypassing the Delay above. We check the command label
    # so if you put "/tell" there, "/tell ANYTHING" will be matched.
    #
    # Whitelist_Delay:
    #   - /spawn
    #   - /hello

    Whitelist_Delay:
    - '@blacklist'
    - '/cleanlight'
    - '/setfloor'
    - '/setmain'
    - '/spawn'
    - '/plot home'
```
As you may see the spam of the commands is disabled. But when I type /afk very fast and many times, for example, than the bugged message appears:
![Minecraft_ 1 16 5 - Multiplayer (3rd-party Server) 14_05_2021 6 57 23](https://user-images.githubusercontent.com/32280863/118219336-f6d70680-b481-11eb-92e6-314a3b9e1c2f.png)

"You can only send commands in second"

AND also I think the "slow down chat" msg should not appear as well because commands may be spammed unlike non-command messages
