### ISSUE TITLE
1.16.5 {killer_item} placeholder does not work in death messages

### ISSUE THREAD

**Issue by nikitushu2** [kangarko/ChatControl#999]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

**Comment by ElBananaa** [comment]
> Minecraft Version: 1.16.5
> MySQL: false
> BungeeCord: false

Hey!
Could you please try `[killer_item]` instead?

**Comment by nikitushu2** [comment]
[killer_item] works but it unnecessarily put the name into square brackets (example, "..killed by [Diamond Sword]). The placeholder without brackets is not working though. Is it a bug?

**Comment by ElBananaa** [comment]
> [killer_item] works but it unnecessarily put the name into square brackets (example, "..killed by [Diamond Sword]). The placeholder without brackets is not working though. Is it a bug?

I don't have a such issue on my end. Could you please send me the content of the `/plugins/ChatControlRed/variables/killer-item.yml` file?

**Comment by nikitushu2** [comment]
```
# -------------------------------------------------------------------------------------------------
# ChatControl supports dynamic, high performance variables you create! They can be used across
# the plugin, for example in formatting your chat or death messages. Currently, the folder
# variables/ stores all custom variables in each separate yml file.
#
# Variables can not only be used to display information, but because you can write your own full
# code in JavaScript to display them, they can also do whatever you would wish for your
# players/server, such as sneaking in code to send sounds or spawn monsters.
#
# Coding this variable requires a little bit of JavaScript knowledge, see the link below.
#
# For documentation and help, please see this link:
# https://github.com/kangarko/ChatControl-Red/wiki/JavaScript-Variables
# -------------------------------------------------------------------------------------------------

# Where should this variable be used?
#
# FORMAT = used in your formats with {syntax}, players cannot use it
# MESSAGE = players can use it with [syntax] in their chat messages
Type: message

# The key we look for in the chat surrounded by [] brackets, example:
# chat message: "Hello everyone, I have an [item] in my hand" if your key is equal to "item"
Key: killer_item

# The value the key will be replaced to. This uses JavaScript.
Value: |-
    
    // A valid JavaScript code follows below. You can use the "player" variable to get
    // Bukkit's player instance. 
    itemDisplayName();
    
    function itemDisplayName() {
        var item = player.getInventory().getItemInHand();
    
        // Change these three variables to alter the color of the killer item and what name
        // shall we use if killer had no item
        var textColor = '&a';
        var bracketColor = '&f';
        var airName = 'fists';
    
        if (item.hasItemMeta() && item.getItemMeta().hasDisplayName()) {
            var itemName = player.getInventory().getItemInHand().getItemMeta().getDisplayName();
    
            return bracketColor + '[' + textColor + itemName + bracketColor + ']';
    
        } else {
            var wordUtils = Java.type("org.apache.commons.lang.WordUtils");
    
            var itemMaterial = player.getInventory().getItemInHand().getType().name();
            var itemDefaultName = wordUtils.capitalizeFully(itemMaterial.contains("AIR") ? airName : itemMaterial.replaceAll('_', ' '));
    
            return bracketColor + '[' + textColor + itemDefaultName + bracketColor + ']';
        }
    }

# What JavaScript condition must return true for this variable to show?
# You can put variables in here to get replaced.
Sender_Condition: ''

# What permission must the message sender have in order for this variable to display to him?
Sender_Permission: ''

# See Sender_Condition, except that we evaluate the JavaScript for each chat message receiver
# and only show the message to those receivers for which the condition returns true.
Receiver_Condition: ''

# What permission must the message receiver have in order for this variable to display to them?
Receiver_Permission: ''

# What texts should be displayed when we hover the mouse
# over this variable in the chat
Hover: []

# What ItemStack should be displayed when we hover the mouse over this variable in the chat
Hover_Item: player.getItemInHand()

# What website URL should be opened when we click with the mouse
# on this variable in the chat
Open_Url: ''

# What command should appear in the player command box on his screen
# if he clicks on this variable in the chat
Suggest_Command: ''

# What command should run as the sender when he clicks the mouse on this variable?
# Minecraft only supports 1 command!
Run_Command: ''

```

**Comment by ElBananaa** [comment]
> ```
> # -------------------------------------------------------------------------------------------------
> # ChatControl supports dynamic, high performance variables you create! They can be used across
> # the plugin, for example in formatting your chat or death messages. Currently, the folder
> # variables/ stores all custom variables in each separate yml file.
> #
> # Variables can not only be used to display information, but because you can write your own full
> # code in JavaScript to display them, they can also do whatever you would wish for your
> # players/server, such as sneaking in code to send sounds or spawn monsters.
> #
> # Coding this variable requires a little bit of JavaScript knowledge, see the link below.
> #
> # For documentation and help, please see this link:
> # https://github.com/kangarko/ChatControl-Red/wiki/JavaScript-Variables
> # -------------------------------------------------------------------------------------------------
> 
> # Where should this variable be used?
> #
> # FORMAT = used in your formats with {syntax}, players cannot use it
> # MESSAGE = players can use it with [syntax] in their chat messages
> Type: message
> 
> # The key we look for in the chat surrounded by [] brackets, example:
> # chat message: "Hello everyone, I have an [item] in my hand" if your key is equal to "item"
> Key: killer_item
> 
> # The value the key will be replaced to. This uses JavaScript.
> Value: |-
>     
>     // A valid JavaScript code follows below. You can use the "player" variable to get
>     // Bukkit's player instance. 
>     itemDisplayName();
>     
>     function itemDisplayName() {
>         var item = player.getInventory().getItemInHand();
>     
>         // Change these three variables to alter the color of the killer item and what name
>         // shall we use if killer had no item
>         var textColor = '&a';
>         var bracketColor = '&f';
>         var airName = 'fists';
>     
>         if (item.hasItemMeta() && item.getItemMeta().hasDisplayName()) {
>             var itemName = player.getInventory().getItemInHand().getItemMeta().getDisplayName();
>     
>             return bracketColor + '[' + textColor + itemName + bracketColor + ']';
>     
>         } else {
>             var wordUtils = Java.type("org.apache.commons.lang.WordUtils");
>     
>             var itemMaterial = player.getInventory().getItemInHand().getType().name();
>             var itemDefaultName = wordUtils.capitalizeFully(itemMaterial.contains("AIR") ? airName : itemMaterial.replaceAll('_', ' '));
>     
>             return bracketColor + '[' + textColor + itemDefaultName + bracketColor + ']';
>         }
>     }
> 
> # What JavaScript condition must return true for this variable to show?
> # You can put variables in here to get replaced.
> Sender_Condition: ''
> 
> # What permission must the message sender have in order for this variable to display to him?
> Sender_Permission: ''
> 
> # See Sender_Condition, except that we evaluate the JavaScript for each chat message receiver
> # and only show the message to those receivers for which the condition returns true.
> Receiver_Condition: ''
> 
> # What permission must the message receiver have in order for this variable to display to them?
> Receiver_Permission: ''
> 
> # What texts should be displayed when we hover the mouse
> # over this variable in the chat
> Hover: []
> 
> # What ItemStack should be displayed when we hover the mouse over this variable in the chat
> Hover_Item: player.getItemInHand()
> 
> # What website URL should be opened when we click with the mouse
> # on this variable in the chat
> Open_Url: ''
> 
> # What command should appear in the player command box on his screen
> # if he clicks on this variable in the chat
> Suggest_Command: ''
> 
> # What command should run as the sender when he clicks the mouse on this variable?
> # Minecraft only supports 1 command!
> Run_Command: ''
> ```

Replace it with this and it should fix your problem :) 
```yaml
# -------------------------------------------------------------------------------------------------
# ChatControl supports dynamic, high performance variables you create! They can be used across
# the plugin, for example in formatting your chat or death messages. Currently, the folder
# variables/ stores all custom variables in each separate yml file.
#
# Variables can not only be used to display information, but because you can write your own full
# code in JavaScript to display them, they can also do whatever you would wish for your
# players/server, such as sneaking in code to send sounds or spawn monsters.
#
# Coding this variable requires a little bit of JavaScript knowledge, see the link below.
#
# For documentation and help, please see this link:
# https://github.com/kangarko/ChatControl-Red/wiki/JavaScript-Variables
# -------------------------------------------------------------------------------------------------

# Where should this variable be used?
#
# FORMAT = used in your formats with {syntax}, players cannot use it
# MESSAGE = players can use it with [syntax] in their chat messages
Type: message

# The key we look for in the chat surrounded by [] brackets, example:
# chat message: "Hello everyone, I have an [item] in my hand" if your key is equal to "item"
Key: killer_item

# The value the key will be replaced to. This uses JavaScript.
Value: |-
    
    // A valid JavaScript code follows below. You can use the "player" variable to get
    // Bukkit's player instance. 
    itemDisplayName();
    
    function itemDisplayName() {
        var item = player.getInventory().getItemInHand();
    
        // Change these three variables to alter the color of the killer item and what name
        // shall we use if killer had no item
        var textColor = '&a';
        var airName = 'fists';
    
        if (item.hasItemMeta() && item.getItemMeta().hasDisplayName()) {
            var itemName = player.getInventory().getItemInHand().getItemMeta().getDisplayName();
    
            return textColor + itemName;
    
        } else {
            var wordUtils = Java.type("org.apache.commons.lang.WordUtils");
    
            var itemMaterial = player.getInventory().getItemInHand().getType().name();
            var itemDefaultName = wordUtils.capitalizeFully(itemMaterial.contains("AIR") ? airName : itemMaterial.replaceAll('_', ' '));
    
            return textColor + itemDefaultName;
        }
    }

# What JavaScript condition must return true for this variable to show?
# You can put variables in here to get replaced.
Sender_Condition: ''

# What permission must the message sender have in order for this variable to display to him?
Sender_Permission: ''

# See Sender_Condition, except that we evaluate the JavaScript for each chat message receiver
# and only show the message to those receivers for which the condition returns true.
Receiver_Condition: ''

# What permission must the message receiver have in order for this variable to display to them?
Receiver_Permission: ''

# What texts should be displayed when we hover the mouse
# over this variable in the chat
Hover: []

# What ItemStack should be displayed when we hover the mouse over this variable in the chat
Hover_Item: player.getItemInHand()

# What website URL should be opened when we click with the mouse
# on this variable in the chat
Open_Url: ''

# What command should appear in the player command box on his screen
# if he clicks on this variable in the chat
Suggest_Command: ''

# What command should run as the sender when he clicks the mouse on this variable?
# Minecraft only supports 1 command!
Run_Command: ''
```
